"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.category_links import CategoryLinks
from pylzt.models.forum.category_permissions import CategoryPermissions


class Category(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/categorieslist
    """

    category_id: int
    category_title: str
    category_description: str
    icon_content: str
    active_icon_content: str
    links: CategoryLinks
    permissions: CategoryPermissions
