"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pydantic import Field

from pylzt.models.base import LolzObject


class CategoryLinks(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/categorieslist
    """

    permalink: str
    detail: str
    sub_categories: str = Field(alias="sub-categories")
    sub_forums: str = Field(alias="sub-forums")
