"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from typing import Any

from pylzt.models.base import LolzObject
from pylzt.models.forum.contest_permissions import ContestPermissions


class ContentContest(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/formscreate
    """

    type: str
    finish_date: int
    now_count_members: int
    needed_members: int
    is_finished: int
    count_winners: int
    require_like_count: int
    require_total_like_count: int
    prize_type: str
    prize_type_phrase: str
    prize_data: dict[str, Any]
    prize_cost: int
    is_money_places: int
    chance_to_win: float
    prize_per_winner: int | None = None
    prize_places: dict[str, Any] | None = None
    already_participate: bool
    permissions: ContestPermissions
