"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from typing import Any

from pylzt.models.base import LolzObject
from pylzt.models.forum.first_post_delete_info import FirstPostDeleteInfo
from pylzt.models.forum.first_post_links import FirstPostLinks
from pylzt.models.forum.first_post_permissions import FirstPostPermissions


class ContentFirstPost(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/formscreate
    """

    post_id: int
    thread_id: int
    poster_user_id: int
    poster_username: str
    poster_username_html: str
    poster_is_banned: int
    poster_is_staff: int
    post_create_date: int
    post_body: str
    post_body_html: str
    post_body_plain_text: str
    signature: str
    signature_html: str
    signature_plain_text: str
    post_like_count: int
    delete_info: FirstPostDeleteInfo | None = None
    user_is_ignored: bool
    post_is_sticked: bool
    post_is_published: bool
    post_is_deleted: bool
    post_update_date: int
    post_is_first_post: bool
    post_is_liked: bool
    links: FirstPostLinks
    permissions: FirstPostPermissions
    thread_is_deleted: bool
    thread_is_closed: bool
    thread: dict[str, Any]
