"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.permissions_bump import PermissionsBump


class ContentPermissions(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/formscreate
    """

    view: bool
    delete: bool
    follow: bool
    post: bool
    edit: bool
    bump: PermissionsBump
