"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject


class ContentLinks(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/formscreate
    """

    permalink: str
    detail: str
    followers: str
    forum: str
    posts: str
    first_poster: str
    first_poster_avatar: str
    first_post: str
    last_poster: str | None = None
    last_post: str | None = None
