"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.conversations_messages_list_message import (
    ConversationsMessagesListMessage,
)
from pylzt.models.forum.links import Links


class ConversationsMessagesListResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/conversationsmessageslist
    """

    messages: list[ConversationsMessagesListMessage]
    messages_total: int
    links: Links
