"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.user_custom_fields import UserCustomFields
from pylzt.models.forum.user_links import UserLinks
from pylzt.models.forum.user_permissions import UserPermissions


class FollowersUser(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/usersfollowers
    """

    content_type: str
    content_id: int
    follow_date: int
    user_id: int
    username: str
    username_html: str
    user_message_count: int
    user_register_date: int
    user_like_count: int
    user_like2_count: int
    contest_count: int
    trophy_count: int
    custom_title: str
    is_banned: int
    user_title: str
    user_is_valid: bool
    user_is_verified: bool
    user_is_followed: bool
    user_last_seen_date: int
    user_following_count: int
    user_followers_count: int
    links: UserLinks
    permissions: UserPermissions
    user_is_ignored: bool
    user_is_visitor: bool
    user_group_id: int
    custom_fields: UserCustomFields
