"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.links import Links
from pylzt.models.forum.user import User


class ForumsFollowersResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/forumsfollowers
    """

    users: User
    users_total: int | None = None
    links: Links | None = None
