"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.forum import Forum
from pylzt.models.forum.forums_list_tab import ForumsListTab


class ForumsListResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/forumslist
    """

    forums: list[Forum]
    forums_total: int
    tabs: list[ForumsListTab]
