"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.user_rendered import UserRendered


class Ignored(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/chatboxgetignore
    """

    avatar_date: int
    background_date: int
    contest_count: int
    custom_title: str
    display_banner_id: int
    display_icon_group_id: int
    display_style_group_id: int
    is_banned: bool
    last_activity: int
    like2_count: int
    like_count: int
    message_count: int
    register_date: int
    rendered: UserRendered
    short_link: str
    trophy_points: int
    uniq_banner: str
    uniq_username_css: str
    user_id: int
    username: str
