"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.ignore_custom_fields import IgnoreCustomFields
from pylzt.models.forum.ignore_rendered import IgnoreRendered


class Ignore(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/chatboxindex
    """

    can_edit: bool
    can_follow: bool
    can_ignore: bool
    can_post_profile: bool
    can_view_profile: bool
    can_view_profile_posts: bool
    can_warn: bool
    contest_count: int
    conv_auto_reply_message: str
    conv_welcome_message: str
    convertedDeposit: int
    custom_fields: IgnoreCustomFields
    deposit: int
    display_banner_id: int
    display_icon_group_id: int
    gender: str
    homepage: str
    is_admin: bool
    is_banned: bool
    is_followed: bool
    is_ignored: bool
    is_moderator: bool
    is_staff: bool
    last_activity: int
    like2_count: int
    like_count: int
    location: str
    message_count: int
    occupation: str
    register_date: int
    rendered: IgnoreRendered
    short_link: str
    trophy_points: int
    user_id: int
    user_title: str
    username: str
    view_url: str
    warning_points: int
