"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pydantic import Field

from pylzt.models.base import LolzObject


class IgnoreCustomFields(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/chatboxindex
    """

    field_4: str = Field(alias="_4")
    scamURL: str
    favoritePorn: str
    favoriteVape: str
    favoriteAnime: str
    lztLikesZeroing: str
    lztLikesIncreasing: str
    lztSympathyZeroing: str
    lztSympathyIncreasing: str
    telegram: str
    vk: str
    discord: str
    steam: str
    matrix: str
    jabber: str
    github: str
