"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pydantic import Field

from pylzt.models.base import LolzObject
from pylzt.models.forum.link_forum import LinkForum


class LinksListResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/linkslist
    """

    link_forums: list[LinkForum] = Field(alias="link-forums")
    link_forums_total: int = Field(alias="link-forums_total")
