"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pydantic import AliasPath, Field

from pylzt.models.base import LolzObject
from pylzt.models.forum.link_forum_links import LinkForumLinks


class LinkForum(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/linksget
    """

    link_id: int
    link_title: str
    link_description: str
    icon_content: str
    active_icon_content: str
    links: LinkForumLinks
    view: bool = Field(validation_alias=AliasPath("permissions", "view"))
