"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject


class MessageRecipient(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/conversationsmessagesedit
    """

    user_id: int
    username: str
    username_html: str
    last_activity: int
    is_online: bool
    contacts_changed: bool
    avatar: str
