"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject


class Permissions(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/chatboxindex
    """

    viewMessages: bool
    viewAnyMessage: bool
    editAnyMessage: bool
    deleteAnyMessage: bool
    ban: bool
    postMessage: bool
    report: bool
