"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pydantic import AliasPath, Field

from pylzt.models.base import LolzObject
from pylzt.models.forum.poll_permissions import PollPermissions
from pylzt.models.forum.threads_poll_get_response import ThreadsPollGetResponse


class Poll(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/threadspollget
    """

    poll_id: int
    poll_question: str
    poll_vote_count: int
    poll_max_votes: int
    poll_is_open: bool
    poll_is_voted: bool
    responses: list[ThreadsPollGetResponse]
    permissions: PollPermissions
    vote: str = Field(validation_alias=AliasPath("links", "vote"))
