"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from typing import Any

from pylzt.models.base import LolzObject
from pylzt.models.forum.content_contest import ContentContest
from pylzt.models.forum.content_links import ContentLinks
from pylzt.models.forum.content_permissions import ContentPermissions
from pylzt.models.forum.content_thread_prefixe import ContentThreadPrefixe


class PostThread(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/postsget
    """

    thread_id: int
    forum_id: int
    thread_title: str
    thread_view_count: int
    creator_user_id: int
    creator_username: str
    creator_username_html: str
    thread_create_date: int
    thread_update_date: int
    thread_reply_group_id: int
    thread_comment_ignore_group: int
    thread_last_bump_date: int
    user_is_ignored: bool
    thread_post_count: int
    thread_is_liked: bool
    thread_is_bumped: bool
    thread_is_published: bool
    thread_is_deleted: bool
    thread_is_sticky: bool
    thread_is_closed: bool
    thread_is_followed: bool
    thread_is_starred: bool
    thread_hide_contacts: bool | None = None
    thread_allow_ask_hidden_content: bool | None = None
    first_post: dict[str, Any]
    thread_prefixes: list[ContentThreadPrefixe]
    thread_tags: dict[str, Any]
    links: ContentLinks
    permissions: ContentPermissions
    node_title: str
    last_post: dict[str, Any] | None = None
    contest: ContentContest | None = None
