"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.profile_posts_comments_create_comment_links import (
    ProfilePostsCommentsCreateCommentLinks,
)
from pylzt.models.forum.profile_posts_comments_create_comment_permissions import (
    ProfilePostsCommentsCreateCommentPermissions,
)


class ProfilePostsCommentsEditComment(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/profilepostscommentscreate
    """

    comment_id: int
    profile_post_id: int
    comment_user_id: int
    comment_username: str
    comment_username_html: str
    comment_create_date: int
    comment_body: str
    user_is_ignored: bool
    timeline_user_id: int
    links: ProfilePostsCommentsCreateCommentLinks
    permissions: ProfilePostsCommentsCreateCommentPermissions
