"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.forums_followers_permissions_bump import ForumsFollowersPermissionsBump


class ProfileThreadPermissions(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/forumsfollowers
    """

    view: bool
    delete: bool
    follow: bool
    post: bool
    bump: ForumsFollowersPermissionsBump
