"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject


class ProfilePostLinks(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/profilepostscommentslist
    """

    permalink: str
    detail: str
    timeline: str
    timeline_user: str
    poster: str
    likes: str
    comments: str
    report: str
    poster_avatar: str
