"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.links import Links
from pylzt.models.forum.profile_posts_get_profile_post import ProfilePostsGetProfilePost


class ProfilePostsListResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/profilepostslist
    """

    profile_posts: list[ProfilePostsGetProfilePost]
    totalProfilePosts: int
    canPostOnProfile: bool
    links: Links
