"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.profile_post_links import ProfilePostLinks
from pylzt.models.forum.profile_posts_get_profile_post_permissions import (
    ProfilePostsGetProfilePostPermissions,
)
from pylzt.models.forum.user import User


class ProfilePostsGetProfilePost(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/profilepostsget
    """

    profile_post_id: int
    timeline_user_id: int
    poster_user_id: int
    poster_username: str
    poster_username_html: str
    post_create_date: int
    post_body: str
    post_body_html: str
    post_body_plain_text: str
    post_like_count: int
    post_comment_count: int
    post_comments_is_disabled: int
    timeline_username: str
    user_is_ignored: bool
    post_is_published: bool
    post_is_deleted: bool
    post_is_liked: bool
    post_is_sticked: bool
    links: ProfilePostLinks
    permissions: ProfilePostsGetProfilePostPermissions
    timeline_user: User
