"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject


class PublicGroupListMonitorList(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/uptimeinfo
    """

    id: int
    name: str
    sendUrl: int
    type: str
