"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from typing import Any

from pydantic import AliasPath, Field

from pylzt.models.base import LolzObject
from pylzt.models.forum.user_edit_permissions import UserEditPermissions
from pylzt.models.forum.user_field import UserField
from pylzt.models.forum.user_links import UserLinks
from pylzt.models.forum.user_permissions import UserPermissions
from pylzt.models.forum.user_profile_thread import UserProfileThread
from pylzt.models.forum.user_user_external_authentication import UserUserExternalAuthentication
from pylzt.models.forum.user_user_following import UserUserFollowing
from pylzt.models.forum.user_user_group import UserUserGroup


class SearchAllUser(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/searchall
    """

    user_id: int
    username: str
    username_html: str
    user_message_count: int
    user_register_date: int
    user_like_count: int
    user_like2_count: int
    contest_count: int
    trophy_count: int
    short_link: str
    custom_title: str
    is_banned: int
    display_banner_id: int
    display_icon_group_id: int
    balance: str
    hold: str
    currency: str
    user_email: str
    user_unread_notification_count: int
    user_unread_conversation_count: int
    conv_welcome_message: str
    show_dob_dateshow_dob_date: int | None = None
    show_dob_year: int
    user_title: str
    user_deposit: int
    user_is_valid: bool
    user_is_verified: bool
    user_is_followed: bool
    user_last_seen_date: int
    links: UserLinks
    permissions: UserPermissions
    user_is_ignored: bool
    user_is_visitor: bool
    user_group_id: int
    curator_titles: list[str]
    user_groups: list[UserUserGroup]
    fields: list[UserField]
    user_timezone_offset: int
    user_external_authentications: list[UserUserExternalAuthentication]
    create_conversation: bool = Field(
        validation_alias=AliasPath("self_permissions", "create_conversation")
    )
    edit_permissions: UserEditPermissions
    birthday: dict[str, Any] | None = None
    secret_answer_rendered: str
    secret_answer_first_letter: str
    user_following: UserUserFollowing
    user_followers: UserUserFollowing
    profile_threads: list[UserProfileThread]
    banner: str
