"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.content import Content
from pylzt.models.forum.links import Links
from pylzt.models.forum.tag import Tag


class TagsGetResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/tagsget
    """

    tag: Tag
    tagged: list[Content]
    tagged_total: int
    links: Links
