"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.forum_links import ForumLinks
from pylzt.models.forum.threads_list_forum_permissions import ThreadsListForumPermissions


class ThreadsListForum(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/threadslist
    """

    forum_id: int
    forum_title: str
    forum_description: str
    forum_thread_count: int
    forum_post_count: int
    forum_prefixes: list[str]
    thread_default_prefix_id: int
    thread_prefix_is_required: bool
    links: ForumLinks
    permissions: ThreadsListForumPermissions
    forum_is_followed: bool
