"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject


class TrophyProgresseProgress(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/userstrophies
    """

    left: int
    need_total: str
    needTotalPhrase: str
    leftPhrase: str
    completed_total: int
    percents_completed: float
