"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from typing import Any

from pylzt.models.base import LolzObject


class Trophy(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/userstrophies
    """

    trophy_id: int
    title: str
    description: str
    trophy_url: str
    award_date: int
    rarity: str
    usersHasTrophyPercentage: float
    rarityPhrase: str
    trophy_counter: int
    counter: str | None = None
    available_levels: dict[str, Any] | None = None
    current_display_level: int | None = None
