"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from typing import Any

from pylzt.models.base import LolzObject


class UptimeHeartbeatResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/uptimeheartbeat
    """

    heartbeatList: dict[str, Any]
    uptimeList: dict[str, Any]
