"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.config import Config
from pylzt.models.forum.incident import Incident
from pylzt.models.forum.maintenance_list import MaintenanceList
from pylzt.models.forum.public_group_list import PublicGroupList


class UptimeInfoResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/uptimeinfo
    """

    config: Config
    incidents: list[Incident] | None = None
    publicGroupList: list[PublicGroupList]
    maintenanceList: list[MaintenanceList] | None = None
