"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject


class UserEditPermissions(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/searchall
    """

    password: bool
    user_email: bool
    username: bool
    user_title: bool
    short_link: bool
    hide_username_logs: bool
    primary_group_id: bool
    secondary_group_ids: bool
    user_dob_day: bool
    user_dob_month: bool
    user_dob_year: bool
    fields: bool
