"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pydantic import Field

from pylzt.models.base import LolzObject


class UsersFollowingsUserCustomFields(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/usersfollowings
    """

    field_4: str = Field(alias="_4")
    allowSelfUnban: list[str]
    discord: str
    github: str
    jabber: str
    lztAwardUserTrophy: str
    lztCuratorNodeTitle: str
    lztCuratorNodeTitleEn: str
    lztDeposit: str
    lztInnovation20Link: str
    lztInnovation30Link: str
    lztInnovationLink: str
    lztLikesIncreasing: str
    lztLikesZeroing: str
    lztSympathyIncreasing: str
    lztSympathyZeroing: str
    maecenasValue: str
    scamURL: str
    steam: str
    telegram: str
    vk: str
