"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject


class UserUserGroup(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/searchall
    """

    user_group_id: int
    user_group_title: str
    user_group_title_en: str
    user_group_banner_css_class: str
    user_group_banner_text: str
    user_group_banner_text_en: str
    display_group_selectable: bool
    display_banner_selectable: bool
    display_icon_selectable: bool
    is_primary_group: bool
    user_group_icon_class: str
