"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.field_choice import FieldChoice


class UserField(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/searchall
    """

    id: str
    title: str
    description: str
    position: str
    is_required: bool
    is_system: bool
    value: str | None = None
    editable: bool
    is_multi_choice: bool
    choices: list[FieldChoice]
    values: list[str]
