"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.links import Links


class UsersResponse[UsersResponseUserT](LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec."""

    users: list[UsersResponseUserT]
    users_total: int
    links: Links
