"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.forum.profile_thread_links import ProfileThreadLinks
from pylzt.models.forum.profile_thread_permissions import ProfileThreadPermissions


class UserProfileThread(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lolzteam.readme.io/reference/searchall
    """

    thread_id: int
    forum_id: int
    thread_title: str
    thread_view_count: int
    creator_user_id: int
    creator_username: str
    creator_username_html: str
    thread_create_date: int
    thread_update_date: int
    thread_reply_group_id: int
    thread_comment_ignore_group: int
    thread_last_bump_date: int
    thread_hide_contacts: int
    thread_allow_ask_hidden_content: int
    user_is_ignored: bool
    thread_post_count: int
    thread_is_bumped: bool
    thread_is_published: bool
    thread_is_deleted: bool
    thread_is_sticky: bool
    thread_is_closed: bool
    thread_is_followed: bool
    thread_is_starred: bool
    thread_prefixes: list[str]
    thread_tags: dict[str, str]
    links: ProfileThreadLinks
    permissions: ProfileThreadPermissions
    node_title: str
