"""Generate BaseMethod[T] skeletons + response DTOs + enums for pylzt from the
official OpenAPI spec merged by `dev/codegen/scraper.py`.

The official spec carries full response schemas, so this tool also drafts response
models with from_raw/from_raw_many classmethods, matching the project's existing model
convention (src/pylzt/models/lot.py etc). Output lands in the `generated/` subpackages
under `src/pylzt/{methods,models,enums,facades}/`.

This module is the low-level generator. The normal entrypoint is the atomic pipeline
`python -m dev.codegen build`, which generates, validates (ruff + mypy) and only then
installs. Run this module directly only for the draft `--enums` / `--docs` side-outputs:
    python -m dev.codegen.generator --spec <spec.json> --api market --enums
    python -m dev.codegen.generator --spec <spec.json> --api market --docs
"""

from __future__ import annotations

import argparse
import json
import keyword
import re
from dataclasses import dataclass, replace
from enum import StrEnum
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
METHODS_DIR = REPO_ROOT / "src" / "pylzt" / "methods"
GENERATED_DIR = REPO_ROOT / "dev" / "generated"
# `generate` writes flat here; the separate `install` step promotes into the lib.
STAGING_ROOT = REPO_ROOT / "dev" / "codegen" / "generated"
# Every generated file carries one of these in its header — the marker(s) that tell
# `install` (and `_existing_endpoints`) a file is ours to own vs a hand-written module
# to protect. GEN_MARKER is the CURRENT header text new output carries; GEN_MARKERS_ALL
# also recognizes the pre-rename header still on file for market/forum modules that
# haven't been regenerated since (never let a stale header make `install` think an old
# generated file is hand-written and refuse to touch it).
GEN_MARKER = "Generated by forge — DO NOT EDIT."
GEN_MARKERS_ALL = (GEN_MARKER, "Auto-generated from the official readme.io OpenAPI")


class ModelBackend(StrEnum):
    """Response-DTO codegen target — request method skeletons always stay frozen
    dataclasses (the BaseMethod[T] contract), only response DTOs are switchable."""

    PYDANTIC = "pydantic"
    DATACLASS = "dataclass"


OPENAPI_TO_PY_TYPE = {
    "integer": "int",
    "number": "float",
    "string": "str",
    "boolean": "bool",
}

# Split camelCase AND acronym→Word boundaries: "CategoryEAResponse" → Category|EA|Response
# (so an acronym like EA/LLM/API doesn't glue to the next word and hide the shared name stem).
ACRONYM_SAFE_SPLIT = re.compile(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")


@dataclass(frozen=True, slots=True)
class ExtractedEnum:
    name: str
    members: tuple[tuple[str, str], ...]  # (member_id, wire_value); tuple → hashable/dedupable


@dataclass(frozen=True, slots=True)
class ExtractedParam:
    name: str  # sanitized, valid Python identifier
    wire_name: str  # raw OpenAPI param/field name — may differ (e.g. PHP-style "foo[]")
    annotation: str  # enum-substituted; arrays become tuple[...] for the frozen dataclass field
    location: str  # "path" | "query" | "body"
    required: bool
    description: str | None
    enum: ExtractedEnum | None  # set when the schema (or its array items) is a string enum


@dataclass(frozen=True, slots=True)
class ExtractedField:
    name: str  # sanitized, valid Python identifier
    wire_name: str  # raw response key — may differ (e.g. "link-forum")
    annotation: str
    description: str | None
    enum: ExtractedEnum | None
    # Set when a single-field object wrapper was collapsed: the wire keys to dig through,
    # rendered as Field(validation_alias=AliasPath(*alias_path)). None → plain field/alias.
    alias_path: tuple[str, ...] | None = None
    # True when the spec's own `required` list omits this field, or its schema's OpenAPI
    # 3.1 type array includes "null" — renders as `X | None = None` instead of a required
    # field, so a live response omitting/nulling it (per docs/codegen-runbook.md's
    # recurring "spec said required, live response omits it" bug class) parses instead of
    # raising, without needing a hand-patch for every individual field that turns out loose.
    nullable: bool = False


@dataclass(frozen=True, slots=True)
class ExtractedModel:
    name: str
    fields: list[ExtractedField]
    source_url: str | None  # readme.io page the owning response was scraped from
    # Set by the post-build collapse pass (see _collapse_models):
    base: str = "LolzObject"  # a synthesized `Base<Stem>` when this model subclasses one (Rule 2)
    type_params: tuple[
        str, ...
    ] = ()  # TypeVar names → `Generic[...]` when this is a generic base (Rule 1)


@dataclass(frozen=True, slots=True)
class ExtractedOperation:
    operation_id: str
    domain: str
    path: str
    http_method: str
    summary: str
    description: str | None
    params: list[ExtractedParam]
    response_schema: dict[str, Any] | None  # resolved 200 schema; models built at render time
    source_url: str | None  # readme.io reference page this operation was scraped from


def _load_spec(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _resolve_ref(spec: dict[str, Any], ref: str) -> dict[str, Any]:
    # refs are always local, e.g. "#/components/responses/BuyItem"
    parts = ref.lstrip("#/").split("/")
    node: Any = spec
    for part in parts:
        node = node[part]
    return node


def _snake(name: str) -> str:
    split = ACRONYM_SAFE_SPLIT.sub("_", name)
    return re.sub(r"[^a-zA-Z0-9]+", "_", split).strip("_").lower()


def _py_identifier(wire_name: str) -> str:
    """Sanitize a wire name (e.g. PHP-style "foo[]", or a keyword like "class") into a
    valid, non-reserved Python identifier."""
    ident = re.sub(r"[^a-zA-Z0-9_]+", "_", wire_name).strip("_")
    if not ident or ident[0].isdigit():
        ident = f"field_{ident}"
    if keyword.iskeyword(ident):
        ident = f"{ident}_"
    return ident


def _pascal(name: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def _domain_from_tag(tags: list[str]) -> str:
    return _snake(tags[0]) if tags else "misc"


def _enum_member_id(value: str) -> str:
    ident = _snake(value).upper()
    return ident if ident and not ident[0].isdigit() else f"V_{ident}"


# Beyond this an "enum" is a free-text dataset (e.g. every game title), not a domain
# enum — keep it as a plain str rather than exploding a 500-member StrEnum into the file.
MAX_ENUM_MEMBERS = 40

# Response schemas can be self-referential (a forum User nesting a User) or very deep;
# beyond this nesting depth a field degrades to dict[str, Any] instead of recursing.
MAX_MODEL_DEPTH = 6

# The spec models dozens of unrelated yes/no/nomatter filter params under a different
# field name each time (Tel, EditBtag, ClashPass, Spam, ...) — same wire vocabulary,
# same shape. Collapse any of them into the one hand-written `Tristate` (see
# EXISTING_TYPES_ENUMS) instead of emitting a per-field duplicate class.
_TRISTATE_VALUES = frozenset({"yes", "no", "nomatter"})


def _is_tristate(values: tuple[str, ...]) -> bool:
    vals = set(values)
    return bool(vals) and vals <= _TRISTATE_VALUES and "yes" in vals


def _enum_from_schema(schema: dict[str, Any], context_name: str) -> ExtractedEnum | None:
    """Build an ExtractedEnum if the schema is a small string enum, named after its field."""
    values = schema.get("enum")
    if not values or not all(isinstance(v, str) for v in values):
        return None
    if len(values) > MAX_ENUM_MEMBERS:
        return None
    members = tuple((_enum_member_id(v), v) for v in values)
    if _is_tristate(tuple(values)):
        return ExtractedEnum(name="Tristate", members=members)
    return ExtractedEnum(name=_pascal(context_name) or "Value", members=members)


def _schema_type(spec: dict[str, Any], schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        schema = _resolve_ref(spec, schema["$ref"])
    type_ = schema.get("type", "string")
    # OpenAPI 3.1 allows a type array for nullable fields, e.g. ["string", "null"].
    if isinstance(type_, list):
        type_ = next((t for t in type_ if t != "null"), "string")
    if type_ == "array":
        item = schema.get("items", {})
        return f"list[{_schema_type(spec, item)}]"
    if type_ == "object":
        return "dict[str, Any]"
    return OPENAPI_TO_PY_TYPE.get(type_, "str")


def _field_type(
    spec: dict[str, Any], schema: dict[str, Any], context_name: str
) -> tuple[str, ExtractedEnum | None]:
    """Resolve a schema to a Python annotation, substituting a StrEnum type where the
    schema (or its array items) carries a string `enum`. Returns (annotation, enum|None)."""
    resolved = _resolve_ref(spec, schema["$ref"]) if "$ref" in schema else schema
    type_ = resolved.get("type", "string")
    if isinstance(type_, list):
        type_ = next((t for t in type_ if t != "null"), "string")

    # OpenAPI's way of saying "raw file upload" — routed to Media (transport/base.py
    # `Request.files`), never treated as a str field (see media-upload plan).
    if type_ == "string" and resolved.get("format") == "binary":
        return "Media", None

    if type_ == "array":
        item = resolved.get("items", {})
        item_resolved = _resolve_ref(spec, item["$ref"]) if "$ref" in item else item
        enum = _enum_from_schema(item_resolved, _singularize(context_name))
        inner = enum.name if enum else _schema_type(spec, item)
        return f"list[{inner}]", enum

    enum = _enum_from_schema(resolved, context_name)
    if enum:
        return enum.name, enum
    return _schema_type(spec, resolved), None


def _singularize(name: str) -> str:
    """Rough singular for an array field name so its item enum reads naturally
    (origins -> Origin, email_provider -> EmailProvider)."""
    if name.endswith("ies"):
        return name[:-3] + "y"
    if name.endswith("s") and not name.endswith("ss"):
        return name[:-1]
    return name


def _list_to_tuple(annotation: str) -> str:
    """Frozen-dataclass fields can't hold a mutable list default; array request params
    become tuple[X, ...] (which _flatten_query still encodes as key[]=...)."""
    m = re.fullmatch(r"list\[(.+)\]", annotation)
    return f"tuple[{m.group(1)}, ...]" if m else annotation


def _extract_params(spec: dict[str, Any], op: dict[str, Any]) -> list[ExtractedParam]:
    params: list[ExtractedParam] = []
    for raw in op.get("parameters", []):
        p = _resolve_ref(spec, raw["$ref"]) if "$ref" in raw else raw
        wire = p["name"]
        annotation, enum = _field_type(spec, p.get("schema", {}), _py_identifier(wire))
        params.append(
            ExtractedParam(
                name=_py_identifier(wire),
                wire_name=wire,
                annotation=_list_to_tuple(annotation),
                location=p.get("in", "query"),
                required=bool(p.get("required", False)),
                description=p.get("description"),
                enum=enum,
            )
        )

    body_content = op.get("requestBody", {}).get("content", {})
    # A file-upload endpoint declares its body under multipart/form-data instead of
    # application/json (confirmed live: Users.Avatar.Upload / Users.Background.Upload).
    body = body_content.get("application/json", {}).get("schema") or body_content.get(
        "multipart/form-data", {}
    ).get("schema")
    if body:
        if "$ref" in body:
            body = _resolve_ref(spec, body["$ref"])
        required_fields = body.get("required", [])
        for field_name, field_schema in body.get("properties", {}).items():
            annotation, enum = _field_type(spec, field_schema, _py_identifier(field_name))
            params.append(
                ExtractedParam(
                    name=_py_identifier(field_name),
                    wire_name=field_name,
                    annotation=_list_to_tuple(annotation),
                    location="body",
                    required=field_name in required_fields,
                    description=field_schema.get("description"),
                    enum=enum,
                )
            )
    return params


def _resolve_response_schema(spec: dict[str, Any], op: dict[str, Any]) -> dict[str, Any] | None:
    """Return the resolved 200-response object schema (nested $refs left intact).

    Prefers `application/json`; a few endpoints (ListDownload, ManagingSteamPreview,
    PublicCountLinesPlain) only declare a `text/html`/`text/plain` 200 — that schema
    is still the real response shape (a bare `{"type": "string"}`), so fall back to
    whatever content type IS declared instead of dropping to `Any` for lack of a JSON
    one. `Response.text`/`BaseMethod.parse_response` carry the runtime side of this.
    """
    ok = op.get("responses", {}).get("200")
    if ok is None:
        return None
    if "$ref" in ok:
        ok = _resolve_ref(spec, ok["$ref"])
    content = ok.get("content", {})
    schema = content.get("application/json", {}).get("schema")
    if schema is None:
        schema = next((c["schema"] for c in content.values() if "schema" in c), None)
    if schema is None:
        return None
    if "$ref" in schema:
        schema = _resolve_ref(spec, schema["$ref"])
    # Return the schema whatever its shape — the caller models objects and maps everything
    # else (array / scalar / free object) to a built-in type parsed by `passthrough`.
    return schema


def _is_object(schema: dict[str, Any]) -> bool:
    return schema.get("type") == "object" and bool(schema.get("properties"))


# A wire object whose keys are UUIDs / integer indices / long hex is a MAP the spec encoded
# with concrete EXAMPLE keys (uplay_games: {"ffffffff-…": {...}}, stickers: {"0": {...}}). Such
# an object must become dict[str, V], never a model with a field named after the example key.
_DYNAMIC_KEY = re.compile(
    r"^(?:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
    r"|\d+|[0-9a-fA-F]{16,})$"
)


def _is_map_props(props: dict[str, Any]) -> bool:
    return bool(props) and all(_DYNAMIC_KEY.match(k) for k in props)


# Leaf field names too generic to name a model on their own: an `items`/`data`/`result` model
# collides across unrelated responses and gets an opaque numeric suffix (Item, Item2, …). For
# these we prefix the owning response's discriminator instead (ManagingBulkGetItem).
_GENERIC_LEAVES = frozenset(
    {"item", "data", "result", "list", "entry", "element", "node", "value", "object", "response"}
)


def _model_field_type(
    spec: dict[str, Any],
    schema: dict[str, Any],
    context_name: str,
    parent_seg: str,
    child_seg: str,
    registry: dict[tuple[tuple[str, str], ...], str],
    order: list[ExtractedModel],
    source_url: str | None,
    depth: int,
    seen_refs: frozenset[str],
    root_disc: str = "",
) -> tuple[str, ExtractedEnum | None]:
    """Like _field_type, but recurses into object/array-of-object schemas, registering a
    nested model (structurally deduped). A cyclic $ref or over-deep nesting degrades to
    dict[str, Any] rather than recursing forever.

    Nested model names are bounded to two PascalCase segments — the parent model's own leaf
    segment (`parent_seg`) plus this field's segment (`child_seg`) — so deep nesting yields
    `RenderedAvatars`, not `ChatboxGetLeaderboardResponseLeaderboardRenderedAvatars`. A generic
    leaf (item/data/result…) is instead named after `root_disc`, the owning response's
    discriminator, so `items` under different responses stays distinct without numeric suffixes."""
    if root_disc and _singularize(_snake(child_seg)) in _GENERIC_LEAVES:
        nested_base = root_disc if root_disc.endswith(child_seg) else root_disc + child_seg
    else:
        nested_base = parent_seg + child_seg
    ref = schema.get("$ref")
    if ref and ref in seen_refs:
        return "dict[str, Any]", None
    child_seen = seen_refs | {ref} if ref else seen_refs
    resolved = _resolve_ref(spec, ref) if ref else schema
    if depth >= MAX_MODEL_DEPTH:
        return "dict[str, Any]", None
    type_ = resolved.get("type", "string")
    if isinstance(type_, list):
        type_ = next((t for t in type_ if t != "null"), "string")

    if type_ == "array":
        item = resolved.get("items", {})
        item_ref = item.get("$ref")
        item_resolved = _resolve_ref(spec, item_ref) if item_ref else item
        if _is_object(item_resolved) and not (item_ref and item_ref in child_seen):
            item_seen = child_seen | {item_ref} if item_ref else child_seen
            name = _build_model(
                spec,
                _singularize(nested_base),
                item_resolved,
                registry,
                order,
                source_url,
                depth + 1,
                item_seen,
                seg=_singularize(child_seg),
                root_disc=root_disc,
            )
            return f"list[{name}]", None
        enum = _enum_from_schema(item_resolved, _singularize(context_name))
        inner = enum.name if enum else _schema_type(spec, item)
        return f"list[{inner}]", enum

    if _is_object(resolved):
        props = resolved["properties"]
        if _is_map_props(props):
            value_schema = next(iter(props.values()))
            v_ref = value_schema.get("$ref")
            v_resolved = _resolve_ref(spec, v_ref) if v_ref else value_schema
            if _is_object(v_resolved) and not (v_ref and v_ref in child_seen):
                v_seen = child_seen | {v_ref} if v_ref else child_seen
                vname = _build_model(
                    spec,
                    _singularize(nested_base),
                    v_resolved,
                    registry,
                    order,
                    source_url,
                    depth + 1,
                    v_seen,
                    seg=_singularize(child_seg),
                    root_disc=root_disc,
                )
                return f"dict[str, {vname}]", None
            return f"dict[str, {_schema_type(spec, v_resolved)}]", None
        name = _build_model(
            spec,
            nested_base,
            resolved,
            registry,
            order,
            source_url,
            depth + 1,
            child_seen,
            seg=child_seg,
            root_disc=root_disc,
        )
        return name, None

    enum = _enum_from_schema(resolved, context_name)
    if enum:
        return enum.name, enum
    return _schema_type(spec, resolved), None


def _build_model(
    spec: dict[str, Any],
    base_name: str,
    schema: dict[str, Any],
    registry: dict[tuple[tuple[str, str], ...], str],
    order: list[ExtractedModel],
    source_url: str | None,
    depth: int = 0,
    seen_refs: frozenset[str] = frozenset(),
    seg: str = "",
    root_disc: str = "",
) -> str:
    """Register an ExtractedModel for an object schema, deduped by structural signature.
    Returns the model's class name. Nested models are registered first."""
    fields: list[ExtractedField] = []
    props = {n: s for n, s in schema.get("properties", {}).items() if n != "system_info"}
    required = set(schema.get("required", []))
    top_names = {_py_identifier(n) for n in props}
    used: set[str] = set()
    for name, field_schema in props.items():
        # Collapse single-field object wrappers: descend while the field is an object with
        # exactly one property, digging the wire path, so A{b: B{n}} yields A.n with
        # validation_alias=AliasPath("b", "n") — one fewer pointless class, wire preserved.
        path = [name]
        leaf_schema = field_schema
        cur = _resolve_ref(spec, field_schema["$ref"]) if "$ref" in field_schema else field_schema
        while (
            _is_object(cur) and len(cur.get("properties", {})) == 1 and len(path) <= MAX_MODEL_DEPTH
        ):
            only_key, only_schema = next(iter(cur["properties"].items()))
            if only_key == "system_info" or _DYNAMIC_KEY.match(only_key):
                break
            path.append(only_key)
            leaf_schema = only_schema
            cur = _resolve_ref(spec, only_schema["$ref"]) if "$ref" in only_schema else only_schema
        leaf_name = _py_identifier(path[-1])
        collapse = (
            len(path) > 1
            and leaf_name not in used
            and not (leaf_name in top_names and leaf_name != _py_identifier(name))
        )
        if not collapse:
            path, leaf_schema, leaf_name = [name], field_schema, _py_identifier(name)
            cur = (
                _resolve_ref(spec, field_schema["$ref"]) if "$ref" in field_schema else field_schema
            )
        used.add(leaf_name)
        annotation, enum = _model_field_type(
            spec,
            leaf_schema,
            leaf_name,
            seg,
            _pascal(path[-1]),
            registry,
            order,
            source_url,
            depth,
            seen_refs,
            root_disc=root_disc,
        )
        cur_type = cur.get("type")
        nullable = name not in required or (isinstance(cur_type, list) and "null" in cur_type)
        fields.append(
            ExtractedField(
                name=leaf_name,
                wire_name=name,
                annotation=annotation,
                description=cur.get("description"),
                enum=enum,
                alias_path=tuple(path) if len(path) > 1 else None,
                nullable=nullable,
            )
        )
    # Dedup key is order-insensitive: the same field set in a different order (readme.io
    # fragments vary) is the same model, so it reuses one class instead of a numbered twin.
    signature = tuple(sorted((f.name, f.annotation) for f in fields))
    if signature in registry:
        return registry[signature]
    taken = {m.name for m in order}
    canonical = _safe_type_name(base_name)
    if canonical in taken and root_disc and not canonical.startswith(root_disc):
        # a distinct shape wants a taken name → disambiguate by owning-response context
        # (UsersGet + User → UsersGetUser) instead of an opaque numeric suffix (User2)
        alt = _safe_type_name(f"{root_disc}{canonical}")
        if alt not in taken:
            canonical = alt
    name = _unique_model_name(canonical, taken)
    registry[signature] = name
    order.append(ExtractedModel(name=name, fields=fields, source_url=source_url))
    return name


def _safe_type_name(name: str) -> str:
    """Guarantee a valid Python type identifier. Nested model names are built from wire
    field segments (`_pascal(path[-1])`), which can start with a digit ("0_stickers" →
    "0Stickers"); without the old response-root prefix that used to mask it, such a name
    would emit an invalid class/module. Prefix `Field` mirroring `_py_identifier`."""
    if not name or name[0].isdigit():
        return f"Field{name}"
    return name


def _unique_model_name(base: str, taken: set[str]) -> str:
    if base not in taken:
        return base
    i = 2
    while f"{base}{i}" in taken:
        i += 1
    return f"{base}{i}"


def extract_operations(spec: dict[str, Any]) -> list[ExtractedOperation]:
    operations: list[ExtractedOperation] = []
    for path, methods in spec.get("paths", {}).items():
        for http_method, op in methods.items():
            if http_method.upper() not in {"GET", "POST", "PUT", "DELETE", "PATCH"}:
                continue
            operations.append(
                ExtractedOperation(
                    operation_id=op.get("operationId", f"{http_method}_{path}"),
                    domain=_domain_from_tag(op.get("tags", [])),
                    path=path,
                    http_method=http_method.upper(),
                    summary=op.get("summary", ""),
                    description=op.get("description"),
                    params=_extract_params(spec, op),
                    response_schema=_resolve_response_schema(spec, op),
                    source_url=op.get("x-source-url"),
                )
            )
    return operations


def _normalize_path(url: str) -> str:
    """Strip path-placeholder names so `/{category}/params` and `/{categoryName}/params`
    dedup as the same endpoint (the hand-written and spec names for a param often differ)."""
    return re.sub(r"\{[^}]*\}", "{}", url)


def _existing_endpoints() -> set[tuple[str, str]]:
    pairs: set[tuple[str, str]] = set()
    if not METHODS_DIR.exists():
        return pairs
    # Flat layout: generated and hand-written methods share methods/. Skip files carrying
    # the auto-gen marker so we dedup only against CURATED endpoints, never our own output.
    for path in METHODS_DIR.glob("*.py"):
        text = path.read_text(encoding="utf-8")
        if any(marker in text[:200] for marker in GEN_MARKERS_ALL):
            continue
        method: str | None = None
        for line in text.splitlines():
            m1 = re.search(r"__http_method__\s*=\s*HttpMethod\.(\w+)", line)
            if m1:
                method = m1.group(1)
            m2 = re.search(r'__url__\s*=\s*f?"([^"]*)"', line)
            if m2 and method is not None:
                pairs.add((method, _normalize_path(m2.group(1))))
                method = None
    return pairs


def _client_method_names() -> set[str]:
    """Hand-written Client method names — seed the facade name pool so a generated facade
    never shadows a hand-written one (which would violate LSP on the god-class)."""
    client = PKG_ROOT / "client.py"
    if not client.exists():
        return set()
    return set(
        re.findall(r"^\s+(?:async\s+)?def\s+(\w+)\s*\(", client.read_text(encoding="utf-8"), re.M)
    )


def _response_root_name(op: ExtractedOperation) -> str | None:
    if op.response_schema is None:
        return None
    return f"{_pascal(op.operation_id.replace('.', '_'))}Response"


def _sorted_params(op: ExtractedOperation) -> list[ExtractedParam]:
    return sorted(op.params, key=lambda p: (p.location != "path", not p.required))


def _format_docstring(op: ExtractedOperation, indent: str = "    ") -> str:
    lines = [f"Generated by forge — DO NOT EDIT. {op.summary or op.operation_id}."]
    lines.append("Sourced from the official OpenAPI spec (readme.io).")
    if op.description:
        for line in op.description.splitlines():
            if line.strip():
                lines.append(line.strip())

    documented = [p for p in _sorted_params(op) if p.description]
    if documented:
        lines.append("")
        lines.append("Args:")
        for p in documented:
            desc = " ".join(p.description.split()) if p.description else ""
            lines.append(f"    {p.name}: {desc}")

    if op.source_url:
        lines.append("")
        lines.append(f"Docs: {op.source_url}")

    body = f"\n{indent}".join(lines)
    raw = f'"""{body}\n{indent}"""'
    return "\n".join(line.rstrip() for line in raw.splitlines())


def render_method_skeleton(
    op: ExtractedOperation,
    root_type: str | None,
    model_names: list[str],
    unwrap_key: str | None = None,
    api: str = "market",
) -> str:
    class_name = _pascal(op.operation_id.replace(".", "_"))
    # The parent BaseMethod.parse_response applies __returning__: a model's from_raw (or
    # from_raw_many for a list body) for a DTO, or passthrough for a built-in. When unwrap_key
    # is set the method returns a single field's payload directly (`{tags: [Tag]}` → list[Tag]),
    # so __returning__ is the ITEM model and __unwrap__ digs the key before parsing.
    note = ""
    if root_type is None:
        ret, returning = "Any", "passthrough"
        note = "  # response shape not in the spec — body returned as-is"
    elif unwrap_key is not None:
        ret = root_type  # the inner type, e.g. list[Tag] / Tag / int
        m = re.fullmatch(r"list\[(.+)\]", root_type)
        item_type = m.group(1) if m else root_type
        returning = item_type if item_type.split("[", 1)[0] in model_names else "passthrough"
    elif root_type.split("[", 1)[0] in model_names:
        ret, returning = root_type, root_type  # model class or generic alias; base applies from_raw
    else:
        ret, returning = root_type, "passthrough"

    field_lines = []
    for p in _sorted_params(op):
        default = "" if p.required else " = None"
        annotation = p.annotation if p.required else f"{p.annotation} | None"
        wire_comment = f"  # wire: {p.wire_name!r}" if p.wire_name != p.name else ""
        field_lines.append(f"    {p.name}: {annotation}{default}{wire_comment}")

    parts = [
        f'# Source: official OpenAPI spec, operationId "{op.operation_id}".',
        f"class {class_name}(BaseMethod[{ret}]):{note}",
        f"    {_format_docstring(op)}",
        "",
        f"    __http_method__ = HttpMethod.{op.http_method}",
        f'    __url__ = "{op.path}"',
        f"    __returning__ = {returning}",
    ]
    if api == "forum":
        # BaseMethod defaults to ApiTarget.MARKET/RateClass.GENERAL — every generated
        # forum operation must override both, or Client._transport_for silently routes
        # it to the market host (prod-api.lzt.market), where it 404s or, worse, hits an
        # unrelated same-path market endpoint and parses garbage into the forum model.
        parts.insert(4, "    __api__ = ApiTarget.FORUM")
        parts.insert(5, "    __rate_class__ = RateClass.FORUM")
    elif api == "antipublic":
        parts.insert(4, "    __api__ = ApiTarget.ANTIPUBLIC")
        parts.insert(5, "    __rate_class__ = RateClass.ANTIPUBLIC")
    if unwrap_key is not None:
        parts.append(f'    __unwrap__ = "{unwrap_key}"')
    if field_lines:
        parts.append("")
        parts.extend(field_lines)
    return "\n".join(parts) + "\n"


def _model_doc(model: ExtractedModel) -> str:
    lines = ["Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec."]
    if model.source_url:
        lines += ["", f"    Docs: {model.source_url}"]
    described = [(f.name, " ".join(f.description.split())) for f in model.fields if f.description]
    if described:
        lines += ["", "    Attributes:"]
        lines += [f"        {name}: {desc}" for name, desc in described]
    body = "\n".join(lines)
    return f'"""{body}\n    """' if "\n" in body else f'"""{body}"""'


def _pydantic_field_line(f: ExtractedField) -> str:
    annotation = f"{f.annotation} | None" if f.nullable else f.annotation
    if f.alias_path:
        keys = ", ".join(f'"{k}"' for k in f.alias_path)
        default = ", default=None" if f.nullable else ""
        return f"    {f.name}: {annotation} = Field(validation_alias=AliasPath({keys}){default})"
    if f.wire_name != f.name:
        default = ", default=None" if f.nullable else ""
        return f'    {f.name}: {annotation} = Field(alias="{f.wire_name}"{default})'
    if f.nullable:
        return f"    {f.name}: {annotation} = None"
    return f"    {f.name}: {annotation}"


def render_model(model: ExtractedModel, backend: ModelBackend) -> str:
    if backend is ModelBackend.PYDANTIC:
        # Inherit LolzObject (or a hoisted Base<Stem>): it owns from_raw/from_raw_many +
        # populate_by_name, so a model only declares its fields (aliases per differing wire
        # name). A generic family base additionally declares `Generic[...]` over its TypeVars.
        field_lines = [_pydantic_field_line(f) for f in model.fields]
        if model.type_params:
            head = [f"class {model.name}[{', '.join(model.type_params)}]({model.base}):"]
        else:
            head = [f"class {model.name}({model.base}):"]
        parts = [*head, f"    {_model_doc(model)}", ""]
        parts.extend(field_lines)
        return "\n".join(parts) + "\n"

    field_lines = [
        f"    {f.name}: {f.annotation}"
        + (f"  # wire: {f.wire_name!r}" if f.wire_name != f.name else "")
        for f in model.fields
    ]
    kwarg_lines = "\n".join(f'            {f.name}=raw.get("{f.wire_name}"),' for f in model.fields)
    parts = [
        "@dataclass(frozen=True, slots=True)",
        f"class {model.name}:",
        f"    {_model_doc(model)}",
        "",
    ]
    parts.extend(field_lines)
    parts.append("")
    parts.append("    @classmethod")
    parts.append(f"    def from_raw(cls, raw: Mapping[str, Any]) -> {model.name}:")
    parts.append("        return cls(")
    parts.append(kwarg_lines)
    parts.append("        )")
    return "\n".join(parts) + "\n"


def _collect_enums_global(
    ops: list[ExtractedOperation], models: list[ExtractedModel]
) -> list[ExtractedEnum]:
    """Union every enum referenced by request params and model fields across the whole API,
    keyed by name (same-named fields are the same enum; union their members)."""
    merged: dict[str, dict[str, str]] = {}
    order: list[str] = []
    referenced: list[ExtractedEnum] = [p.enum for op in ops for p in op.params if p.enum]
    referenced += [f.enum for m in models for f in m.fields if f.enum]
    for e in referenced:
        if e.name not in merged:
            merged[e.name] = {}
            order.append(e.name)
        for member_id, value in e.members:
            merged[e.name].setdefault(member_id, value)
    return [ExtractedEnum(name=name, members=tuple(merged[name].items())) for name in order]


def _build_api_models(
    spec: dict[str, Any], kept_ops: list[ExtractedOperation]
) -> tuple[dict[str, str | None], dict[str, str], list[ExtractedModel], list[ExtractedEnum]]:
    """Build every response model for the API into one globally-deduped set (identical field
    sets reuse one model). Returns (op -> root type, op -> unwrap key, models, enums). A response
    root that is an object with exactly ONE field is unwrapped: the op returns that field's type
    directly (`{tags: [Tag]}` → `list[Tag]`) and carries the wire key in `op_unwrap` so the
    method digs it out — no pointless one-field wrapper model."""
    registry: dict[tuple[tuple[str, str], ...], str] = {}
    order: list[ExtractedModel] = []
    op_root: dict[str, str | None] = {}
    op_unwrap: dict[str, str] = {}
    for op in sorted(kept_ops, key=lambda o: o.operation_id):
        schema = op.response_schema
        disc = _pascal(op.operation_id.replace(".", "_"))
        if schema is None:
            op_root[op.operation_id] = None
        elif _is_object(schema) and not _is_map_props(schema["properties"]):
            # match _build_model's system_info filter before counting fields
            props = {n: s for n, s in schema["properties"].items() if n != "system_info"}
            if len(props) == 1:
                key = next(iter(props))
                inner, _ = _model_field_type(
                    spec,
                    props[key],
                    _py_identifier(key),
                    "",
                    _pascal(key),
                    registry,
                    order,
                    op.source_url,
                    0,
                    frozenset(),
                    root_disc=disc,
                )
                op_root[op.operation_id] = inner
                op_unwrap[op.operation_id] = key
            else:
                op_root[op.operation_id] = _build_model(
                    spec,
                    _response_root_name(op) or "Response",
                    schema,
                    registry,
                    order,
                    op.source_url,
                    root_disc=disc,
                )
        else:
            # array / scalar / free object -> a built-in type string (list[..], int,
            # dict[str, Any], ...) that `passthrough` returns as-is.
            op_root[op.operation_id] = _schema_type(spec, schema)
    enums = _collect_enums_global(kept_ops, order)
    return op_root, op_unwrap, order, enums


def _name_tokens(name: str) -> list[str]:
    return [t for t in ACRONYM_SAFE_SPLIT.split(name) if t]


def _char_common_prefix(names: list[str]) -> str:
    lo, hi = min(names), max(names)
    i = 0
    while i < len(lo) and lo[i] == hi[i]:
        i += 1
    return lo[:i]


def _common_affix(names: list[str]) -> tuple[str, int, int]:
    """Derive a shared stem from a family of member names by intersecting their PascalCase
    token lists at both ends: [Category|Fortnite|Response] & [Category|Riot|Response] →
    prefix [Category] + suffix [Response] → ('CategoryResponse', 1, 1). Falls back to the
    common character prefix (Item, Item2 → 'Item'). Returns ('', 0, 0) if nothing is shared."""
    toks = [_name_tokens(n) for n in names]
    shortest = min(len(t) for t in toks)
    plen = 0
    while plen < shortest and len({t[plen] for t in toks}) == 1:
        plen += 1
    slen = 0
    while slen < shortest - plen and len({t[-1 - slen] for t in toks}) == 1:
        slen += 1
    stem = "".join(toks[0][:plen] + (toks[0][len(toks[0]) - slen :] if slen else []))
    if not stem:
        stem = _char_common_prefix(names).rstrip("0123456789_")
        return (_safe_type_name(stem), 0, 0) if stem else ("", 0, 0)
    return _safe_type_name(stem), plen, slen


def _discriminator(name: str, plen: int, slen: int) -> str:
    """The middle tokens of a member name once the shared prefix/suffix are stripped —
    the part that makes it unique in its family (CategoryFortniteResponse → 'Fortnite')."""
    toks = _name_tokens(name)
    mid = toks[plen : len(toks) - slen] if slen else toks[plen:]
    return "".join(mid)


def _type_var_name(stem: str, field_name: str) -> str:
    return f"{stem}{_pascal(_singularize(field_name))}T"


def _templatize(annos: list[str]) -> tuple[str, list[str]] | None:
    """For one field's per-member annotations, return (template, [concrete_per_member]) where
    the template carries a single `{T}` slot, or None if constant / not templatable. Supports
    list[X], dict[K, X] (shared K) and bare identifiers."""
    if len(set(annos)) <= 1:
        return None
    lists = [re.fullmatch(r"list\[(.+)\]", a) for a in annos]
    if all(lists):
        return "list[{T}]", [m.group(1) for m in lists]  # type: ignore[union-attr]
    dicts = [re.fullmatch(r"dict\[(.+?),\s*(.+)\]", a) for a in annos]
    if all(dicts) and len({m.group(1) for m in dicts}) == 1:  # type: ignore[union-attr]
        key = dicts[0].group(1)  # type: ignore[union-attr]
        return f"dict[{key}, {{T}}]", [m.group(2) for m in dicts]  # type: ignore[union-attr]
    if all(re.fullmatch(r"[A-Za-z_][\w.]*", a) for a in annos):
        return "{T}", list(annos)
    return None


MIN_BASE_FIELDS = 4  # a shared leading run of ≥ this many identical fields → hoist a Base<Stem>


def _collapse_generics(
    models: list[ExtractedModel],
) -> tuple[dict[str, str], dict[str, str], list[list[str]], list[ExtractedModel]]:
    """Rule 1 — fold a family of models with identical field NAMES that differ only in some
    fields' TYPES into one `Generic[...]` base, and rename each opaque per-member type arg
    (Item6) to `<discriminator><FieldLeaf>` (FortniteItem). Returns (renames, param_rewrites,
    arg_families, models): renames map arg-model names 1:1, param_rewrites map a former
    response model to its parametrized form `Stem[Arg, …]`, and arg_families lists the concrete
    arg-model names per type parameter (a known family Rule 2 hoists a base from)."""
    # Cluster by (field-name shape, first name token, last name token): a family must share
    # its shape AND both name ends, so `Category*Response` collapse together but an unrelated
    # model with the same shape yet a different name doesn't dilute the shared stem.
    by_shape: dict[tuple[Any, ...], list[ExtractedModel]] = {}
    for m in models:
        toks = _name_tokens(m.name)
        key = (tuple(f.name for f in m.fields), toks[0] if toks else "", toks[-1] if toks else "")
        by_shape.setdefault(key, []).append(m)
    taken = {m.name for m in models}
    renames: dict[str, str] = {}
    param_rewrites: dict[str, str] = {}
    arg_families: list[list[str]] = []
    generics: list[ExtractedModel] = []
    consumed: set[str] = set()
    for group in by_shape.values():
        if len(group) < 2:
            continue
        templates: dict[int, tuple[str, list[str]]] = {}
        ok = True
        for i in range(len(group[0].fields)):
            annos = [g.fields[i].annotation for g in group]
            t = _templatize(annos)
            if t is None and len(set(annos)) != 1:
                ok = False  # a field varies but isn't templatable → not a clean generic
                break
            if t is not None:
                templates[i] = t
        if not ok or not templates:
            continue
        stem, plen, slen = _common_affix([g.name for g in group])
        if plen < 1 or slen < 1:
            continue  # require a shared prefix AND suffix → a meaningful stem (CategoryResponse)
        stem = _unique_model_name(stem, taken)
        taken.add(stem)
        tvs = {i: _type_var_name(stem, group[0].fields[i].name) for i in sorted(templates)}
        base_fields = [
            replace(f, annotation=templates[i][0].format(T=tvs[i]), enum=None)
            if i in templates
            else f
            for i, f in enumerate(group[0].fields)
        ]
        generics.append(
            ExtractedModel(
                name=stem,
                fields=base_fields,
                # Not group[0].source_url: this generic base is shared by every member's
                # own endpoint, not just whichever happened to be first — a single
                # "Docs:" link would misleadingly claim one member's page as canonical.
                source_url=None,
                type_params=tuple(tvs[i] for i in sorted(tvs)),
            )
        )
        param_args: dict[int, list[str]] = {i: [] for i in sorted(templates)}
        for gi, g in enumerate(group):
            disc = _discriminator(g.name, plen, slen)
            args: list[str] = []
            for i in sorted(templates):
                concrete = templates[i][1][gi]
                if concrete in taken and disc:  # a model arg → give it a meaningful name
                    leaf = _pascal(_singularize(group[0].fields[i].name))
                    new = _unique_model_name(f"{disc}{leaf}", taken)
                    taken.add(new)
                    renames[concrete] = new
                    args.append(new)
                    param_args[i].append(new)
                else:
                    args.append(concrete)
            param_rewrites[g.name] = f"{stem}[{', '.join(args)}]"
            consumed.add(g.name)
        arg_families.extend(fam for fam in param_args.values() if len(fam) >= 2)
    survivors = [m for m in models if m.name not in consumed]
    return renames, param_rewrites, arg_families, survivors + generics


def _common_prefix_len(a: list[ExtractedField], b: list[ExtractedField]) -> int:
    n = 0
    for fa, fb in zip(a, b, strict=False):  # prefixes of differing-length field lists
        if fa.name == fb.name and fa.annotation == fb.annotation:
            n += 1
        else:
            break
    return n


def _extract_bases(families: list[list[str]], models: list[ExtractedModel]) -> list[ExtractedModel]:
    """Rule 2 — for each KNOWN family of generic type-arg models (the FortniteItem/BattleNetItem
    that parametrise one CategoryResponse[T]), hoist their shared leading run of identical fields
    into a synthesized `Base<Stem>` (BaseItem) and reduce each member to a subclass carrying only
    its own tail fields. Families come from Rule 1, so grouping is exact — no prefix guessing."""
    by_name = {m.name: m for m in models}
    taken = {m.name for m in models}
    reduce_map: dict[str, tuple[str, int]] = {}  # member name -> (base name, shared prefix length)
    bases: list[ExtractedModel] = []
    for fam in families:
        members = [
            by_name[n]
            for n in fam
            if n in by_name
            and n not in reduce_map
            and not by_name[n].type_params
            and by_name[n].base == "LolzObject"
        ]
        if len(members) < 2:
            continue
        prefix_len = min(_common_prefix_len(members[0].fields, m.fields) for m in members[1:])
        prefix_len = min(prefix_len, *(len(m.fields) for m in members))
        if prefix_len < MIN_BASE_FIELDS:
            continue
        stem, _, _ = _common_affix([m.name for m in members])
        base_name = _unique_model_name(f"Base{stem or 'Item'}", taken)
        taken.add(base_name)
        bases.append(
            ExtractedModel(
                name=base_name,
                fields=list(members[0].fields[:prefix_len]),
                # Not members[0].source_url: this base is shared by every member's own
                # endpoint (BaseItem underlies ~21 category items), not just whichever
                # happened to be first — a single "Docs:" link would misleadingly claim
                # one member's page as canonical (confirmed: BaseItem's docstring pointed
                # at /categorybattlenet, the first family member processed).
                source_url=None,
            )
        )
        for m in members:
            reduce_map[m.name] = (base_name, prefix_len)
    result = [
        replace(m, fields=list(m.fields[reduce_map[m.name][1] :]), base=reduce_map[m.name][0])
        if m.name in reduce_map
        else m
        for m in models
    ]
    return result + bases


def _apply_rewrites(
    subs: dict[str, str], op_root: dict[str, str | None], models: list[ExtractedModel]
) -> tuple[dict[str, str | None], list[ExtractedModel]]:
    """Rewrite every reference to a renamed model — field annotations and op return types —
    as whole-identifier substitutions."""
    if not subs:
        return op_root, models
    pattern = re.compile(r"\b(" + "|".join(re.escape(k) for k in subs) + r")\b")

    def rw(s: str) -> str:
        return pattern.sub(lambda mo: subs[mo.group(0)], s)

    models = [
        replace(m, fields=[replace(f, annotation=rw(f.annotation)) for f in m.fields])
        for m in models
    ]
    op_root = {k: (rw(v) if v else v) for k, v in op_root.items()}
    return op_root, models


def _rebase_status_responses(models: list[ExtractedModel]) -> list[ExtractedModel]:
    """A response model whose leading field is `status: str` reports the API's own
    ok/error sentinel — rebase it onto the hand-written `BaseResponse` (which owns
    `is_ok()`) and drop the now-inherited field, instead of every model re-declaring it."""
    out = []
    for m in models:
        f0 = m.fields[0] if m.fields else None
        if (
            m.base == "LolzObject"
            and f0 is not None
            and f0.name == "status"
            and f0.annotation == "str"
            and f0.wire_name == "status"
            and f0.alias_path is None
        ):
            m = replace(m, base="BaseResponse", fields=m.fields[1:])
        out.append(m)
    return out


def _collapse_models(
    op_root: dict[str, str | None], models: list[ExtractedModel], api: str
) -> tuple[dict[str, str | None], list[ExtractedModel]]:
    """Post-build model normalisation: generic families (Rule 1), shared-prefix base classes
    (Rule 2), then neutral names for response shapes shared by ≥2 operations — every reference
    (op return types + field annotations) rewritten at each step."""
    renames, param_rewrites, arg_families, models = _collapse_generics(models)
    models = [replace(m, name=renames.get(m.name, m.name)) for m in models]
    models = _extract_bases(arg_families, models)
    op_root, models = _apply_rewrites({**renames, **param_rewrites}, op_root, models)

    # A response body shared by ≥2 operations (the ubiquitous {status, message} OK-body) must
    # not be named after whichever operation happened to build it first (ImapDelete returning
    # AutoPaymentsDeleteResponse). Give it a neutral name derived from its own field names —
    # and if several such shapes share field NAMES but differ by a field TYPE, fold them into
    # one generic (StatusItemResponse[T]) instead of a numbered twin.
    op_counts: dict[str, int] = {}
    for v in op_root.values():
        if v:
            op_counts[v.split("[", 1)[0]] = op_counts.get(v.split("[", 1)[0], 0) + 1
    groups: dict[tuple[str, ...], list[ExtractedModel]] = {}
    for m in models:
        if op_counts.get(m.name, 0) >= 2 and not m.type_params and 1 <= len(m.fields) <= 5:
            groups.setdefault(tuple(f.name for f in m.fields), []).append(m)

    taken = {m.name for m in models}
    renames2: dict[str, str] = {}
    params2: dict[str, str] = {}
    generics2: list[ExtractedModel] = []
    dropped: set[str] = set()
    for fnames, group in groups.items():
        # API-qualify the neutral name: generate_all runs once per API, so this pass can't
        # see the other namespace's models. A field-derived name is API-agnostic by
        # construction, so the same shape ({status, message}) yields the same bare name in
        # two namespaces — a collision only visible downstream where a registry keys models
        # by bare __name__ (lzt-mcp catalog). Prefixing with the API keeps it globally unique.
        base = _unique_model_name(
            _safe_type_name(_pascal(api) + "".join(_pascal(n) for n in fnames) + "Response"),
            taken,
        )
        taken.add(base)
        templates = {
            i: t
            for i in range(len(fnames))
            if (t := _templatize([g.fields[i].annotation for g in group])) is not None
        }
        untemplatable = any(
            i not in templates and len({g.fields[i].annotation for g in group}) != 1
            for i in range(len(fnames))
        )
        if len(group) < 2 or untemplatable or not templates:
            renames2[group[0].name] = base  # single shape (or not cleanly generic) → neutral name
            continue
        tvs = {i: _type_var_name(base, fnames[i]) for i in sorted(templates)}
        generics2.append(
            ExtractedModel(
                name=base,
                # Not group[0].source_url — this shape is shared by ≥2 operations by
                # construction (see op_counts filter above), so no single member's page
                # is the canonical source.
                source_url=None,
                type_params=tuple(tvs[i] for i in sorted(tvs)),
                fields=[
                    replace(f, annotation=templates[i][0].format(T=tvs[i]), enum=None)
                    if i in templates
                    else f
                    for i, f in enumerate(group[0].fields)
                ],
            )
        )
        for gi, g in enumerate(group):
            args = ", ".join(templates[i][1][gi] for i in sorted(templates))
            params2[g.name] = f"{base}[{args}]"
            dropped.add(g.name)
    models = [m for m in models if m.name not in dropped] + generics2
    models = [replace(m, name=renames2.get(m.name, m.name)) for m in models]
    op_root, models = _apply_rewrites({**renames2, **params2}, op_root, models)
    return op_root, models


PKG_ROOT = REPO_ROOT / "src" / "pylzt"

# Enums already hand-defined in pylzt.types are reused (imported), never regenerated —
# their open-ended .parse() fallback absorbs any spec values beyond the curated members.
EXISTING_TYPES_ENUMS = frozenset(
    {
        "Category",
        "ItemOrigin",
        "Currency",
        "OrderBy",
        "RateClass",
        "ApiTarget",
        "HttpMethod",
        "ProxyScheme",
        "ProxyOutcome",
        "Tristate",
    }
)


def _gen_path(area: str, filename: str) -> Path:
    """Resolve a flat target inside the STAGING tree `dev/codegen/generated/<area>/`.
    `generate` writes here and never touches the library; the separate `install` step
    promotes these files flat into `src/pylzt/<area>/` behind the ruff+mypy gate. The
    emitted files carry the module's final flat import paths (`pylzt.<area>.<name>`)."""
    target = STAGING_ROOT / area / filename
    target.parent.mkdir(parents=True, exist_ok=True)
    return target


_GEN_HEAD = (
    '"""Generated by forge — DO NOT EDIT.\n'
    "Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`\n"
    "to update.\n"
    '"""'
)


def _strip_docs(body: str) -> str:
    """Drop docstrings and comments so import detection scans code, not prose (an enum
    named Email must not be imported just because a docstring says "email")."""
    body = re.sub(r'"""(?:.|\n)*?"""', "", body)
    return re.sub(r"#[^\n]*", "", body)


def _imports_used(code: str, names: list[str], module: str) -> str | None:
    used = sorted({n for n in names if re.search(rf"\b{re.escape(n)}\b", code)})
    return f"from {module} import {', '.join(used)}" if used else None


def _lib_enum_module(body: str) -> str:
    head = f"{_GEN_HEAD}\n\nfrom __future__ import annotations\n\nfrom enum import StrEnum\n\n\n"
    return f"{head}{body}\n"


def _lib_model_file(
    api: str,
    model: ExtractedModel,
    backend: ModelBackend,
    reused: list[str],
    new_enums: list[str],
    model_names: list[str],
) -> str:
    """One model per file: `models/<api>/<snake>.py`. Sibling models referenced in this
    model's field annotations are real imports (the model graph is a DAG — nested-then-
    parent, deduped, cycles degraded to dict — so transitive imports resolve). Import order
    is normalised by ruff --fix during install, so grouping here is loose."""
    body = render_model(model, backend)
    code = _strip_docs(body)
    imports = ["from __future__ import annotations", ""]
    if re.search(r"\bAny\b", code):
        imports.append("from typing import Any")
    if backend is ModelBackend.DATACLASS:
        imports.append("from dataclasses import dataclass")
        if re.search(r"\bMapping\b", code):
            imports.append("from collections.abc import Mapping")
    else:
        base_imports = [n for n in ("LolzObject", "BaseResponse") if n in code]
        if base_imports:
            imports.append(f"from pylzt.models.base import {', '.join(base_imports)}")
        pyd = [n for n in ("Field", "AliasPath") if f"{n}(" in code]
        if pyd:
            imports.append(f"from pydantic import {', '.join(pyd)}")
    for sib in sorted(
        n for n in model_names if n != model.name and re.search(rf"\b{re.escape(n)}\b", code)
    ):
        imports.append(f"from pylzt.models.{api}.{_snake(sib)} import {sib}")
    for imp in (
        _imports_used(code, reused, "pylzt.types"),
        _imports_used(code, new_enums, f"pylzt.enums.{api}"),
    ):
        if imp:
            imports.append(imp)
    return f"{_GEN_HEAD}\n\n" + "\n".join(imports) + f"\n\n\n{body}"


# The response roots that shipped UNPREFIXED in the published library, per API. An explicit list,
# not a pattern: a rule like "alias every prefixed Response" also aliases models this generator has
# only just invented, which no caller can be importing — and for `StatusMessageResponse` that would
# hand the same bare name to two namespaces, the very ambiguity the prefix exists to prevent. This
# list is the compatibility surface and nothing else; it only ever shrinks, and empties at the next
# major.
_SHIPPED_UNPREFIXED: Final[dict[str, tuple[str, ...]]] = {
    "market": (
        "EmailLettersResponse",
        "ItemCodeDataResponse",
        "QueryDataAppIdResponse",
        "StatusItemResponse",
    ),
    "forum": ("DataDataTotalLinksResponse",),
}


def _compat_aliases(api: str, ordered: list[ExtractedModel]) -> list[tuple[str, str]]:
    """`(old_name, current_name)` for every response root this generator API-qualifies.

    The qualification is deliberate (see the API-prefix comment in `_normalize_models`): a
    field-derived name like `StatusItemResponse` is API-agnostic by construction, so market and
    forum both produce it and a downstream registry keyed by bare `__name__` collides. But the
    published library shipped the UNPREFIXED names, so regenerating renames five public types out
    from under anyone importing them.

    Emitting the old name as an alias keeps both: the registry gets globally unique class names,
    and existing imports keep resolving. Emitted from the generator rather than hand-written into
    the package, because `models/<api>/__init__.py` is generated — a hand-added alias there would
    be erased by the next run, which is exactly when it is still needed.
    """
    cap = _pascal(api)
    taken = {m.name for m in ordered}
    aliases = []
    for bare in _SHIPPED_UNPREFIXED.get(api, ()):
        qualified = f"{cap}{bare}"
        # Never shadow a model that genuinely owns the bare name, and never alias a name this run
        # did not actually produce.
        if qualified in taken and bare not in taken:
            aliases.append((bare, qualified))
    return aliases


def _model_init(api: str, models: list[ExtractedModel]) -> str:
    """The `models/<api>/__init__.py` that re-exports every generated model so callers keep
    importing `from pylzt.models.<api> import X`."""
    ordered = sorted(models, key=lambda m: m.name)
    aliases = _compat_aliases(api, ordered)
    lines = [_GEN_HEAD, ""]
    lines += [f"from pylzt.models.{api}.{_snake(m.name)} import {m.name}" for m in ordered]
    if aliases:
        lines += [
            "",
            "# Backward-compatible aliases: these names shipped unprefixed before the response",
            "# roots were API-qualified. Deprecated — prefer the qualified name; removable in the",
            "# next major, once no caller imports the bare form.",
        ]
        lines += [f"{old} = {new}" for old, new in aliases]
    lines += ["", "__all__ = ["]
    lines += [f'    "{name}",' for name in sorted([m.name for m in ordered] + [a for a, _ in aliases])]
    lines += ["]"]
    return "\n".join(lines) + "\n"


def _lib_method_module(
    api: str, body: str, model_names: list[str], reused: list[str], new_enums: list[str]
) -> str:
    code = _strip_docs(body)
    imports = ["from __future__ import annotations"]
    if re.search(r"\bAny\b", code):
        imports.append("from typing import Any")
    base_names = ["BaseMethod"]
    if re.search(r"\bpassthrough\b", code):
        base_names.append("passthrough")
    imports += ["", f"from pylzt.methods.base import {', '.join(base_names)}"]
    if "def parse_response" in code:
        imports.append("from pylzt.transport.base import Response")
    locals_ = [
        imp
        for imp in (
            _imports_used(code, ["Media"], "pylzt.media"),
            _imports_used(code, model_names, f"pylzt.models.{api}"),
            # HttpMethod/ApiTarget/RateClass live in pylzt.types (methods.base doesn't
            # re-export them under strict) — ApiTarget/RateClass only referenced by forum
            # method bodies (__api__/__rate_class__ overrides), _imports_used drops unused ones.
            _imports_used(
                code, ["HttpMethod", "ApiTarget", "RateClass", *reused], "pylzt.types"
            ),
            _imports_used(code, new_enums, f"pylzt.enums.{api}"),
        )
        if imp
    ]
    if locals_:
        imports += ["", *locals_]
    return f"{_GEN_HEAD}\n\n" + "\n".join(imports) + f"\n\n\n{body}"


def _facade_name(op: ExtractedOperation, taken: set[str]) -> str:
    base = _snake(op.operation_id.replace(".", "_")) or "call"
    name, i = base, 2
    while name in taken:
        name, i = f"{base}_{i}", i + 1
    taken.add(name)
    return name


# The one name added to every generated signature. Checked against all three specs: it collides
# with none of the 629 distinct parameter names they declare, while `cookies` (2 endpoints) and
# `extra` (3) are already taken — which is why the overrides travel as ONE bundle rather than as
# separate `headers=`/`cookies=`/`timeout=` arguments.
_OPTIONS_PARAM: Final = "request_options"


def render_facade_method(
    op: ExtractedOperation, class_name: str, root_name: str | None, facade_name: str
) -> str:
    params = _sorted_params(op)
    sig = ["self"]
    for p in params:
        ann = p.annotation if p.required else f"{p.annotation} | None"
        sig.append(f"{p.name}: {ann}" + ("" if p.required else " = None"))
    ret = root_name or "Any"
    args = ", ".join(f"{p.name}={p.name}" for p in params)
    # Keyword-only and last, so no existing positional call shifts.
    sig += ["*", f"{_OPTIONS_PARAM}: RequestOptions | None = None"]
    return (
        f"    async def {facade_name}({', '.join(sig)}) -> {ret}:\n"
        f"        {_format_docstring(op, indent='        ')}\n"
        f"        return await self({class_name}({args}), "
        f"{_OPTIONS_PARAM}={_OPTIONS_PARAM})"
    )


def render_sync_facade_method(
    op: ExtractedOperation, root_name: str | None, facade_name: str
) -> str:
    """Sync counterpart of `render_facade_method` — same signature, a blocking `def`
    body running the already-rendered async facade method through `SyncRunner`
    instead of re-parsing the spec (reuses `_sorted_params`/`_format_docstring`, the
    only two spec-derived shapes a call site needs)."""
    params = _sorted_params(op)
    sig = ["self"]
    for p in params:
        ann = p.annotation if p.required else f"{p.annotation} | None"
        sig.append(f"{p.name}: {ann}" + ("" if p.required else " = None"))
    ret = root_name or "Any"
    args = ", ".join(f"{p.name}={p.name}" for p in params)
    sig += ["*", f"{_OPTIONS_PARAM}: RequestOptions | None = None"]
    forwarded = f"{_OPTIONS_PARAM}={_OPTIONS_PARAM}"
    call_args = f"{args}, {forwarded}" if args else forwarded
    return (
        f"    def {facade_name}({', '.join(sig)}) -> {ret}:\n"
        f"        {_format_docstring(op, indent='        ')}\n"
        f"        return self._runner.run(self._async.{facade_name}({call_args}))"
    )


def _render_sync_facade_module(
    api: str,
    body: str,
    model_names: list[str],
    reused: list[str],
    new_enums: list[str],
) -> str:
    """Parallel sync facade — a thin blocking wrapper around `Generated{Cap}Facade`,
    not a second spec-derived implementation (no separate `__call__`/method-as-class
    path; every method just runs the async one through a `SyncRunner`)."""
    cap = api.capitalize()
    code = _strip_docs(body)
    imports = [
        "from __future__ import annotations",
        "",
        "from typing import TYPE_CHECKING, Any",
        "",
        f"from pylzt.facades.{api} import Generated{cap}Facade",
    ]
    for imp in (
        _imports_used(code, ["Media"], "pylzt.media"),
        _imports_used(code, model_names, f"pylzt.models.{api}"),
        _imports_used(code, reused, "pylzt.types"),
        _imports_used(code, new_enums, f"pylzt.enums.{api}"),
    ):
        if imp:
            imports.append(imp)
    imports.append("from pylzt.transport.base import RequestOptions")
    imports += ["", "if TYPE_CHECKING:", "    from pylzt.sync.runner import SyncRunner"]
    cls = [
        f"class SyncGenerated{cap}Facade:",
        f'    """Generated by forge — DO NOT EDIT. Blocking facade for the {api} API — '
        f"each method runs `Generated{cap}Facade`'s async counterpart through a "
        '`SyncRunner`, no separate spec-derived implementation."""',
        "",
        f"    def __init__(self, async_facade: Generated{cap}Facade, runner: SyncRunner) -> None:",
        "        self._async = async_facade",
        "        self._runner = runner",
        "",
        body,
    ]
    return f"{_GEN_HEAD}\n\n" + "\n".join(imports) + "\n\n\n" + "\n".join(cls) + "\n"


def _render_facade_module(
    api: str,
    body: str,
    method_imports: list[str],
    model_names: list[str],
    reused: list[str],
    new_enums: list[str],
) -> str:
    cap = api.capitalize()
    code = _strip_docs(body)
    imports = ["from __future__ import annotations", "", "from typing import TYPE_CHECKING, Any"]
    imports += ["", *sorted(set(method_imports))]
    for imp in (
        _imports_used(code, ["Media"], "pylzt.media"),
        _imports_used(code, model_names, f"pylzt.models.{api}"),
        _imports_used(code, reused, "pylzt.types"),
        _imports_used(code, new_enums, f"pylzt.enums.{api}"),
    ):
        if imp:
            imports.append(imp)
    # A real import, not a TYPE_CHECKING one: every generated signature carries it as a runtime
    # default annotation, and the module is `from __future__ import annotations` so it would still
    # type-check — but a caller doing `from pylzt.facades.market import RequestOptions` (the
    # obvious place to look for it) must find something.
    imports.append("from pylzt.transport.base import RequestOptions")
    imports += ["", "if TYPE_CHECKING:", "    from pylzt.methods.base import BaseMethod"]
    cls = [
        f"class Generated{cap}Facade:",
        f'    """Generated by forge — DO NOT EDIT. Async facade for the {api} API."""',
        "",
        "    if TYPE_CHECKING:",
        # Must mirror _Namespace.__call__ exactly: this stub is the only thing a type checker sees
        # for the delegation every generated method body performs, and the real __call__ lives on
        # the namespace that mixes this class in.
        "        async def __call__[T](",
        "            self, method: BaseMethod[T], *, "
        f"{_OPTIONS_PARAM}: RequestOptions | None = None",
        "        ) -> T: ...",
        "",
        body,
    ]
    return f"{_GEN_HEAD}\n\n" + "\n".join(imports) + "\n\n\n" + "\n".join(cls) + "\n"


def generate_all(spec: dict[str, Any], api: str, backend: ModelBackend) -> None:
    operations = extract_operations(spec)
    existing = _existing_endpoints()
    kept = [op for op in operations if (op.http_method, _normalize_path(op.path)) not in existing]

    op_root, op_unwrap, models, enums = _build_api_models(spec, kept)
    if backend is ModelBackend.PYDANTIC:
        op_root, models = _collapse_models(op_root, models, api)
        models = _rebase_status_responses(models)
    model_names = [m.name for m in models]
    reused = sorted({e.name for e in enums if e.name in EXISTING_TYPES_ENUMS})
    new_enums = [e for e in enums if e.name not in EXISTING_TYPES_ENUMS]
    new_enum_names = [e.name for e in new_enums]

    if new_enums:
        enum_body = "\n\n".join(render_enum(e) for e in new_enums)
        _gen_path("enums", f"{api}.py").write_text(_lib_enum_module(enum_body), encoding="utf-8")

    for m in models:
        _gen_path("models", f"{api}/{_snake(m.name)}.py").write_text(
            _lib_model_file(api, m, backend, reused, new_enum_names, model_names), encoding="utf-8"
        )
    _gen_path("models", f"{api}/__init__.py").write_text(_model_init(api, models), encoding="utf-8")

    by_domain: dict[str, list[ExtractedOperation]] = {}
    for op in kept:
        by_domain.setdefault(op.domain, []).append(op)

    facade_methods: list[str] = []
    sync_facade_methods: list[str] = []
    facade_imports: list[str] = []
    taken: set[str] = _client_method_names()  # never shadow a hand-written Client method
    for domain, ops in sorted(by_domain.items()):
        ops = sorted(ops, key=lambda o: o.operation_id)
        body = "\n\n".join(
            render_method_skeleton(
                op, op_root[op.operation_id], model_names, op_unwrap.get(op.operation_id), api
            )
            for op in ops
        )
        _gen_path("methods", f"{api}_{domain}.py").write_text(
            _lib_method_module(api, body, model_names, reused, new_enum_names), encoding="utf-8"
        )
        for op in ops:
            cls = _pascal(op.operation_id.replace(".", "_"))
            facade_name = _facade_name(op, taken)
            root_name = op_root[op.operation_id]
            facade_methods.append(render_facade_method(op, cls, root_name, facade_name))
            sync_facade_methods.append(render_sync_facade_method(op, root_name, facade_name))
            facade_imports.append(f"from pylzt.methods.{api}_{domain} import {cls}")
        print(f"staged methods/{api}_{domain}.py ({len(ops)} methods)")

    facade_body = "\n\n".join(facade_methods)
    _gen_path("facades", f"{api}.py").write_text(
        _render_facade_module(
            api, facade_body, facade_imports, model_names, reused, new_enum_names
        ),
        encoding="utf-8",
    )
    sync_facade_body = "\n\n".join(sync_facade_methods)
    _gen_path("facades", f"sync_{api}.py").write_text(
        _render_sync_facade_module(api, sync_facade_body, model_names, reused, new_enum_names),
        encoding="utf-8",
    )
    print(
        f"staged models/{api}.py ({len(models)}) + facades/{api}.py "
        f"({len(kept)} facades) + {len(new_enums)} new enums; "
        f"skipped {len(operations) - len(kept)} existing"
    )


def extract_enums(spec: dict[str, Any]) -> list[ExtractedEnum]:
    enums: list[ExtractedEnum] = []
    seen: set[str] = set()
    for schema_name, schema in spec.get("components", {}).get("schemas", {}).items():
        _collect_enums(schema_name, schema, enums, seen)
    for param_name, param in spec.get("components", {}).get("parameters", {}).items():
        schema = param.get("schema", {})
        _collect_enums(_pascal(param_name), schema, enums, seen)
    return enums


def _collect_enums(
    name: str, schema: dict[str, Any], enums: list[ExtractedEnum], seen: set[str]
) -> None:
    values = schema.get("enum")
    if values and all(isinstance(v, str) for v in values) and name not in seen:
        seen.add(name)
        members = tuple((_enum_member_id(v), v) for v in values)
        enums.append(ExtractedEnum(name=name, members=members))
    for prop_name, prop_schema in schema.get("properties", {}).items():
        if isinstance(prop_schema, dict):
            _collect_enums(_pascal(prop_name), prop_schema, enums, seen)


def render_enum(e: ExtractedEnum) -> str:
    member_lines = "\n".join(f"    {member} = {json.dumps(value)}" for member, value in e.members)
    return f'''class {e.name}(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

{member_lines}
'''


def generate_enums(spec: dict[str, Any], api: str) -> None:
    enums = extract_enums(spec)
    out_file = GENERATED_DIR / f"{api}_openapi_enums.py"
    blocks = [
        f'"""Generated by forge — DO NOT EDIT. Draft enums for {api}, extracted by',
        "`dev.codegen.generator --enums` from the official readme.io OpenAPI spec — review",
        'each before moving it into src/pylzt/types.py."""',
        "",
        "from __future__ import annotations",
        "",
        "from enum import StrEnum",
        "",
    ]
    blocks.extend(render_enum(e) for e in enums)
    out_file.write_text("\n\n".join(blocks), encoding="utf-8")
    print(f"wrote {out_file} ({len(enums)} enums)")


def _param_sig(p: ExtractedParam) -> str:
    return f"{p.name}:{p.annotation}" if p.required else f"{p.name}:{p.annotation}?"


def _md_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def generate_docs(spec: dict[str, Any]) -> str:
    """Render a compressed Markdown reference: per-domain method tables + typed models + enums."""
    operations = extract_operations(spec)
    op_root, _op_unwrap, models, enums = _build_api_models(spec, operations)
    info = spec.get("info", {})
    title = info.get("title", "lzt API")
    version = info.get("version", "?")

    by_domain: dict[str, list[ExtractedOperation]] = {}
    for op in operations:
        by_domain.setdefault(op.domain, []).append(op)

    lines = [
        f"# {title} — generated reference",
        "",
        f"Spec version `{version}`. Auto-rendered by `dev.codegen.generator --docs` — "
        f"{len(operations)} methods, {len(models)} models, {len(enums)} enums "
        f"across {len(by_domain)} domains.",
        "",
    ]

    for domain, ops in sorted(by_domain.items()):
        ops = sorted(ops, key=lambda o: o.operation_id)
        lines.append(f"## {domain}")
        lines.append("")
        lines.append("| Op | HTTP | Path | Params | Returns |")
        lines.append("|----|------|------|--------|---------|")
        for op in ops:
            params = ", ".join(_param_sig(p) for p in _sorted_params(op)) or "—"
            returns = op_root.get(op.operation_id) or "—"
            oid = op.operation_id
            op_cell = f"[`{oid}`]({op.source_url})" if op.source_url else f"`{oid}`"
            lines.append(
                f"| {op_cell} | {op.http_method} | `{op.path}` | {_md_cell(params)} | {returns} |"
            )
        lines.append("")

    if models:
        lines.append("## Models")
        lines.append("")
        for m in models:
            fields = ", ".join(f"{f.name}:{f.annotation}" for f in m.fields)
            lines.append(f"- `{m.name}` — {_md_cell(fields)}")
        lines.append("")

    if enums:
        lines.append("## Enums")
        lines.append("")
        for e in enums:
            members = ", ".join(v for _, v in e.members)
            lines.append(f"- `{e.name}` — {_md_cell(members)}")
        lines.append("")

    return "\n".join(lines)


def generate_docs_file(spec: dict[str, Any], api: str) -> None:
    out_file = GENERATED_DIR / "docs" / f"{api}.md"
    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text(generate_docs(spec), encoding="utf-8")
    n = len(extract_operations(spec))
    print(f"wrote {out_file} ({n} methods documented)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", type=Path, required=True)
    parser.add_argument("--api", choices=["market", "forum", "antipublic"], required=True)
    parser.add_argument(
        "--model-backend",
        choices=[b.value for b in ModelBackend],
        default=ModelBackend.PYDANTIC.value,
        help="Response-DTO target (default: pydantic). Method skeletons stay frozen dataclasses.",
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--all", action="store_true")
    mode.add_argument("--enums", action="store_true")
    mode.add_argument("--docs", action="store_true")
    args = parser.parse_args()

    spec = _load_spec(args.spec)
    if args.all:
        generate_all(spec, args.api, ModelBackend(args.model_backend))
    elif args.enums:
        generate_enums(spec, args.api)
    else:
        generate_docs_file(spec, args.api)


if __name__ == "__main__":
    main()
