"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pydantic import Field

from pylzt.models.base import LolzObject


class BalanceCustomFields(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/paymentsbalanceexchange
    """

    field_4: str = Field(alias="_4")
    allowSelfUnban: list[str]
    ban_reason: str
    discord: str
    github: str
    jabber: str
    lztAwardUserTrophy: str
    lztLikesIncreasing: str
    lztLikesZeroing: str
    lztSympathyIncreasing: str
    lztSympathyZeroing: str
    lztUnbanAmount: str
    maecenasValue: str
    scamURL: str
    steam: str
    telegram: str
    vk: str
    favoritePorn: str
    favoriteVape: str
    favoriteAnime: str
    matrix: str
