"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.rendered_avatars import RenderedAvatars
from pylzt.models.market.rendered_backgrounds import RenderedBackgrounds


class BalanceRendered(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/paymentsbalanceexchange
    """

    username: str
    avatars: RenderedAvatars
    backgrounds: RenderedBackgrounds
    link: str
