"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.item_bump_settings import ItemBumpSettings
from pylzt.models.market.item_seller import ItemSeller


class CartGetItem(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/cartget
    """

    item_id: int | None = None
    item_state: str | None = None
    category_id: int | None = None
    published_date: int | None = None
    title: str | None = None
    description: str | None = None
    price: int | None = None
    update_stat_date: int | None = None
    refreshed_date: int | None = None
    view_count: int | None = None
    is_sticky: int | None = None
    item_origin: str | None = None
    extended_guarantee: int | None = None
    nsb: int | None = None
    allow_ask_discount: int | None = None
    title_en: str | None = None
    description_en: str | None = None
    item_domain: str | None = None
    resale_item_origin: str | None = None
    isIgnored: int | None = None
    guarantee: bool | None = None
    canViewLoginData: bool | None = None
    canUpdateItemStats: bool | None = None
    canViewEmailLoginData: bool | None = None
    showGetEmailCodeButton: bool | None = None
    canOpenItem: bool | None = None
    canCloseItem: bool | None = None
    canEditItem: bool | None = None
    canDeleteItem: bool | None = None
    canStickItem: bool | None = None
    canUnstickItem: bool | None = None
    bumpSettings: ItemBumpSettings | None = None
    canBumpItem: bool | None = None
    canBuyItem: bool | None = None
    rub_price: int | None = None
    price_currency: str | None = None
    canValidateAccount: bool | None = None
    canResellItemAfterPurchase: bool | None = None
    canViewAccountLink: bool | None = None
    itemOriginPhrase: str | None = None
    tags: list[str] | None = None
    note_text: str | None = None
    description_html: str | None = None
    description_html_en: str | None = None
    seller: ItemSeller | None = None
