"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject


class CategoryItemSeller[CategoryItemSellerRestorePercentT](LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec."""

    user_id: int
    sold_items_count: int
    active_items_count: int
    restore_data: str
    username: str
    avatar_date: int
    is_banned: int
    display_style_group_id: int
    restore_percents: CategoryItemSellerRestorePercentT
