"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pydantic import AliasPath, Field

from pylzt.models.base import LolzObject
from pylzt.models.market.item_account_link import ItemAccountLink
from pylzt.models.market.item_category import ItemCategory
from pylzt.models.market.item_onlyfans_subscription import ItemOnlyfansSubscription
from pylzt.models.market.item_onlyfans_transaction import ItemOnlyfansTransaction
from pylzt.models.market.item_seller import ItemSeller


class CategoryOnlyfansItem(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/categoryonlyfans
    """

    item_id: int
    item_state: str
    category_id: int
    published_date: int
    title: str
    description: str
    price: int
    update_stat_date: int
    refreshed_date: int
    edit_date: int
    pending_deletion_date: int
    view_count: int
    is_sticky: int
    item_origin: str
    extended_guarantee: int
    nsb: int
    allow_ask_discount: int
    title_en: str
    description_en: str
    email_type: str
    email_provider: str
    item_domain: str
    resale_item_origin: str
    auto_bump_period: int
    guarantee_duration: int
    rub_price: int
    discount: str
    onlyfans_item_id: int
    onlyfans_id: str
    onlyfans_register_date: int
    onlyfans_balance: str
    onlyfans_converted_balance: int
    onlyfans_subscribers_count: int
    onlyfans_posts_count: int
    onlyfans_active_subs_count: int
    onlyfans_kyc_verified: int
    onlyfans_payout_approved: int
    onlyfans_age_verified: int
    onlyfans_card_verified: int
    onlyfans_has_card: int
    onlyfans_subscriptions: str
    onlyfans_transactions: str
    feedback_data: str
    max_discount_percent: int
    priceWithSellerFee: float
    category: ItemCategory
    guarantee: str
    canViewLoginData: bool
    canViewTempEmail: bool
    canUpdateItemStats: bool
    canReportItem: bool
    canViewItemViews: bool
    canManagePublicTag: bool
    canViewEmailLoginData: bool
    title_link: str = Field(validation_alias=AliasPath("copyFormatData", "title_link"))
    showGetEmailCodeButton: bool
    canOpenItem: bool
    canCloseItem: bool
    canEditItem: bool
    canDeleteItem: bool
    canStickItem: bool
    canUnstickItem: bool
    canBumpItem: bool
    canNotBumpItemReason: str
    canAutoBump: bool
    buyer: str
    isPersonalAccount: bool
    canBuyItem: bool
    price_currency: str
    priceWithSellerFeeLabel: str
    canValidateAccount: bool
    canChangeOwner: bool
    canResellItem: bool
    onlyfansSubscriptions: list[ItemOnlyfansSubscription]
    onlyfansTransactions: list[ItemOnlyfansTransaction]
    canViewAccountLink: bool
    accountLinks: list[ItemAccountLink]
    accountLink: str
    imagePreviewLinks: list[str]
    emailLoginUrl: str
    canChangePassword: bool
    canChangeEmailPassword: bool
    uniqueKeyExists: bool
    itemOriginPhrase: str
    tags: list[str]
    public_tag: str
    note_text: str
    descriptionHtml: str
    descriptionEnHtml: str
    descriptionPlain: str
    descriptionEnPlain: str
    seller: ItemSeller
