"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.currency_list_btc import CurrencyListBTC
from pylzt.models.market.currency_list_rub import CurrencyListRUB


class CurrencyList(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/paymentscurrency
    """

    BTC: CurrencyListBTC
    ETH: CurrencyListBTC
    BNB: CurrencyListBTC
    BCH: CurrencyListBTC
    XMR: CurrencyListBTC
    SOL: CurrencyListBTC
    LTC: CurrencyListBTC
    DASH: CurrencyListBTC
    TON: CurrencyListBTC
    USDT: CurrencyListBTC
    MATIC: CurrencyListBTC
    TRX: CurrencyListBTC
    DOGE: CurrencyListBTC
    KWD: CurrencyListBTC
    GBP: CurrencyListBTC
    CHF: CurrencyListBTC
    EUR: CurrencyListBTC
    USD: CurrencyListBTC
    SGD: CurrencyListBTC
    CAD: CurrencyListBTC
    AUD: CurrencyListBTC
    NZD: CurrencyListBTC
    BGN: CurrencyListBTC
    GEL: CurrencyListBTC
    ILS: CurrencyListBTC
    QAR: CurrencyListBTC
    PEN: CurrencyListBTC
    AED: CurrencyListBTC
    SAR: CurrencyListBTC
    PLN: CurrencyListBTC
    MYR: CurrencyListBTC
    RON: CurrencyListBTC
    BRL: CurrencyListBTC
    DKK: CurrencyListBTC
    CNY: CurrencyListBTC
    HKD: CurrencyListBTC
    SEK: CurrencyListBTC
    NOK: CurrencyListBTC
    ZAR: CurrencyListBTC
    MXN: CurrencyListBTC
    CZK: CurrencyListBTC
    TWD: CurrencyListBTC
    THB: CurrencyListBTC
    TRY: CurrencyListBTC
    UAH: CurrencyListBTC
    UYU: CurrencyListBTC
    PHP: CurrencyListBTC
    INR: CurrencyListBTC
    RUB: CurrencyListRUB
    RSD: CurrencyListBTC
    JPY: CurrencyListBTC
    HUF: CurrencyListBTC
    KZT: CurrencyListBTC
    CRC: CurrencyListBTC
    CLP: CurrencyListBTC
    ARS: CurrencyListBTC
    KRW: CurrencyListBTC
    COP: CurrencyListBTC
    IDR: CurrencyListBTC
    VND: CurrencyListBTC
