"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.forum_prefixe_group_prefixe import ForumPrefixeGroupPrefixe


class ForumForumPrefixe(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/managingcreateclaim
    """

    group_title: str
    group_prefixes: list[ForumPrefixeGroupPrefixe]
