"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from typing import Any

from pylzt.models.base import LolzObject


class ItemIdTagAddedTagIdDeleteTagsResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/managingpublicuntag
    """

    itemId: int
    tag: dict[str, Any] | None = None
    addedTagId: int
    deleteTags: list[int]
