"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.genshin_character_reliquary import GenshinCharacterReliquary
from pylzt.models.market.genshin_character_weapon import GenshinCharacterWeapon


class ItemGenshinCharacter(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/categorymihoyo-1
    """

    id: int
    image: str
    icon: str
    name: str
    element: str
    fetter: int
    level: int
    rarity: int
    weapon: GenshinCharacterWeapon
    reliquaries: list[GenshinCharacterReliquary]
    actived_constellation_num: int
    costumes: list[str]
    external: str
    background: str
