"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject


class ItemTelegramGroupCounters(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/categorytelegram
    """

    chats: int
    channels: int
    conversations: int
    admin: int
