"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject


class ItemBumpSettings(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/cartget
    """

    canBumpItem: bool | None = None
    canBumpItemGlobally: bool | None = None
    shortErrorPhrase: str | None = None
    errorPhrase: str | None = None
