"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject


class ItemWotTopPremiumTank(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/categorywot-1
    """

    tank_id: int | None = None
    name: str | None = None
    is_premium: int | None = None
    image_url: str | None = None
    short_name: str | None = None
    tier: int | None = None
