"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.list_user_item import ListUserItem
from pylzt.models.market.user import User


class ListUserResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/listuser
    """

    items: list[ListUserItem]
    totalItems: int
    totalItemsPrice: int
    hasNextPage: bool
    perPage: int
    page: int
    wasCached: bool
    cacheTTL: int
    lastModified: int
    serverTime: int
    totalItemsPriceWithSellerFee: float
    searchUrl: str
    search: str
    stickyItems: list[str]
    user: User
    publishedPeriodLabelPhrase: str
    filterDatesDefault: bool
    published_startDate: str
    published_endDate: str
    filter_by_published_date: bool
    published_period_label: str
    paidPeriodLabelPhrase: str
    paid_startDate: str
    paid_endDate: str
    filter_by_buyer_operation_date: bool
    paid_period_label: str
    deletePeriodLabelPhrase: str
    delete_startDate: str
    delete_endDate: str
    filter_by_delete_date: bool
    delete_period_label: str
