"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.ma_file_session import MaFileSession


class MaFile(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/managingsteamgetmafile
    """

    shared_secret: str
    serial_number: int
    revocation_code: str
    uri: str
    account_name: str
    token_gid: str
    identity_secret: str
    secret_1: str
    device_id: str
    fully_enrolled: bool
    Session: MaFileSession
