"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.managing_bulk_get_item import ManagingBulkGetItem


class ManagingBulkGetResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/managingbulkget
    """

    items: list[ManagingBulkGetItem]
    left_item_id: list[int]
