"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pydantic import Field

from pylzt.models.base import LolzObject
from pylzt.models.market.list_user_item import ListUserItem


class ManagingBulkGetItem(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/managingbulkget
    """

    field_0: ListUserItem | None = Field(alias="0", default=None)
