"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.managing_steam_inventory_value_item import (
    ManagingSteamInventoryValueItem,
)


class ManagingSteamInventoryValueData(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/managingsteaminventoryvalue
    """

    items: dict[str, ManagingSteamInventoryValueItem]
    steam_id: str
    appId: int
    appTitle: str
    totalValue: float
    itemCount: int
    marketableItemCount: int
    currency: str
    currencyIcon: str
    language: str
    time: int
