"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.codes import Codes
from pylzt.models.market.list_user_item import ListUserItem


class ManagingTelegramCodeResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/managingtelegramcode
    """

    item: ListUserItem
    codes: Codes
