"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.managing_steam_inventory_value_data import ManagingSteamInventoryValueData


class MarketQueryDataAppIdResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/managingsteaminventoryvalue
    """

    query: str | None = None
    data: ManagingSteamInventoryValueData | None = None
    appId: int | None = None
