"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import BaseResponse


class MarketStatusItemResponse[MarketStatusItemResponseItemT](BaseResponse):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec."""

    item: MarketStatusItemResponseItemT
