"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.market.base_item import BaseItem
from pylzt.models.market.item_account_link import ItemAccountLink
from pylzt.models.market.item_bump_settings import ItemBumpSettings
from pylzt.models.market.item_genshin_character import ItemGenshinCharacter
from pylzt.models.market.item_honkai_character import ItemHonkaiCharacter
from pylzt.models.market.item_mihoyo_linked_accounts import ItemMihoyoLinkedAccounts
from pylzt.models.market.item_seller import ItemSeller
from pylzt.models.market.item_zenless_character import ItemZenlessCharacter


class MihoyoItem(BaseItem):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/categorymihoyo-1
    """

    view_count: int
    is_sticky: int
    item_origin: str
    extended_guarantee: int
    nsb: int
    allow_ask_discount: int
    title_en: str
    description_en: str
    email_type: str
    email_provider: str
    item_domain: str
    resale_item_origin: str
    mihoyo_item_id: int
    mihoyo_id: int
    mihoyo_email: int
    mihoyo_has_linked_accounts: int
    mihoyo_region: str
    mihoyo_last_activity: int
    mihoyo_genshin_level: int
    mihoyo_genshin_character_count: int
    mihoyo_genshin_achievement_count: int
    mihoyo_genshin_abyss_process: str
    mihoyo_genshin_legendary_characters_count: int
    mihoyo_genshin_constellations_count: int
    mihoyo_genshin_legendary_weapons_count: int
    mihoyo_genshin_activity_days: int
    mihoyo_genshin_currency: int
    mihoyo_honkai_level: int
    mihoyo_honkai_character_count: int
    mihoyo_honkai_achievement_count: int
    mihoyo_honkai_abyss_process: str
    mihoyo_honkai_legendary_characters_count: int
    mihoyo_honkai_eidolons_count: int
    mihoyo_honkai_legendary_weapons_count: int
    mihoyo_honkai_activity_days: int
    mihoyo_honkai_currency: int
    mihoyo_zenless_level: int
    mihoyo_zenless_character_count: int
    mihoyo_zenless_achievement_count: int
    mihoyo_zenless_abyss_process: str
    mihoyo_zenless_legendary_characters_count: int
    mihoyo_zenless_cinemas_count: int
    mihoyo_zenless_legendary_weapons_count: int
    mihoyo_zenless_activity_days: int
    mihoyo_zenless_currency: int
    feedback_data: str
    isIgnored: bool
    priceWithSellerFee: int
    guarantee: str
    canViewLoginData: bool
    canUpdateItemStats: bool
    canReportItem: bool
    canViewEmailLoginData: bool
    showGetEmailCodeButton: bool
    canOpenItem: bool
    canCloseItem: bool
    canEditItem: bool
    canDeleteItem: bool
    canStickItem: bool
    canUnstickItem: bool
    bumpSettings: ItemBumpSettings
    canBumpItem: bool
    canBuyItem: bool
    rub_price: int
    price_currency: str
    canValidateAccount: bool
    canResellItemAfterPurchase: bool
    mihoyoRegionPhrase: str
    mihoyoLinkedAccounts: ItemMihoyoLinkedAccounts
    mihoyoLinkedAccountsString: str
    honkaiCharacters: list[ItemHonkaiCharacter]
    genshinCharacters: list[ItemGenshinCharacter]
    zenlessCharacters: list[ItemZenlessCharacter]
    canViewAccountLink: bool
    accountLinks: list[ItemAccountLink]
    accountLink: str
    emailLoginUrl: str
    canChangePassword: bool
    itemOriginPhrase: str
    sold_items_category_count: int
    restore_items_category_count: int
    tags: list[str]
    note_text: str
    hasPendingAutoBuy: bool
    descriptionHtml: str
    descriptionEnHtml: str
    descriptionPlain: str
    descriptionEnPlain: str
    seller: ItemSeller
