"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pydantic import AliasPath, Field

from pylzt.models.base import LolzObject
from pylzt.models.market.balance import Balance
from pylzt.models.market.to import To


class PaymentsBalanceExchangeResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/paymentsbalanceexchange
    """

    balance: Balance = Field(validation_alias=AliasPath("from", "balance"))
    to: To
