"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject


class ProxyProxy(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/proxyget
    """

    proxy_id: int
    user_id: int
    proxy_ip: str
    proxy_port: int
    proxy_user: str
    proxy_pass: str
    proxyString: str
