"""Hand-patched in one place — the rest is handled by `LolzObject`.

A real `purchasing_fast_buy` against prod (2026-07-20, Steam lots at 1 rouble) failed validation
on ten fields at once: the purchase went through on the marketplace and the SDK raised anyway.
Seven of those were simply absent from the response and two were null — `LolzObject` now makes
every response field optional, so none of them need touching here.

`priceWithSellerFee` is the exception, because it is not a missing value but a wrong TYPE: the
spec says int, the wire says `0.9`, and `int_from_float` rejects it however optional it is. Same
fix already applied to `SteamItem`.

Re-running `python -m dev.codegen build` overwrites this file; re-apply the one-line patch.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.item_account_link import ItemAccountLink
from pylzt.models.market.item_bump_settings import ItemBumpSettings
from pylzt.models.market.item_extra_price import ItemExtraPrice
from pylzt.models.market.item_login_data import ItemLoginData
from pylzt.models.market.publishing_check_item_buyer import PublishingCheckItemBuyer
from pylzt.models.market.publishing_check_item_guarantee import PublishingCheckItemGuarantee
from pylzt.models.market.publishing_check_item_seller import PublishingCheckItemSeller
from pylzt.models.market.tag import Tag


class PublishingCheckItem(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/publishingcheck
    """

    item_id: int
    item_state: str
    category_id: int
    published_date: int
    title: str
    description: str
    price: int
    update_stat_date: int
    refreshed_date: int
    edit_date: int
    login: str
    temp_email: str
    view_count: int
    is_sticky: int
    information: str
    item_origin: str
    extended_guarantee: int
    nsb: int
    allow_ask_discount: int
    title_en: str
    description_en: str
    information_en: str
    email_type: str
    email_provider: str
    item_domain: str
    resale_item_origin: str
    user_allow_ask_discount: int
    max_discount_percent: int
    market_custom_title: str
    feedback_data: str
    buyer_avatar_date: int
    buyer_user_group_id: int
    priceWithSellerFee: float
    guarantee: PublishingCheckItemGuarantee
    canViewLoginData: bool
    canUpdateItemStats: bool
    canReportItem: bool
    loginData: ItemLoginData
    canViewEmailLoginData: bool
    emailLoginData: ItemLoginData
    showGetEmailCodeButton: bool
    getEmailCodeDisplayLogin: str
    buyer: PublishingCheckItemBuyer
    isPersonalAccount: bool
    sold_items_category_count: int
    restore_items_category_count: int
    rub_price: int
    price_currency: str
    canValidateAccount: bool
    canResellItemAfterPurchase: bool
    account_last_activity: int
    displayConvertedBalance: bool
    canViewAccountLink: bool
    accountLinks: list[ItemAccountLink]
    accountLink: str
    emailLoginUrl: str
    canChangePassword: bool
    itemOriginPhrase: str
    visitorIsAuthor: bool
    canAskDiscount: bool
    tags: dict[str, Tag]
    customFields: list[str]
    externalAuth: list[str]
    isTrusted: bool
    isBirthdayToday: bool
    isIgnored: bool
    deposit: int
    extraPrices: list[ItemExtraPrice]
    canViewAccountLoginAndTempEmail: bool
    bumpSettings: ItemBumpSettings
    canCheckGuarantee: bool
    needToRequireVideoToViewLoginData: bool
    descriptionHtml: str
    descriptionEnHtml: str
    descriptionPlain: str
    descriptionEnPlain: str
    seller: PublishingCheckItemSeller
