"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.item_account_link import ItemAccountLink
from pylzt.models.market.item_bump_settings import ItemBumpSettings
from pylzt.models.market.item_extra_price import ItemExtraPrice
from pylzt.models.market.item_guarantee import ItemGuarantee
from pylzt.models.market.purchasing_check_item_seller import PurchasingCheckItemSeller


class PurchasingCheckItem(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/purchasingcheck
    """

    item_id: int
    item_state: str
    category_id: int
    published_date: int
    title: str
    description: str
    price: int
    update_stat_date: int
    refreshed_date: int
    edit_date: int
    view_count: int
    is_sticky: int
    item_origin: str
    extended_guarantee: int
    nsb: int
    allow_ask_discount: int
    title_en: str
    description_en: str
    email_type: str
    email_provider: str
    item_domain: str
    resale_item_origin: str
    user_allow_ask_discount: int
    max_discount_percent: int
    market_custom_title: str
    feedback_data: str
    category_title: str
    category_url: str
    require_temp_email: int
    available_temp_email: int
    check_button_enabled: int
    checker_enabled: int
    buy_without_validation: int
    has_guarantee: int
    require_video_recording: int
    can_be_resold: int
    login_type: str
    require_email_login_data: int
    category_prefix_id: int
    ask_user_id: str
    ask_item_id: str
    ask_date: str
    discount_price: str
    discount_accepted: str
    user_alerted: str
    message: str
    min_price: int
    priceWithSellerFee: int
    guarantee: ItemGuarantee
    canViewLoginData: bool
    canUpdateItemStats: bool
    canReportItem: bool
    canViewEmailLoginData: bool
    showGetEmailCodeButton: bool
    isPersonalAccount: bool
    rub_price: int
    price_currency: str
    canValidateAccount: bool
    canResellItemAfterPurchase: bool
    isSmallExf: bool
    account_last_activity: int
    canViewAccountLink: bool
    accountLinks: list[ItemAccountLink]
    accountLink: str
    emailLoginUrl: str
    canChangePassword: bool
    itemOriginPhrase: str
    visitorIsAuthor: bool
    canAskDiscount: bool
    tags: list[str]
    customFields: list[str]
    externalAuth: list[str]
    isTrusted: bool
    isBirthdayToday: bool
    isIgnored: bool
    deposit: int
    extraPrices: list[ItemExtraPrice]
    canViewAccountLoginAndTempEmail: bool
    bumpSettings: ItemBumpSettings
    canCheckGuarantee: bool
    needToRequireVideoToViewLoginData: bool
    descriptionHtml: str
    descriptionEnHtml: str
    descriptionPlain: str
    descriptionEnPlain: str
    seller: PurchasingCheckItemSeller
