"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.

Hand-patched (2026-07-08): the generator prefixed the PEP 695 type parameter with `_`
(`_type_var_name` in dev/codegen/generator.py), which ruff UP049 now flags — a leading
underscore signals module-privacy but a type param already has its own scope. Fixed in
the generator; this file matches what the next regen produces.
"""

from __future__ import annotations

from pylzt.models.base import BaseResponse


class StatusItemResponse[StatusItemResponseItemT](BaseResponse):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec."""

    item: StatusItemResponseItemT
