"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.providers_bep20 import ProvidersBEP20


class SystemProviders(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/paymentspayoutservices
    """

    BEP20: ProvidersBEP20
    TRC20: ProvidersBEP20
    ERC20: ProvidersBEP20
    TRX: ProvidersBEP20
    BTC: ProvidersBEP20
    TON: ProvidersBEP20
    ETH: ProvidersBEP20
    LTC: ProvidersBEP20
    BNB: ProvidersBEP20
    DASH: ProvidersBEP20
    DOGE: ProvidersBEP20
    XMR: ProvidersBEP20
    SOL: ProvidersBEP20
    BCH: ProvidersBEP20
