"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.first_post_like_user import FirstPostLikeUser
from pylzt.models.market.first_post_links import FirstPostLinks
from pylzt.models.market.first_post_permissions import FirstPostPermissions


class ThreadFirstPost(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/managingcreateclaim
    """

    post_id: int
    thread_id: int
    poster_user_id: int
    poster_username: str
    post_create_date: int
    post_body: str
    post_body_html: str
    post_body_plain_text: str
    signature: str
    signature_html: str
    signature_plain_text: str
    post_like_count: int
    post_attachment_count: int
    like_users: list[FirstPostLikeUser]
    user_is_ignored: bool
    post_is_published: bool
    post_is_deleted: bool
    post_update_date: int
    post_is_first_post: bool
    links: FirstPostLinks
    permissions: FirstPostPermissions
