"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.thread_first_post import ThreadFirstPost
from pylzt.models.market.thread_forum import ThreadForum
from pylzt.models.market.thread_links import ThreadLinks
from pylzt.models.market.thread_permissions import ThreadPermissions


class Thread(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/managingcreateclaim
    """

    thread_id: int
    forum_id: int
    thread_title: str
    thread_view_count: int
    creator_user_id: int
    creator_username: str
    thread_create_date: int
    thread_update_date: int
    user_is_ignored: bool
    thread_post_count: int
    thread_is_published: bool
    thread_is_deleted: bool
    thread_is_sticky: bool
    thread_is_followed: bool
    first_post: ThreadFirstPost
    thread_prefixes: list[str]
    thread_tags: list[str]
    links: ThreadLinks
    permissions: ThreadPermissions
    forum: ThreadForum
