"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject


class UserTelegramClient(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/profileget
    """

    telegram_api_id: str
    telegram_api_hash: str
    telegram_device_model: str
    telegram_system_version: str
    telegram_app_version: str
    telegram_system_lang_code: str
    telegram_lang_code: str
    telegram_lang_pack: str
