"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.base import LolzObject
from pylzt.models.market.weapon_property import WeaponProperty


class ZenlessCharacterWeapon(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://lzt-market.readme.io/reference/categorymihoyo-1
    """

    id: int
    level: int
    name: str
    star: int
    icon: str
    rarity: int
    properties: list[WeaponProperty]
    main_properties: list[WeaponProperty]
    talent_title: str
    talent_content: str
    profession: int
    starIcon: str
    rarityIcon: str
