"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.methods.base import BaseMethod, passthrough
from pylzt.models.antipublic import PublicCountLinesResponse
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "Public.CountLines".
class PublicCountLines(BaseMethod[PublicCountLinesResponse]):
    """Generated by forge — DO NOT EDIT. Count Lines.
    Sourced from the official OpenAPI spec (readme.io).
    Get count of rows in the AntiPublic db.

    Docs: https://antipublic.readme.io/reference/publiccountlines-1
    """

    __api__ = ApiTarget.ANTIPUBLIC
    __rate_class__ = RateClass.ANTIPUBLIC
    __http_method__ = HttpMethod.GET
    __url__ = "/countLines"
    __returning__ = PublicCountLinesResponse


# Source: official OpenAPI spec, operationId "Public.CountLinesPlain".
class PublicCountLinesPlain(BaseMethod[str]):  # 200 is text/html: a bare string, not JSON
    """Generated by forge — DO NOT EDIT. Count Lines Plain.
    Sourced from the official OpenAPI spec (readme.io).
    Get count of rows in the AntiPublic db (raw format).

    Docs: https://antipublic.readme.io/reference/publiccountlinesplain-1
    """

    __api__ = ApiTarget.ANTIPUBLIC
    __rate_class__ = RateClass.ANTIPUBLIC
    __http_method__ = HttpMethod.GET
    __url__ = "/countLinesPlain"
    __returning__ = passthrough
