"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.methods.base import BaseMethod, passthrough
from pylzt.models.antipublic import Threads
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "License.AvailableQueries".
class LicenseAvailableQueries(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Available Queries.
    Sourced from the official OpenAPI spec (readme.io).
    Get your available queries.

    Docs: https://antipublic.readme.io/reference/licenseavailablequeries-1
    """

    __api__ = ApiTarget.ANTIPUBLIC
    __rate_class__ = RateClass.ANTIPUBLIC
    __http_method__ = HttpMethod.GET
    __url__ = "/availableQueries"
    __returning__ = passthrough


# Source: official OpenAPI spec, operationId "License.CheckLicense".
class LicenseCheckLicense(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Check Access.
    Sourced from the official OpenAPI spec (readme.io).
    Checks your license.

    Docs: https://antipublic.readme.io/reference/licensechecklicense-1
    """

    __api__ = ApiTarget.ANTIPUBLIC
    __rate_class__ = RateClass.ANTIPUBLIC
    __http_method__ = HttpMethod.GET
    __url__ = "/checkAccess"
    __returning__ = passthrough


# Source: official OpenAPI spec, operationId "get_/debug".
class GetDebug(BaseMethod[Threads]):
    """Generated by forge — DO NOT EDIT. Threads usage debug.
    Sourced from the official OpenAPI spec (readme.io).

    Docs: https://antipublic.readme.io/reference/get_debug
    """

    __api__ = ApiTarget.ANTIPUBLIC
    __rate_class__ = RateClass.ANTIPUBLIC
    __http_method__ = HttpMethod.GET
    __url__ = "/debug"
    __returning__ = Threads
    __unwrap__ = "threads"
