"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from typing import Any

from pylzt.enums.antipublic import Format, GroupBy, Order, SearchBy
from pylzt.methods.base import BaseMethod, passthrough
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "License.Search".
class LicenseSearch(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Search.
    Sourced from the official OpenAPI spec (readme.io).
    Search lines by email/password/domain.

    Args:
        searchBy: Search type. Search Priority: - **searchBy: email** - `email`, then `password`. - **searchBy: password** - `password`, then `email`. - **searchBy: domain** - `domain`, then `email`, then `password`.
        query: Search query
        direction: Search direction To use `all` - Premium required
        order: [**Premium** subscription required] If you specify DESC order, then most likely you will have a couple of results. Everything is fine and it should be. To get more results - you need to disable fuses by specifying `all` in `direction` for your query field. Or if the request field is `strict`, then specify `fromLastValueOfKey` equal to true.
        fromLastValueOfKey: [**Premium** subscription required] When using this option and "strict direction" the starting position starts from the last value of the key. For example, we have *email:pass1*, *email:pass2*, *email:pass3*. Then when setting `query` = email, `direction` = strict, `fromLastValueOfKey` = true the first result obtained will be `email:pass3`.
        groupBy: [**Premium** subscription required] This option allows you to remove "duplicates". Only the first found line corresponding to the grouping will be returned and will move on to the next value. Can be used in the following cases: - **searchBy: email** - `login@domain`. - **searchBy: password** - `password`. - **searchBy: domain** - `domain`, `login@domain`.
        format: The format of the returned results. Allows you to quickly leave the most necessary without post-processing. When used correctly together with `groupBy`, the execution time of a database search query can be accelerated by eliminating JOIN operations on the server.
        pageToken: The page token that was returned in the previous request. The token will be considered invalid if any of the request parameters change.

    Docs: https://antipublic.readme.io/reference/licensesearch-1
    """

    __api__ = ApiTarget.ANTIPUBLIC
    __rate_class__ = RateClass.ANTIPUBLIC
    __http_method__ = HttpMethod.POST
    __url__ = "/search"
    __returning__ = passthrough

    searchBy: SearchBy
    query: dict[str, Any]
    direction: dict[str, Any] | None = None
    order: Order | None = None
    fromLastValueOfKey: bool | None = None
    groupBy: GroupBy | None = None
    format: Format | None = None
    pageToken: str | None = None


# Source: official OpenAPI spec, operationId "LicensePlus.EmailPasswords".
class LicensePlusEmailPasswords(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Email Passwords.
    Sourced from the official OpenAPI spec (readme.io).
    Get passwords for emails. AntiPublic Plus subscription required.

    Args:
        emails: Emails for search.
        onlyPassword: Return only passwords, instead of lines with logins
        limit: Result limit (per email).

    Docs: https://antipublic.readme.io/reference/licenseplusemailpasswords-1
    """

    __api__ = ApiTarget.ANTIPUBLIC
    __rate_class__ = RateClass.ANTIPUBLIC
    __http_method__ = HttpMethod.POST
    __url__ = "/emailPasswords"
    __returning__ = passthrough

    emails: tuple[str, ...]
    onlyPassword: bool | None = None
    limit: int | None = None
