"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.methods.base import BaseMethod, passthrough
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "License.CheckLines".
class LicenseCheckLines(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Check Lines.
    Sourced from the official OpenAPI spec (readme.io).
    Check your lines. Maximum 1000 lines per request.

    Args:
        lines: Lines for check, email:password.
        insert: Upload private rows to AntiPublic db.

    Docs: https://antipublic.readme.io/reference/licensechecklines-1
    """

    __api__ = ApiTarget.ANTIPUBLIC
    __rate_class__ = RateClass.ANTIPUBLIC
    __http_method__ = HttpMethod.POST
    __url__ = "/checkLines"
    __returning__ = passthrough

    lines: tuple[str, ...]
    insert: bool | None = None
