"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.enums.forum import (
    ContestType,
    Direction,
    FieldsInclude,
    LengthOption,
    Order,
    PayClaim,
    Period,
    PrizeType,
    State,
    TransferType,
)
from pylzt.methods.base import BaseMethod, passthrough
from pylzt.models.forum import Content, ForumStatusMessageResponse
from pylzt.types import ApiTarget, Currency, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "Threads.Bump".
class ThreadsBump(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Bump Thread.
    Sourced from the official OpenAPI spec (readme.io).
    Bump a thread.
    Required scopes:
    + **post**

    Args:
        thread_id: Id of thread.

    Docs: https://lolzteam.readme.io/reference/threadsbump
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/threads/{thread_id}/bump"
    __returning__ = passthrough

    thread_id: int


# Source: official OpenAPI spec, operationId "Threads.Claim".
class ThreadsClaim(BaseMethod[Content]):
    """Generated by forge — DO NOT EDIT. Create Claim.
    Sourced from the official OpenAPI spec (readme.io).
    Create a Claim.
    Required scopes:
    + **post**

    Args:
        as_responder: To whom the complaint is filed. Specify a nickname or a link to the profile.
        as_is_market_deal: Did you buy account on the market?
        as_amount: Indicate the amount by which the responder deceived you.
        transfer_type: The transaction took place through a guarantor or there was a transfer to the market with a hold? Required if **as_is_market_deal** is 0.
        post_body: You should describe what's happened. - describe the situation in a nutshell. If you wish, you can describe the situation in more detail using the "Spoiler" function. - attach screenshots of correspondence. You may upload to the site [Imgur](https://imgur.com/upload) - for convenience, use Ctrl + V when uploading screenshots to the album. - other evidence; - notify the respondent about the complaint you created, familiarize him with hidden content Describe the situation in as much detail as possible.
        as_market_item_id: Market item id. Required if **as_is_market_deal** is 1.
        as_data: Contacts and wallets of the responder. Specify the known data about the responder, if any. Optional if **as_is_market_deal** is 0.
        currency: Currency of Claim.
        pay_claim: Pay claim fee now or later. (Only for **transfer_type** = **notsafe**)
        as_funds_receipt: Funds transfer receipt. Upload a receipt for the transfer of funds, use the "View receipt" button in your wallet. May be uploaded to [Imgur](https://imgur.com/upload). Write "no" if you have not paid. Required if **as_is_market_deal** is 0.
        as_tg_login_screenshot: Screenshot showing the respondent's Telegram login. If the correspondence was conducted in Telegram, upload a screenshot that will display the respondent's Telegram login against the background of your dialogue. The screenshot may be uploaded to [Imgur](https://imgur.com/upload). If the correspondence was conducted elsewhere, write "no".
        tags: Thread tags.
        hide_contacts: Hide contacts.
        allow_ask_hidden_content: Allow ask hidden content.
        reply_group: Allow to reply only users with chosen or higher group.
        comment_ignore_group: Allow commenting if user can't post in thread.
        dont_alert_followers: Don't alert followers about thread creation.
        schedule_date: Date to schedule thread creation (format: `DD-MM-YYYY`).
        schedule_time: Time to schedule thread creation (format: `HH:MM`).
        watch_thread_state: Watch thread state.
        watch_thread: Receive forum notifications of new posts in this thread.
        watch_thread_email: Receive email notifications of new posts in this thread.

    Docs: https://lolzteam.readme.io/reference/threadsclaim
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/claims"
    __returning__ = Content
    __unwrap__ = "thread"

    as_responder: str
    as_is_market_deal: bool
    as_amount: float
    transfer_type: TransferType
    post_body: str
    as_market_item_id: int | None = None
    as_data: str | None = None
    currency: Currency | None = None
    pay_claim: PayClaim | None = None
    as_funds_receipt: str | None = None
    as_tg_login_screenshot: str | None = None
    tags: tuple[str, ...] | None = None
    hide_contacts: bool | None = None
    allow_ask_hidden_content: bool | None = None
    reply_group: int | None = None
    comment_ignore_group: bool | None = None
    dont_alert_followers: bool | None = None
    schedule_date: str | None = None
    schedule_time: str | None = None
    watch_thread_state: bool | None = None
    watch_thread: bool | None = None
    watch_thread_email: bool | None = None


# Source: official OpenAPI spec, operationId "Threads.CreateContest".
class ThreadsCreateContest(BaseMethod[Content]):
    """Generated by forge — DO NOT EDIT. Create Contest.
    Sourced from the official OpenAPI spec (readme.io).
    Create a new contest.
    Required scopes:
    + **post**

    Args:
        post_body: Content of the new contest.
        contest_type: Contest type.
        prize_type: Prize type.
        require_like_count: Sympathies for this week.
        require_total_like_count: Sympathies for all time.
        title: Thread title. Can be skipped if **title_en** set.
        title_en: Thread english title. Can be skipped if **title** set.
        length_value: Giveaway duration value. The maximum duration is 3 days. Required if **contest_type** is **by_finish_date**.
        length_option: Giveaway duration type. The maximum duration is 3 days. Required if **contest_type** is **by_finish_date**.
        count_winners: Winner count (prize count). Optional if **prize_type** is **money**.
        prize_data_money: How much money will each winner receive. Optional if **prize_type** is **money**.
        is_money_places: Enable the distribution of money prizes by places. Optional if **prize_type** is **money**.
        prize_data_places: How much money will receive each place. Required if **is_money_places** is **1**.
        prize_data_upgrade: Which upgrade will each winner receive. Required if **prize_type** is **upgrades**.
        secret_answer: Secret answer of your account.
        tags: Thread tags.
        reply_group: Allow to reply only users with chosen or higher group.
        comment_ignore_group: Allow commenting if user can't post in thread.
        dont_alert_followers: Don't alert followers about thread creation.
        hide_contacts: Hide contacts.
        allow_ask_hidden_content: Allow ask hidden content.
        schedule_date: Date to schedule thread creation (format: `DD-MM-YYYY`).
        schedule_time: Time to schedule thread creation (format: `HH:MM`).
        watch_thread_state: Watch thread state.
        watch_thread: Receive forum notifications of new posts in this thread.
        watch_thread_email: Receive email notifications of new posts in this thread.

    Docs: https://lolzteam.readme.io/reference/threadscreatecontest
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/contests"
    __returning__ = Content
    __unwrap__ = "thread"

    post_body: str
    contest_type: ContestType
    prize_type: PrizeType
    require_like_count: int
    require_total_like_count: int
    title: str | None = None
    title_en: str | None = None
    length_value: int | None = None
    length_option: LengthOption | None = None
    count_winners: int | None = None
    prize_data_money: float | None = None
    is_money_places: bool | None = None
    prize_data_places: tuple[float, ...] | None = None
    prize_data_upgrade: int | None = None
    secret_answer: str | None = None
    tags: tuple[str, ...] | None = None
    reply_group: int | None = None
    comment_ignore_group: bool | None = None
    dont_alert_followers: bool | None = None
    hide_contacts: bool | None = None
    allow_ask_hidden_content: bool | None = None
    schedule_date: str | None = None
    schedule_time: str | None = None
    watch_thread_state: bool | None = None
    watch_thread: bool | None = None
    watch_thread_email: bool | None = None


# Source: official OpenAPI spec, operationId "Threads.Finish".
class ThreadsFinish(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Finish Contest.
    Sourced from the official OpenAPI spec (readme.io).
    Finishes a contest.
    Required scopes:
    + **post**

    Args:
        thread_id: Id of thread.

    Docs: https://lolzteam.readme.io/reference/threadsfinish
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/contests/{thread_id}/finish"
    __returning__ = ForumStatusMessageResponse

    thread_id: int


# Source: official OpenAPI spec, operationId "Threads.Followed".
class ThreadsFollowed(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Followed Threads.
    Sourced from the official OpenAPI spec (readme.io).
    List of followed threads by current user.
    Required scopes:
    + **read**

    Args:
        total: If included in the request, only the thread count is returned as **threads_total**.
        fields_include: List of fields to include.

    Docs: https://lolzteam.readme.io/reference/threadsfollowed
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/threads/followed"
    __returning__ = passthrough

    total: bool | None = None
    fields_include: tuple[FieldsInclude, ...] | None = None


# Source: official OpenAPI spec, operationId "Threads.Get".
class ThreadsGet(BaseMethod[Content]):
    """Generated by forge — DO NOT EDIT. Get Thread.
    Sourced from the official OpenAPI spec (readme.io).
    Detail information of a thread.
    Required scopes:
    + **read**

    Args:
        thread_id: Id of thread.
        fields_include: List of fields to include.

    Docs: https://lolzteam.readme.io/reference/threadsget
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/threads/{thread_id}"
    __returning__ = Content
    __unwrap__ = "thread"

    thread_id: int
    fields_include: tuple[FieldsInclude, ...] | None = None


# Source: official OpenAPI spec, operationId "Threads.Hide".
class ThreadsHide(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Hide Thread.
    Sourced from the official OpenAPI spec (readme.io).
    Hide a thread from your feed.
    Required scopes:
    + **post**

    Args:
        thread_id: Id of thread.

    Docs: https://lolzteam.readme.io/reference/threadshide
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/threads/{thread_id}/hide"
    __returning__ = passthrough

    thread_id: int


# Source: official OpenAPI spec, operationId "Threads.List".
class ThreadsList(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Threads.
    Sourced from the official OpenAPI spec (readme.io).
    List of threads in a forum (with pagination).
    Required scopes:
    + **read**

    Args:
        forum_id: Id of the containing forum.
        tab: Tab to get threads from.
        state: Thread state. Works only if **forum_id** is set.
        period: Filter to get only threads created within the selected period. Works only if **forum_id** is set.
        title: Thread title.
        title_only: Search only in titles.
        creator_user_id: Filter to get only threads created by the specified user.
        sticky: Filter to get only sticky or non-sticky threads. By default, all threads will be included and sticky ones will be at the top of the result on the first page. In mixed mode, sticky threads are not counted towards **threads_total** and does not affect pagination.
        prefix_ids: Filter to get only threads with the specified prefix.
        prefix_ids_not: Filter to get only threads without the specified prefix.
        thread_tag_id: Filter to get only threads with the specified tag.
        page: Page number of threads.
        limit: Number of threads in a page.
        order: Ordering of threads.
        direction: Direction of threads ordering.
        thread_create_date: Filter threads by creation date. Only works with 'thread_create_date' and 'thread_create_date_reverse' ordering.
        thread_update_date: Filter threads by update date. Only works with 'thread_update_date' and 'thread_update_date_reverse' ordering.
        fields_include: List of fields to include.

    Docs: https://lolzteam.readme.io/reference/threadslist
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/threads"
    __returning__ = passthrough

    forum_id: int | None = None
    tab: str | None = None
    state: State | None = None
    period: Period | None = None
    title: str | None = None
    title_only: bool | None = None
    creator_user_id: int | None = None
    sticky: bool | None = None
    prefix_ids: tuple[int, ...] | None = None  # wire: 'prefix_ids[]'
    prefix_ids_not: tuple[int, ...] | None = None  # wire: 'prefix_ids_not[]'
    thread_tag_id: int | None = None
    page: int | None = None
    limit: int | None = None
    order: Order | None = None
    direction: Direction | None = None
    thread_create_date: int | None = None
    thread_update_date: int | None = None
    fields_include: tuple[FieldsInclude, ...] | None = None


# Source: official OpenAPI spec, operationId "Threads.Move".
class ThreadsMove(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Move Thread.
    Sourced from the official OpenAPI spec (readme.io).
    Move a thread to another forum.
    Required scopes:
    + **post**

    Args:
        thread_id: Id of thread.
        node_id: Forum id.
        title: Thread title.
        title_en: Thread title english.
        prefix_id: Prefix ids. Set "0" to remove all thread prefixes.
        apply_thread_prefix: Apply thread prefix.
        send_alert: Send a notification to users who are followed to target node.

    Docs: https://lolzteam.readme.io/reference/threadsmove
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/threads/{thread_id}/move"
    __returning__ = ForumStatusMessageResponse

    thread_id: int
    node_id: str
    title: str | None = None
    title_en: str | None = None
    prefix_id: tuple[int, ...] | None = None
    apply_thread_prefix: bool | None = None
    send_alert: bool | None = None


# Source: official OpenAPI spec, operationId "Threads.Navigation".
class ThreadsNavigation(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Navigation Elements.
    Sourced from the official OpenAPI spec (readme.io).
    List of navigation elements to reach the specified thread.
    Required scopes:
    + **read**

    Args:
        thread_id: Id of thread.

    Docs: https://lolzteam.readme.io/reference/threadsnavigation
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/threads/{thread_id}/navigation"
    __returning__ = passthrough

    thread_id: int


# Source: official OpenAPI spec, operationId "Threads.Poll.Get".
class ThreadsPollGet(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Poll.
    Sourced from the official OpenAPI spec (readme.io).
    Detail information of a poll.
    Required scopes:
    + **read**

    Args:
        thread_id: Id of thread.

    Docs: https://lolzteam.readme.io/reference/threadspollget
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/threads/{thread_id}/poll"
    __returning__ = passthrough

    thread_id: int


# Source: official OpenAPI spec, operationId "Threads.Poll.Vote".
class ThreadsPollVote(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Vote Poll.
    Sourced from the official OpenAPI spec (readme.io).
    Vote on a thread poll.
    Required scopes:
    + **post**

    Args:
        thread_id: Id of thread.
        response_id: The id of the response to vote for. Can be skipped if **response_ids** set.
        response_ids: An array of ids of responses (if the poll allows multiple choices).

    Docs: https://lolzteam.readme.io/reference/threadspollvote
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/threads/{thread_id}/poll/votes"
    __returning__ = ForumStatusMessageResponse

    thread_id: int
    response_id: int | None = None
    response_ids: tuple[int, ...] | None = None


# Source: official OpenAPI spec, operationId "Threads.Recent".
class ThreadsRecent(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Recent Threads.
    Sourced from the official OpenAPI spec (readme.io).
    List of recent threads.
    Required scopes:
    + **read**

    Args:
        days: Maximum number of days to search for threads.
        limit: Maximum number of result threads. The limit may get decreased if the value is too large.
        forum_id: Id of the container forum to search for threads. Child forums of the specified forum will be included in the search.
        data_limit: Number of thread data to be returned. Default value is 20.

    Docs: https://lolzteam.readme.io/reference/threadsrecent
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/threads/recent"
    __returning__ = passthrough

    days: int | None = None
    limit: int | None = None
    forum_id: int | None = None
    data_limit: int | None = None


# Source: official OpenAPI spec, operationId "Threads.Unfollow".
class ThreadsUnfollow(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Unfollow Thread.
    Sourced from the official OpenAPI spec (readme.io).
    Unfollow a thread.
    Required scopes:
    + **post**

    Args:
        thread_id: Id of thread.

    Docs: https://lolzteam.readme.io/reference/threadsunfollow
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.DELETE
    __url__ = "/threads/{thread_id}/followers"
    __returning__ = ForumStatusMessageResponse

    thread_id: int


# Source: official OpenAPI spec, operationId "Threads.Unread".
class ThreadsUnread(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Unread Threads.
    Sourced from the official OpenAPI spec (readme.io).
    List of unread threads (must be logged in).
    Required scopes:
    + **read**

    Args:
        limit: Maximum number of result threads. The limit may get decreased if the value is too large (depending on the system configuration).
        forum_id: Id of the container forum to search for threads. Child forums of the specified forum will be included in the search.
        data_limit: Number of thread data to be returned. Default value is 20.

    Docs: https://lolzteam.readme.io/reference/threadsunread
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/threads/new"
    __returning__ = passthrough

    limit: int | None = None
    forum_id: int | None = None
    data_limit: int | None = None


# Source: official OpenAPI spec, operationId "Threads.Unstar".
class ThreadsUnstar(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Unbookmark Thread.
    Sourced from the official OpenAPI spec (readme.io).
    Unbookmark a thread.
    Required scopes:
    + **post**

    Args:
        thread_id: Id of thread.

    Docs: https://lolzteam.readme.io/reference/threadsunstar
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.DELETE
    __url__ = "/threads/{thread_id}/star"
    __returning__ = ForumStatusMessageResponse

    thread_id: int
