"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.enums.forum import Order
from pylzt.methods.base import BaseMethod, passthrough
from pylzt.models.forum import (
    ForumsGetFeedOptionsResponse,
    ForumsGroupedResponse,
    ForumsListResponse,
    ForumStatusMessageResponse,
)
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "Forums.Followed".
class ForumsFollowed(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Followed Forums.
    Sourced from the official OpenAPI spec (readme.io).
    List of followed forums by current user.
    Required scopes:
    + **read**

    Args:
        total: If included in the request, only the forum count is returned as **forums_total**.

    Docs: https://lolzteam.readme.io/reference/forumsfollowed
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/forums/followed"
    __returning__ = passthrough

    total: bool | None = None


# Source: official OpenAPI spec, operationId "Forums.Get".
class ForumsGet(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Forum.
    Sourced from the official OpenAPI spec (readme.io).
    Detail information of a forum.
    Required scopes:
    + **read**

    Args:
        forum_id: Id of forum.

    Docs: https://lolzteam.readme.io/reference/forumsget
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/forums/{forum_id}"
    __returning__ = passthrough

    forum_id: int


# Source: official OpenAPI spec, operationId "Forums.GetFeedOptions".
class ForumsGetFeedOptions(BaseMethod[ForumsGetFeedOptionsResponse]):
    """Generated by forge — DO NOT EDIT. Get Feed Options.
    Sourced from the official OpenAPI spec (readme.io).
    Returns available options for the forums feed.
    Required scopes:
    + **read**

    Docs: https://lolzteam.readme.io/reference/forumsgetfeedoptions
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/forums/feed/options"
    __returning__ = ForumsGetFeedOptionsResponse


# Source: official OpenAPI spec, operationId "Forums.Grouped".
class ForumsGrouped(BaseMethod[ForumsGroupedResponse]):
    """Generated by forge — DO NOT EDIT. Get Forums Tree.
    Sourced from the official OpenAPI spec (readme.io).
    Returns grouped forums.
    Required scopes:
    + **read**

    Docs: https://lolzteam.readme.io/reference/forumsgrouped
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/forums/grouped"
    __returning__ = ForumsGroupedResponse


# Source: official OpenAPI spec, operationId "Forums.List".
class ForumsList(BaseMethod[ForumsListResponse]):
    """Generated by forge — DO NOT EDIT. Get Forums.
    Sourced from the official OpenAPI spec (readme.io).
    List of all forums in the system.
    Required scopes:
    + **read**

    Args:
        parent_category_id: Id of parent category. If exists, filter forums that are direct children of that category.
        parent_forum_id: Id of parent forum. If exists, filter forums that are direct children of that forum.
        order: Ordering of forums.

    Docs: https://lolzteam.readme.io/reference/forumslist
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/forums"
    __returning__ = ForumsListResponse

    parent_category_id: int | None = None
    parent_forum_id: int | None = None
    order: Order | None = None


# Source: official OpenAPI spec, operationId "Forums.Unfollow".
class ForumsUnfollow(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Unfollow Forum.
    Sourced from the official OpenAPI spec (readme.io).
    Unfollow a forum.
    Required scopes:
    + **post**

    Args:
        forum_id: Id of forum.

    Docs: https://lolzteam.readme.io/reference/forumsunfollow
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.DELETE
    __url__ = "/forums/{forum_id}/followers"
    __returning__ = ForumStatusMessageResponse

    forum_id: int
