"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.methods.base import BaseMethod
from pylzt.models.forum import OAuthTokenResponse
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "OAuth.Token".
class OAuthToken(BaseMethod[OAuthTokenResponse]):
    """Generated by forge — DO NOT EDIT. Get Access Token.
    Sourced from the official OpenAPI spec (readme.io).
    Obtain an access token using various grant types.
    Supports the following grant types:
    - Client Credentials
    - Authorization Code
    - Refresh Token
    - Password

    Docs: https://lolzteam.readme.io/reference/oauthtoken
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/oauth/token"
    __returning__ = OAuthTokenResponse
