"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.methods.base import BaseMethod, passthrough
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "Tags.Find".
class TagsFind(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Filtered Content.
    Sourced from the official OpenAPI spec (readme.io).
    Filtered list of tags.
    Required scopes:
    + **read**

    Args:
        tag: tag to filter. Tags start with the query will be returned.

    Docs: https://lolzteam.readme.io/reference/tagsfind
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/tags/find"
    __returning__ = passthrough

    tag: str


# Source: official OpenAPI spec, operationId "Tags.Get".
class TagsGet(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Tagged Content.
    Sourced from the official OpenAPI spec (readme.io).
    List of tagged contents.
    Required scopes:
    + **read**

    Args:
        tag_id: Id of tag.
        page: Page number of tagged contents.
        limit: Number of tagged contents in a page.

    Docs: https://lolzteam.readme.io/reference/tagsget
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/tags/{tag_id}"
    __returning__ = passthrough

    tag_id: int
    page: int | None = None
    limit: int | None = None


# Source: official OpenAPI spec, operationId "Tags.List".
class TagsList(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Tags.
    Sourced from the official OpenAPI spec (readme.io).
    List of tags.
    Required scopes:
    + **read**

    Args:
        page: Page number of tags list.
        limit: Number of results in a page.

    Docs: https://lolzteam.readme.io/reference/tagslist
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/tags/list"
    __returning__ = passthrough

    page: int | None = None
    limit: int | None = None


# Source: official OpenAPI spec, operationId "Tags.Popular".
class TagsPopular(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Popular Tags.
    Sourced from the official OpenAPI spec (readme.io).
    List of popular tags (no pagination).
    Required scopes:
    + **read**

    Docs: https://lolzteam.readme.io/reference/tagspopular
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/tags"
    __returning__ = passthrough
