"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.methods.base import BaseMethod, passthrough
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "Posts.Comments.Get".
class PostsCommentsGet(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Post Comments.
    Sourced from the official OpenAPI spec (readme.io).
    List of post comments in a thread.
    Required scopes:
    + **read**

    Args:
        post_id: Id of a post.
        post_comment_id: Id of a post comment.
        before: The time in milliseconds (e.g. 1652177794083) before last comment date.
        before_comment: Comment id to get older comments.

    Docs: https://lolzteam.readme.io/reference/postscommentsget
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/posts/comments"
    __returning__ = passthrough

    post_id: int | None = None
    post_comment_id: int | None = None
    before: int | None = None
    before_comment: int | None = None
