"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.methods.base import BaseMethod
from pylzt.models.forum import UptimeHeartbeatResponse, UptimeInfoResponse
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "Uptime.Heartbeat".
class UptimeHeartbeat(BaseMethod[UptimeHeartbeatResponse]):
    """Generated by forge — DO NOT EDIT. Get Status Page Heartbeats & Uptime.
    Sourced from the official OpenAPI spec (readme.io).
    Get heartbeat and uptime.

    Docs: https://lolzteam.readme.io/reference/uptimeheartbeat
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/api/status-page/heartbeat/lzt"
    __returning__ = UptimeHeartbeatResponse


# Source: official OpenAPI spec, operationId "Uptime.Info".
class UptimeInfo(BaseMethod[UptimeInfoResponse]):
    """Generated by forge — DO NOT EDIT. Get Status Page Info.
    Sourced from the official OpenAPI spec (readme.io).
    Provide data for published public status pages.

    Docs: https://lolzteam.readme.io/reference/uptimeinfo
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/api/status-page/lzt"
    __returning__ = UptimeInfoResponse
