"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.enums.forum import Order
from pylzt.methods.base import BaseMethod, passthrough
from pylzt.models.forum import PagesListResponse
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "Pages.Get".
class PagesGet(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Page.
    Sourced from the official OpenAPI spec (readme.io).
    Detail information of a page.
    Required scopes:
    + **read**

    Args:
        page_id: Id of page.

    Docs: https://lolzteam.readme.io/reference/pagesget
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/pages/{page_id}"
    __returning__ = passthrough

    page_id: int


# Source: official OpenAPI spec, operationId "Pages.List".
class PagesList(BaseMethod[PagesListResponse]):
    """Generated by forge — DO NOT EDIT. Get Pages.
    Sourced from the official OpenAPI spec (readme.io).
    List of all pages in the system.
    Required scopes:
    + **read**

    Args:
        parent_page_id: Id of parent page. If exists, filter pages that are direct children of that page.
        order: Ordering of pages.

    Docs: https://lolzteam.readme.io/reference/pageslist
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/pages"
    __returning__ = PagesListResponse

    parent_page_id: int | None = None
    order: Order | None = None
