"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.methods.base import BaseMethod
from pylzt.models.forum import LinkForum, LinksListResponse
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "Links.Get".
class LinksGet(BaseMethod[LinkForum]):
    """Generated by forge — DO NOT EDIT. Get Link Forum.
    Sourced from the official OpenAPI spec (readme.io).
    Detail information of a link forum.
    Required scopes:
    + **read**

    Args:
        link_id: Id of link forum.

    Docs: https://lolzteam.readme.io/reference/linksget
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/link-forums/{link_id}"
    __returning__ = LinkForum
    __unwrap__ = "link-forum"

    link_id: int


# Source: official OpenAPI spec, operationId "Links.List".
class LinksList(BaseMethod[LinksListResponse]):
    """Generated by forge — DO NOT EDIT. Get Links Forum.
    Sourced from the official OpenAPI spec (readme.io).
    List of all link forums.
    Required scopes:
    + **read**

    Docs: https://lolzteam.readme.io/reference/linkslist
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/link-forums"
    __returning__ = LinksListResponse
