"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.enums.forum import MessageState
from pylzt.methods.base import BaseMethod, passthrough
from pylzt.models.forum import Comment, ForumStatusMessageResponse
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "Posts.Comments.Create".
class PostsCommentsCreate(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Create Post Comment.
    Sourced from the official OpenAPI spec (readme.io).
    Create a post comment.
    Required scopes:
    + **post**

    Args:
        post_id: Id of post.
        comment_body: Content of the a post comment.

    Docs: https://lolzteam.readme.io/reference/postscommentscreate
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/posts/comments"
    __returning__ = passthrough

    post_id: int
    comment_body: str


# Source: official OpenAPI spec, operationId "Posts.Comments.Delete".
class PostsCommentsDelete(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Delete Post Comment.
    Sourced from the official OpenAPI spec (readme.io).
    Delete a post comment.
    Required scopes:
    + **post**

    Args:
        post_comment_id: Id of post comment.
        reason: Reason of a post comment removal.

    Docs: https://lolzteam.readme.io/reference/postscommentsdelete
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.DELETE
    __url__ = "/posts/comments"
    __returning__ = ForumStatusMessageResponse

    post_comment_id: int
    reason: str | None = None


# Source: official OpenAPI spec, operationId "Posts.Comments.Edit".
class PostsCommentsEdit(BaseMethod[Comment]):
    """Generated by forge — DO NOT EDIT. Edit Post Comment.
    Sourced from the official OpenAPI spec (readme.io).
    Edit a post comment.
    Required scopes:
    + **post**

    Args:
        post_comment_id: Id of post.
        comment_body: Content of the new post comment.

    Docs: https://lolzteam.readme.io/reference/postscommentsedit
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.PUT
    __url__ = "/posts/comments"
    __returning__ = Comment
    __unwrap__ = "comment"

    post_comment_id: int
    comment_body: str
    message_state: MessageState | None = None


# Source: official OpenAPI spec, operationId "Posts.Comments.Get".
class PostsCommentsGet(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Post Comments.
    Sourced from the official OpenAPI spec (readme.io).
    List of post comments in a thread.
    Required scopes:
    + **read**

    Args:
        post_id: Id of a post.
        post_comment_id: Id of a post comment.
        before: The time in milliseconds (e.g. 1652177794083) before last comment date.
        before_comment: Comment id to get older comments.

    Docs: https://lolzteam.readme.io/reference/postscommentsget
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/posts/comments"
    __returning__ = passthrough

    post_id: int | None = None
    post_comment_id: int | None = None
    before: int | None = None
    before_comment: int | None = None
