"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from typing import Any

from pylzt.enums.forum import (
    AllowInviteGroup,
    AllowPostProfile,
    AllowReceiveNewsFeed,
    AllowSendPersonalConversation,
    AllowViewProfile,
    ClaimState,
    ContentType,
    FieldsInclude,
    Gender,
    LikeType,
    Order,
    Type,
)
from pylzt.media import Media
from pylzt.methods.base import BaseMethod, passthrough
from pylzt.models.forum import (
    ForumStatusMessageResponse,
    User,
    UsersClaimsResponse,
    UsersIgnoredUser,
    UsersLikesResponse,
    UsersListResponse,
    UsersSAResetResponse,
    UsersSecretAnswerTypesData,
    UsersTrophiesResponse,
)
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "Users.Avatar.Crop".
class UsersAvatarCrop(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Crop Avatar.
    Sourced from the official OpenAPI spec (readme.io).
    Crop avatar for a user.
    Required scopes:
    + **post**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.
        x: The starting point of the selection by width. Default value - 0
        y: The starting point of the selection by height. Default value - 0
        crop: Selection size.

    Docs: https://lolzteam.readme.io/reference/usersavatarcrop
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/users/{user_id}/avatar/crop"
    __returning__ = passthrough

    user_id: str
    x: int | None = None
    y: int | None = None
    crop: int | None = None


# Source: official OpenAPI spec, operationId "Users.Avatar.Delete".
class UsersAvatarDelete(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Delete Avatar.
    Sourced from the official OpenAPI spec (readme.io).
    Delete avatar for a user.
    Required scopes:
    + **post**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.

    Docs: https://lolzteam.readme.io/reference/usersavatardelete
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.DELETE
    __url__ = "/users/{user_id}/avatar"
    __returning__ = ForumStatusMessageResponse

    user_id: str


# Source: official OpenAPI spec, operationId "Users.Avatar.Upload".
class UsersAvatarUpload(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Upload Avatar.
    Sourced from the official OpenAPI spec (readme.io).
    Upload avatar for a user.
    Required scopes:
    + **post**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.
        avatar: Binary data of the avatar.
        x: The starting point of the selection by width. Default value - 0
        y: The starting point of the selection by height. Default value - 0
        crop: Selection size.

    Docs: https://lolzteam.readme.io/reference/usersavatarupload
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/users/{user_id}/avatar"
    __returning__ = passthrough

    user_id: str
    avatar: Media
    x: int | None = None
    y: int | None = None
    crop: int | None = None


# Source: official OpenAPI spec, operationId "Users.Background.Crop".
class UsersBackgroundCrop(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Crop Background.
    Sourced from the official OpenAPI spec (readme.io).
    Crop background for a user.
    Required scopes:
    + **post**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.
        x: The starting point of the selection by width. Default value - 0
        y: The starting point of the selection by height. Default value - 0
        crop: Selection size.

    Docs: https://lolzteam.readme.io/reference/usersbackgroundcrop
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/users/{user_id}/background/crop"
    __returning__ = passthrough

    user_id: str
    x: int | None = None
    y: int | None = None
    crop: int | None = None


# Source: official OpenAPI spec, operationId "Users.Background.Delete".
class UsersBackgroundDelete(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Delete Background.
    Sourced from the official OpenAPI spec (readme.io).
    Delete background for a user.
    Required scopes:
    + **post**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.

    Docs: https://lolzteam.readme.io/reference/usersbackgrounddelete
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.DELETE
    __url__ = "/users/{user_id}/background"
    __returning__ = ForumStatusMessageResponse

    user_id: str


# Source: official OpenAPI spec, operationId "Users.Background.Upload".
class UsersBackgroundUpload(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Upload Background.
    Sourced from the official OpenAPI spec (readme.io).
    Upload background for a user.
    Required scopes:
    + **post**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.
        background: Binary data of the background. Background image must be 1920x1080 pixels
        x: The starting point of the selection by width. Default value - 0
        y: The starting point of the selection by height. Default value - 0
        crop: Selection size.

    Docs: https://lolzteam.readme.io/reference/usersbackgroundupload
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/users/{user_id}/background"
    __returning__ = passthrough

    user_id: str
    background: Media
    x: int | None = None
    y: int | None = None
    crop: int | None = None


# Source: official OpenAPI spec, operationId "Users.Claims".
class UsersClaims(BaseMethod[UsersClaimsResponse]):
    """Generated by forge — DO NOT EDIT. Get User Claims.
    Sourced from the official OpenAPI spec (readme.io).
    Get user claims.
    Required scopes:
    + **read**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.
        type: Filter claims by their type.
        claim_state: Filter claims by their state.

    Docs: https://lolzteam.readme.io/reference/usersclaims
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/users/{user_id}/claims"
    __returning__ = UsersClaimsResponse

    user_id: str
    type: Type | None = None
    claim_state: ClaimState | None = None


# Source: official OpenAPI spec, operationId "Users.Contents".
class UsersContents(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Contents.
    Sourced from the official OpenAPI spec (readme.io).
    List of contents created by user (with pagination).
    Required scopes:
    + **read**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.
        page: Page number of contents.
        limit: Number of contents in a page.

    Docs: https://lolzteam.readme.io/reference/userscontents
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/users/{user_id}/timeline"
    __returning__ = passthrough

    user_id: str
    page: int | None = None
    limit: int | None = None


# Source: official OpenAPI spec, operationId "Users.Edit".
class UsersEdit(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Edit User.
    Sourced from the official OpenAPI spec (readme.io).
    Edit a user.
    Required scopes:
    + **post**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.
        username: New username.
        user_title: New custom title of the user.
        display_group_id: Id of the group you want to display.
        display_icon_group_id: Id of the icon group you want to display.
        display_banner_id: Id of the banner you want to display.
        conv_welcome_message: This message is shown when someone wants to write to you.
        user_dob_day: Your date of birth (day).
        user_dob_month: Your date of birth (month).
        user_dob_year: Your date of birth (year).
        secret_answer: Secret answer.
        secret_answer_type: Secret answer type.
        short_link: Profile short link.
        language_id: User interface language ID.
        gender: User gender.
        timezone: User timezone.
        receive_admin_email: Whether to receive admin emails.
        activity_visible: Whether user activity is visible.
        show_dob_date: Show date of birth (day and month).
        show_dob_year: Show year of birth.
        hide_username_change_logs: Hide username change logs.
        allow_view_profile: Who can view your profile.
        allow_post_profile: Who can post on your profile.
        allow_send_personal_conversation: Who can send you personal conversations.
        allow_invite_group: Who can invite you to groups.
        allow_receive_news_feed: Who can see your news feed.
        alert: Alert settings.
        fields: Custom user profile fields.

    Docs: https://lolzteam.readme.io/reference/usersedit
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.PUT
    __url__ = "/users/{user_id}"
    __returning__ = ForumStatusMessageResponse

    user_id: str
    username: str | None = None
    user_title: str | None = None
    display_group_id: int | None = None
    display_icon_group_id: int | None = None
    display_banner_id: int | None = None
    conv_welcome_message: str | None = None
    user_dob_day: int | None = None
    user_dob_month: int | None = None
    user_dob_year: int | None = None
    secret_answer: str | None = None
    secret_answer_type: int | None = None
    short_link: str | None = None
    language_id: int | None = None
    gender: Gender | None = None
    timezone: str | None = None
    receive_admin_email: bool | None = None
    activity_visible: bool | None = None
    show_dob_date: bool | None = None
    show_dob_year: bool | None = None
    hide_username_change_logs: bool | None = None
    allow_view_profile: AllowViewProfile | None = None
    allow_post_profile: AllowPostProfile | None = None
    allow_send_personal_conversation: AllowSendPersonalConversation | None = None
    allow_invite_group: AllowInviteGroup | None = None
    allow_receive_news_feed: AllowReceiveNewsFeed | None = None
    alert: dict[str, Any] | None = None
    fields: dict[str, Any] | None = None


# Source: official OpenAPI spec, operationId "Users.Fields".
class UsersFields(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get User Fields.
    Sourced from the official OpenAPI spec (readme.io).
    List of user fields.
    Required scopes:
    + **read**

    Docs: https://lolzteam.readme.io/reference/usersfields
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/users/fields"
    __returning__ = passthrough


# Source: official OpenAPI spec, operationId "Users.Find".
class UsersFind(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Find Users.
    Sourced from the official OpenAPI spec (readme.io).
    List of users filtered by username, email or custom fields.
    Required scopes:
    + **read**

    Args:
        username: Username to filter. Usernames start with the query will be returned.
        custom_fields: Custom fields to filter. Example: **custom_fields[telegram]=telegramLogin**.
        fields_include: List of fields to include.

    Docs: https://lolzteam.readme.io/reference/usersfind
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/users/find"
    __returning__ = passthrough

    username: str | None = None
    custom_fields: dict[str, Any] | None = None
    fields_include: tuple[FieldsInclude, ...] | None = None


# Source: official OpenAPI spec, operationId "Users.Follow".
class UsersFollow(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Follow User.
    Sourced from the official OpenAPI spec (readme.io).
    Follow a user.
    Required scopes:
    + **post**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.

    Docs: https://lolzteam.readme.io/reference/usersfollow
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/users/{user_id}/followers"
    __returning__ = ForumStatusMessageResponse

    user_id: str


# Source: official OpenAPI spec, operationId "Users.Followers".
class UsersFollowers(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get User Followers.
    Sourced from the official OpenAPI spec (readme.io).
    List of a user's followers.
    Required scopes:
    + **read**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.
        order: Ordering of followers.
        page: Page number of followers.
        limit: Number of followers in a page.

    Docs: https://lolzteam.readme.io/reference/usersfollowers
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/users/{user_id}/followers"
    __returning__ = passthrough

    user_id: str
    order: Order | None = None
    page: int | None = None
    limit: int | None = None


# Source: official OpenAPI spec, operationId "Users.Followings".
class UsersFollowings(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Followed Users By User.
    Sourced from the official OpenAPI spec (readme.io).
    List of users whom are followed by a user.
    Required scopes:
    + **read**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.
        order: Ordering of users.
        page: Page number of users.
        limit: Number of users in a page.

    Docs: https://lolzteam.readme.io/reference/usersfollowings
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/users/{user_id}/followings"
    __returning__ = passthrough

    user_id: str
    order: Order | None = None
    page: int | None = None
    limit: int | None = None


# Source: official OpenAPI spec, operationId "Users.Get".
class UsersGet(BaseMethod[User]):
    """Generated by forge — DO NOT EDIT. Get User.
    Sourced from the official OpenAPI spec (readme.io).
    Detail information of a user.
    Required scopes:
    + **read**
    + **basic**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.
        fields_include: List of fields to include.

    Docs: https://lolzteam.readme.io/reference/usersget
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/users/{user_id}"
    __returning__ = User
    __unwrap__ = "user"

    user_id: str
    fields_include: tuple[FieldsInclude, ...] | None = None


# Source: official OpenAPI spec, operationId "Users.Ignore".
class UsersIgnore(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Ignore User.
    Sourced from the official OpenAPI spec (readme.io).
    Ignore a user.
    Required scopes:
    + **post**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.

    Docs: https://lolzteam.readme.io/reference/usersignore
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/users/{user_id}/ignore"
    __returning__ = ForumStatusMessageResponse

    user_id: str


# Source: official OpenAPI spec, operationId "Users.IgnoreEdit".
class UsersIgnoreEdit(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Edit Ignoring Options.
    Sourced from the official OpenAPI spec (readme.io).
    Edit ignoring options.
    Required scopes:
    + **post**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.
        ignore_conversations: Ignore user's conversations.
        ignore_content: Ignore user's content.
        restrict_view_profile: Restrict user from viewing your profile.

    Docs: https://lolzteam.readme.io/reference/usersignoreedit
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.PUT
    __url__ = "/users/{user_id}/ignore"
    __returning__ = ForumStatusMessageResponse

    user_id: str
    ignore_conversations: bool | None = None
    ignore_content: bool | None = None
    restrict_view_profile: bool | None = None


# Source: official OpenAPI spec, operationId "Users.Ignored".
class UsersIgnored(BaseMethod[list[UsersIgnoredUser]]):
    """Generated by forge — DO NOT EDIT. Get Ignored Users.
    Sourced from the official OpenAPI spec (readme.io).
    List of ignored users of current user.
    Required scopes:
    + **read**

    Args:
        total: If included in the request, only the user count is returned as **users_total**.

    Docs: https://lolzteam.readme.io/reference/usersignored
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/users/ignored"
    __returning__ = UsersIgnoredUser
    __unwrap__ = "users"

    total: bool | None = None


# Source: official OpenAPI spec, operationId "Users.Likes".
class UsersLikes(BaseMethod[UsersLikesResponse]):
    """Generated by forge — DO NOT EDIT. Get User Likes.
    Sourced from the official OpenAPI spec (readme.io).
    Get information about user likes.
    Required scopes:
    + **read**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.
        node_id: Filter by forum section.
        like_type: Like type.
        type: Likes type.
        page: Page number.
        content_type: Content type.
        search_user_id: Get only likes from specified user.
        stats: Show weekly statistics.

    Docs: https://lolzteam.readme.io/reference/userslikes
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/users/{user_id}/likes"
    __returning__ = UsersLikesResponse

    user_id: str
    node_id: int | None = None
    like_type: LikeType | None = None
    type: Type | None = None
    page: int | None = None
    content_type: ContentType | None = None
    search_user_id: int | None = None
    stats: bool | None = None


# Source: official OpenAPI spec, operationId "Users.List".
class UsersList(BaseMethod[UsersListResponse]):
    """Generated by forge — DO NOT EDIT. Get Users.
    Sourced from the official OpenAPI spec (readme.io).
    List of users (with pagination).
    Required scopes:
    + **read**

    Args:
        page: Page number of users.
        limit: Number of users in a page.
        fields_include: List of fields to include.

    Docs: https://lolzteam.readme.io/reference/userslist
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/users"
    __returning__ = UsersListResponse

    page: int | None = None
    limit: int | None = None
    fields_include: tuple[FieldsInclude, ...] | None = None


# Source: official OpenAPI spec, operationId "Users.SA.CancelReset".
class UsersSACancelReset(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Cancel Secret Answer Reset.
    Sourced from the official OpenAPI spec (readme.io).
    Cancel a pending secret answer reset request for the account.
    Required scopes:
    + **post**

    Docs: https://lolzteam.readme.io/reference/userssacancelreset
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.DELETE
    __url__ = "/account/secret-answer/reset"
    __returning__ = ForumStatusMessageResponse


# Source: official OpenAPI spec, operationId "Users.SA.Reset".
class UsersSAReset(BaseMethod[UsersSAResetResponse]):
    """Generated by forge — DO NOT EDIT. Reset Secret Answer.
    Sourced from the official OpenAPI spec (readme.io).
    Request a reset of the secret answer for the account.
    Required scopes:
    + **post**

    Docs: https://lolzteam.readme.io/reference/userssareset
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/account/secret-answer/reset"
    __returning__ = UsersSAResetResponse


# Source: official OpenAPI spec, operationId "Users.SecretAnswerTypes".
class UsersSecretAnswerTypes(BaseMethod[list[UsersSecretAnswerTypesData]]):
    """Generated by forge — DO NOT EDIT. Get Secret Answer Types.
    Sourced from the official OpenAPI spec (readme.io).
    Get available secret answer types for user account security.
    Required scopes:
    + **read**

    Docs: https://lolzteam.readme.io/reference/userssecretanswertypes
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/users/secret-answer/types"
    __returning__ = UsersSecretAnswerTypesData
    __unwrap__ = "data"


# Source: official OpenAPI spec, operationId "Users.Trophies".
class UsersTrophies(BaseMethod[UsersTrophiesResponse]):
    """Generated by forge — DO NOT EDIT. Get Trophies.
    Sourced from the official OpenAPI spec (readme.io).
    List of user trophies.
    Required scopes:
    + **read**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.

    Docs: https://lolzteam.readme.io/reference/userstrophies
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/users/{user_id}/trophies"
    __returning__ = UsersTrophiesResponse

    user_id: str


# Source: official OpenAPI spec, operationId "Users.Unfollow".
class UsersUnfollow(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Unfollow User.
    Sourced from the official OpenAPI spec (readme.io).
    Unfollow a user.
    Required scopes:
    + **post**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.

    Docs: https://lolzteam.readme.io/reference/usersunfollow
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.DELETE
    __url__ = "/users/{user_id}/followers"
    __returning__ = ForumStatusMessageResponse

    user_id: str


# Source: official OpenAPI spec, operationId "Users.Unignore".
class UsersUnignore(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Unignore User.
    Sourced from the official OpenAPI spec (readme.io).
    Stop ignoring a user.
    Required scopes:
    + **post**

    Args:
        user_id: User ID. > You can use shortlink `me` to interact with your profile.

    Docs: https://lolzteam.readme.io/reference/usersunignore
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.DELETE
    __url__ = "/users/{user_id}/ignore"
    __returning__ = ForumStatusMessageResponse

    user_id: str
