"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.enums.forum import Order
from pylzt.methods.base import BaseMethod, passthrough
from pylzt.models.forum import CategoriesListResponse
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "Categories.Get".
class CategoriesGet(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Category.
    Sourced from the official OpenAPI spec (readme.io).
    Detail information of a category.
    Required scopes:
    + **read**

    Args:
        category_id: Id of category.

    Docs: https://lolzteam.readme.io/reference/categoriesget
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/categories/{category_id}"
    __returning__ = passthrough

    category_id: int


# Source: official OpenAPI spec, operationId "Categories.List".
class CategoriesList(BaseMethod[CategoriesListResponse]):
    """Generated by forge — DO NOT EDIT. Get Categories.
    Sourced from the official OpenAPI spec (readme.io).
    List of all categories in the system.
    Required scopes:
    + **read**

    Args:
        parent_category_id: Id of parent category. If exists, filter categories that are direct children of that category.
        parent_forum_id: Id of parent forum. If exists, filter categories that are direct children of that forum.
        order: Ordering of categories.

    Docs: https://lolzteam.readme.io/reference/categorieslist
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/categories"
    __returning__ = CategoriesListResponse

    parent_category_id: int | None = None
    parent_forum_id: int | None = None
    order: Order | None = None
