"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.enums.forum import Order
from pylzt.methods.base import BaseMethod, passthrough
from pylzt.models.forum import ForumStatusMessageResponse, Post
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "Posts.Comments.ReportReasons".
class PostsCommentsReportReasons(BaseMethod[list[str]]):
    """Generated by forge — DO NOT EDIT. Get Post Comment Report Reasons.
    Sourced from the official OpenAPI spec (readme.io).
    Get a post comment report reasons.
    Required scopes:
    + **read**

    Args:
        post_comment_id: Id of post comment.

    Docs: https://lolzteam.readme.io/reference/postscommentsreportreasons
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/posts/comments/report"
    __returning__ = passthrough
    __unwrap__ = "reasons"

    post_comment_id: int


# Source: official OpenAPI spec, operationId "Posts.Get".
class PostsGet(BaseMethod[Post]):
    """Generated by forge — DO NOT EDIT. Get Post.
    Sourced from the official OpenAPI spec (readme.io).
    Detail information of a post.
    Required scopes:
    + **read**

    Args:
        post_id: Id of post.

    Docs: https://lolzteam.readme.io/reference/postsget
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/posts/{post_id}"
    __returning__ = Post
    __unwrap__ = "post"

    post_id: int


# Source: official OpenAPI spec, operationId "Posts.List".
class PostsList(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Posts.
    Sourced from the official OpenAPI spec (readme.io).
    List of posts in a thread (with pagination).
    Required scopes:
    + **read**

    Args:
        thread_id: Id of the containing thread.
        page_of_post_id: Id of a post, posts that are in the same page with the specified post will be returned. **thread_id** may be skipped.
        page: Page number of posts.
        limit: Number of posts in a page.
        order: Ordering of posts.

    Docs: https://lolzteam.readme.io/reference/postslist
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/posts"
    __returning__ = passthrough

    thread_id: int | None = None
    page_of_post_id: int | None = None
    page: int | None = None
    limit: int | None = None
    order: Order | None = None


# Source: official OpenAPI spec, operationId "Posts.ReportReasons".
class PostsReportReasons(BaseMethod[list[str]]):
    """Generated by forge — DO NOT EDIT. Get Post Report Reasons.
    Sourced from the official OpenAPI spec (readme.io).
    Get post report reasons.
    Required scopes:
    + **read**

    Args:
        post_id: Id of post.

    Docs: https://lolzteam.readme.io/reference/postsreportreasons
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/posts/{post_id}/report"
    __returning__ = passthrough
    __unwrap__ = "reasons"

    post_id: int


# Source: official OpenAPI spec, operationId "Posts.Unlike".
class PostsUnlike(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Unlike Post.
    Sourced from the official OpenAPI spec (readme.io).
    Unlike a post.
    Required scopes:
    + **post**

    Args:
        post_id: Id of post.

    Docs: https://lolzteam.readme.io/reference/postsunlike
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.DELETE
    __url__ = "/posts/{post_id}/likes"
    __returning__ = ForumStatusMessageResponse

    post_id: int
