"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.enums.forum import MessageState
from pylzt.methods.base import BaseMethod, passthrough
from pylzt.models.forum import ForumStatusMessageResponse, ProfilePostsCommentsEditComment
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "ProfilePosts.Comments.Create".
class ProfilePostsCommentsCreate(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Create Profile Post Comment.
    Sourced from the official OpenAPI spec (readme.io).
    Create a new profile post comment.
    Required scopes:
    + **post**

    Args:
        profile_post_id: Id of profile post.
        comment_body: Content of the new profile post comment.

    Docs: https://lolzteam.readme.io/reference/profilepostscommentscreate
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/profile-posts/comments"
    __returning__ = passthrough

    profile_post_id: int
    comment_body: str


# Source: official OpenAPI spec, operationId "ProfilePosts.Comments.Delete".
class ProfilePostsCommentsDelete(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Delete Profile Post Comment.
    Sourced from the official OpenAPI spec (readme.io).
    Delete a profile post comment.
    Required scopes:
    + **post**

    Args:
        comment_id: Id of profile post comment.

    Docs: https://lolzteam.readme.io/reference/profilepostscommentsdelete
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.DELETE
    __url__ = "/profile-posts/comments"
    __returning__ = ForumStatusMessageResponse

    comment_id: int


# Source: official OpenAPI spec, operationId "ProfilePosts.Comments.Edit".
class ProfilePostsCommentsEdit(BaseMethod[ProfilePostsCommentsEditComment]):
    """Generated by forge — DO NOT EDIT. Edit Profile Post Comment.
    Sourced from the official OpenAPI spec (readme.io).
    Edit a profile post comment.
    Required scopes:
    + **post**

    Args:
        comment_id: Id of profile post comment.
        comment_body: New content for the profile post comment.

    Docs: https://lolzteam.readme.io/reference/profilepostscommentsedit
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.PUT
    __url__ = "/profile-posts/comments"
    __returning__ = ProfilePostsCommentsEditComment
    __unwrap__ = "comment"

    comment_id: int
    comment_body: str
    message_state: MessageState | None = None


# Source: official OpenAPI spec, operationId "ProfilePosts.Comments.Get".
class ProfilePostsCommentsGet(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Profile Post Comment.
    Sourced from the official OpenAPI spec (readme.io).
    Detail information of a profile post comment.
    Required scopes:
    + **read**

    Args:
        profile_post_id: Id of profile post.
        comment_id: Id of profile post comment.

    Docs: https://lolzteam.readme.io/reference/profilepostscommentsget
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/profile-posts/{profile_post_id}/comments/{comment_id}"
    __returning__ = passthrough

    profile_post_id: int
    comment_id: int


# Source: official OpenAPI spec, operationId "ProfilePosts.Comments.List".
class ProfilePostsCommentsList(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Profile Post Comments.
    Sourced from the official OpenAPI spec (readme.io).
    List of comments of a profile post.
    Required scopes:
    + **read**

    Args:
        profile_post_id: ID of profile post.
        comment_id: ID of a profile post comment.
        page_of_comment_id: ID of a profile post comment, comments that are in the same page with the specified comment will be returned.
        before: Date to get older comments. Please note that this entry point does not support the page parameter but it still does support **limit**.
        limit: Number of profile posts in a page.

    Docs: https://lolzteam.readme.io/reference/profilepostscommentslist
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/profile-posts/comments"
    __returning__ = passthrough

    profile_post_id: int | None = None
    comment_id: int | None = None
    page_of_comment_id: int | None = None
    before: int | None = None
    limit: int | None = None


# Source: official OpenAPI spec, operationId "ProfilePosts.Comments.Report".
class ProfilePostsCommentsReport(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Report a Profile Post Comment.
    Sourced from the official OpenAPI spec (readme.io).
    Report a profile post comment.
    Required scopes:
    + **post**

    Args:
        message: Reason of the report.
        comment_id: Id of profile post comment.

    Docs: https://lolzteam.readme.io/reference/profilepostscommentsreport
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/profile-posts/comments/report"
    __returning__ = ForumStatusMessageResponse

    message: str
    comment_id: int


# Source: official OpenAPI spec, operationId "ProfilePosts.Comments.ReportReasons".
class ProfilePostsCommentsReportReasons(BaseMethod[list[str]]):
    """Generated by forge — DO NOT EDIT. Get Profile Post Comment Report Reasons.
    Sourced from the official OpenAPI spec (readme.io).
    Get profile post comment report reasons.
    Required scopes:
    + **read**

    Args:
        comment_id: Id of profile post comment.

    Docs: https://lolzteam.readme.io/reference/profilepostscommentsreportreasons
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/profile-posts/comments/report"
    __returning__ = passthrough
    __unwrap__ = "reasons"

    comment_id: int
