"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.methods.base import BaseMethod, passthrough
from pylzt.models.forum import ForumStatusMessageResponse
from pylzt.types import ApiTarget, HttpMethod, RateClass


# Source: official OpenAPI spec, operationId "Notifications.Get".
class NotificationsGet(BaseMethod[str]):
    """Generated by forge — DO NOT EDIT. Get Notification.
    Sourced from the official OpenAPI spec (readme.io).
    Get associated content of notification. The response depends on the content type.
    Required scopes:
    + **read**

    Args:
        notification_id: Id of notification.

    Docs: https://lolzteam.readme.io/reference/notificationsget
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.GET
    __url__ = "/notifications/{notification_id}/content"
    __returning__ = passthrough

    notification_id: int


# Source: official OpenAPI spec, operationId "Notifications.Read".
class NotificationsRead(BaseMethod[ForumStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Mark Notification Read.
    Sourced from the official OpenAPI spec (readme.io).
    Mark single notification or all existing notifications read.
    Required scopes:
    + **post**

    Args:
        notification_id: If notification_id is omitted, it's mark all existing notifications as read.

    Docs: https://lolzteam.readme.io/reference/notificationsread
    """

    __api__ = ApiTarget.FORUM
    __rate_class__ = RateClass.FORUM
    __http_method__ = HttpMethod.POST
    __url__ = "/notifications/read"
    __returning__ = ForumStatusMessageResponse

    notification_id: int | None = None
