"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.methods.base import BaseMethod
from pylzt.models.market import MarketStatusMessageResponse, Proxy
from pylzt.types import HttpMethod


# Source: official OpenAPI spec, operationId "Proxy.Add".
class ProxyAdd(BaseMethod[MarketStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Add Proxy.
    Sourced from the official OpenAPI spec (readme.io).
    Add single proxy or proxy list.
    To add single proxy use this parameters:
    + **proxy_ip** (required) - proxy ip or host
    + **proxy_port** (required) - proxy port
    + **proxy_user** (optional) - proxy username
    + **proxy_pass** (optional) - proxy password
    To add proxy list use this parameters:
    + **proxy_row** (required) - proxy list in String format ip:port:user:pass. Each proxy must be start with new line (use \n separator)

    Args:
        proxy_ip: Proxy ip or host. Required if **proxy_row** is not specified.
        proxy_port: Proxy port. Required if **proxy_row** is not specified.
        proxy_user: Proxy username. Required if **proxy_row** is not specified.
        proxy_pass: Proxy password. Required if **proxy_row** is not specified.
        proxy_row: Proxy list in String format ip:port:user:pass. Each proxy must be start with new line (use \r\n separator)

    Docs: https://lzt-market.readme.io/reference/proxyadd
    """

    __http_method__ = HttpMethod.POST
    __url__ = "/proxy"
    __returning__ = MarketStatusMessageResponse

    proxy_ip: str | None = None
    proxy_port: int | None = None
    proxy_user: str | None = None
    proxy_pass: str | None = None
    proxy_row: str | None = None


# Source: official OpenAPI spec, operationId "Proxy.Delete".
class ProxyDelete(BaseMethod[MarketStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Delete Proxy.
    Sourced from the official OpenAPI spec (readme.io).
    Delete single or all proxies.

    Args:
        proxy_id: Id of an existing proxy.
        delete_all: Delete all proxies.

    Docs: https://lzt-market.readme.io/reference/proxydelete
    """

    __http_method__ = HttpMethod.DELETE
    __url__ = "/proxy"
    __returning__ = MarketStatusMessageResponse

    proxy_id: int | None = None
    delete_all: bool | None = None


# Source: official OpenAPI spec, operationId "Proxy.Get".
class ProxyGet(BaseMethod[list[Proxy]]):
    """Generated by forge — DO NOT EDIT. Get Proxy.
    Sourced from the official OpenAPI spec (readme.io).
    Gets your proxy list.

    Docs: https://lzt-market.readme.io/reference/proxyget
    """

    __http_method__ = HttpMethod.GET
    __url__ = "/proxy"
    __returning__ = Proxy
    __unwrap__ = "proxies"
