"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from typing import Any

from pylzt.enums.market import HoldLengthOption
from pylzt.methods.base import BaseMethod, passthrough
from pylzt.models.market import (
    MarketStatusMessageResponse,
    PaymentsCurrencyResponse,
    PaymentsFeeResponse,
    System,
)
from pylzt.types import Currency, HttpMethod


# Source: official OpenAPI spec, operationId "AutoPayments.Delete".
class AutoPaymentsDelete(BaseMethod[MarketStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Delete Auto Payment.
    Sourced from the official OpenAPI spec (readme.io).
    Deletes an auto payment.
    Required scopes:
    + **payment**

    Args:
        auto_payment_id: Auto payment ID.

    Docs: https://lzt-market.readme.io/reference/autopaymentsdelete
    """

    __http_method__ = HttpMethod.DELETE
    __url__ = "/auto-payment"
    __returning__ = MarketStatusMessageResponse

    auto_payment_id: int


# Source: official OpenAPI spec, operationId "AutoPayments.List".
class AutoPaymentsList(BaseMethod[dict[str, Any]]):
    """Generated by forge — DO NOT EDIT. Get Auto Payments.
    Sourced from the official OpenAPI spec (readme.io).
    Get auto payments list.
    Required scopes:
    + **payment**

    Docs: https://lzt-market.readme.io/reference/autopaymentslist
    """

    __http_method__ = HttpMethod.GET
    __url__ = "/auto-payments"
    __returning__ = passthrough
    __unwrap__ = "payments"


# Source: official OpenAPI spec, operationId "Payments.Cancel".
class PaymentsCancel(BaseMethod[MarketStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Cancel Transfer.
    Sourced from the official OpenAPI spec (readme.io).
    Cancels a transfer with a hold that was sent to your account.
    Required scopes:
    + **payment**

    Args:
        payment_id: Payment id.

    Docs: https://lzt-market.readme.io/reference/paymentscancel
    """

    __http_method__ = HttpMethod.POST
    __url__ = "/balance/transfer/cancel"
    __returning__ = MarketStatusMessageResponse

    payment_id: int


# Source: official OpenAPI spec, operationId "Payments.Currency".
class PaymentsCurrency(BaseMethod[PaymentsCurrencyResponse]):
    """Generated by forge — DO NOT EDIT. Get Currency.
    Sourced from the official OpenAPI spec (readme.io).
    Get currency list.

    Docs: https://lzt-market.readme.io/reference/paymentscurrency
    """

    __http_method__ = HttpMethod.GET
    __url__ = "/currency"
    __returning__ = PaymentsCurrencyResponse


# Source: official OpenAPI spec, operationId "Payments.Fee".
class PaymentsFee(BaseMethod[PaymentsFeeResponse]):
    """Generated by forge — DO NOT EDIT. Check Transfer Fee.
    Sourced from the official OpenAPI spec (readme.io).
    Get transfer limits and get fee amount for transfer.
    Required scopes:
    + **payment**

    Args:
        currency: Currencн.
        amount: Amount you want to send in your currency.

    Docs: https://lzt-market.readme.io/reference/paymentsfee
    """

    __http_method__ = HttpMethod.GET
    __url__ = "/balance/transfer/fee"
    __returning__ = PaymentsFeeResponse

    currency: Currency
    amount: float | None = None


# Source: official OpenAPI spec, operationId "Payments.Payout".
class PaymentsPayout(BaseMethod[MarketStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Create Payout.
    Sourced from the official OpenAPI spec (readme.io).
    Creates a payout request.

    Docs: https://lzt-market.readme.io/reference/paymentspayout
    """

    __http_method__ = HttpMethod.POST
    __url__ = "/balance/payout"
    __returning__ = MarketStatusMessageResponse

    payment_system: str
    wallet: str
    amount: float
    currency: Currency
    include_fee: bool | None = None
    extra: dict[str, Any] | None = None


# Source: official OpenAPI spec, operationId "Payments.PayoutServices".
class PaymentsPayoutServices(BaseMethod[list[System]]):
    """Generated by forge — DO NOT EDIT. Get Payout Services.
    Sourced from the official OpenAPI spec (readme.io).
    Get a list of available payout services.

    Docs: https://lzt-market.readme.io/reference/paymentspayoutservices
    """

    __http_method__ = HttpMethod.GET
    __url__ = "/balance/payout/services"
    __returning__ = System
    __unwrap__ = "systems"


# Source: official OpenAPI spec, operationId "Payments.Transfer".
class PaymentsTransfer(BaseMethod[MarketStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Transfer Money.
    Sourced from the official OpenAPI spec (readme.io).
    Transfer money to any user.
    Required scopes:
    + **payment**

    Args:
        amount: Amount to send in your currency.
        user_id: User id of receiver. If **user_id** specified, **username** is not required.
        username: Username of receiver. If **username** specified, **user_id** is not required.
        comment: Transfer comment.
        telegram_deal: Is the deal happening on Telegram?
        telegram_username: Telegram username of the user you are dialoguing with.
        transfer_hold: Hold transfer or not.
        hold_length_value: Hold length value.
        hold_length_option: Hold length option.

    Docs: https://lzt-market.readme.io/reference/paymentstransfer
    """

    __http_method__ = HttpMethod.POST
    __url__ = "/balance/transfer"
    __returning__ = MarketStatusMessageResponse

    amount: int
    currency: Currency
    user_id: int | None = None
    username: str | None = None
    comment: str | None = None
    telegram_deal: bool | None = None
    telegram_username: str | None = None
    transfer_hold: bool | None = None
    hold_length_value: int | None = None
    hold_length_option: HoldLengthOption | None = None
