"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from typing import Any

from pylzt.enums.market import EmailType, Type
from pylzt.methods.base import BaseMethod
from pylzt.models.market import (
    ListUserItem,
    MarketStatusItemResponse,
    MarketStatusMessageResponse,
    PublishingCheckItem,
    PublishingFastSellResponse,
)
from pylzt.types import Currency, HttpMethod, ItemOrigin


# Source: official OpenAPI spec, operationId "Publishing.Add".
class PublishingAdd(BaseMethod[MarketStatusItemResponse[ListUserItem]]):
    """Generated by forge — DO NOT EDIT. Add Account.
    Sourced from the official OpenAPI spec (readme.io).
    Adds account on the market.
    Required email login data categories:
    + 9 - Fortnite
    + 12 - Epic games
    + 18 - Escape from Tarkov

    Args:
        price: Current price of account in your currency.
        title: Title of account. If **title** specified and **title_en** is empty, **title_en** will be automatically translated to English language.
        title_en: English title of account. If **title_en** specified and **title** is empty, **title** will be automatically translated to Russian language.
        auto_generate_title: Generate the title by using AI.
        guarantee_duration: Guarantee duration.
        description: Account public description.
        information: Account private information (visible only for buyer).
        forceTempEmail: Get temporary email if not required by category. Available for Supercell, Fortnite and Epic Games categories.
        resell_item_id: Put item id, if you are trying to resell item. This is useful to pass temporary email from reselling item to new item. You will get same temporary email from reselling account.
        has_email_login_data: Required if a **category** is one of list of Required email login data categories.
        email_login_data: Required if a **category** is one of list of Required email login data categories. Email login data (email:password format).
        email_type: Email type.
        tfa_secret: 2FA secret code. Available for `Instagram` and `Roblox` categories.
        allow_ask_discount: Allow users to ask discount for this account.
        proxy_id: Proxy id that will be used to check account.

    Docs: https://lzt-market.readme.io/reference/publishingadd
    """

    __http_method__ = HttpMethod.POST
    __url__ = "/item/add"
    __returning__ = MarketStatusItemResponse[ListUserItem]

    price: float
    category_id: int
    currency: Currency
    item_origin: ItemOrigin
    title: str | None = None
    title_en: str | None = None
    auto_generate_title: bool | None = None
    guarantee_duration: int | None = None
    description: str | None = None
    information: str | None = None
    forceTempEmail: bool | None = None
    resell_item_id: int | None = None
    has_email_login_data: bool | None = None
    email_login_data: str | None = None
    email_type: EmailType | None = None
    tfa_secret: str | None = None
    allow_ask_discount: bool | None = None
    proxy_id: int | None = None
    random_proxy: bool | None = None


# Source: official OpenAPI spec, operationId "Publishing.Check".
class PublishingCheck(BaseMethod[MarketStatusItemResponse[PublishingCheckItem]]):
    """Generated by forge — DO NOT EDIT. Check Account Details.
    Sourced from the official OpenAPI spec (readme.io).
    Check and put up to sale not published account OR update account information existing account.
    > ❗️ If you receive a "retry_request" error, you should repeat the same request (up to a maximum of 100 times).

    Args:
        item_id: Item id.
        random_proxy: Set this parameter to **true** so that the Market will take a random proxy from its pool for each of your requests. Otherwise, if this parameter is set to **false** or not set, the Market will take a specific proxy from its pool, which is predefined for each item. > This parameter only works with proxies from the Market pool. If you want to use your own proxies, use the proxy_id or extra[proxy] parameter.
        login: Account login (or email).
        password: Account password.
        login_password: Account login data (login:password format).
        has_email_login_data: Required if a **category** is one of list of Required email login data categories.
        email_login_data: Required if a **category** is one of list of Required email login data categories. Email login data (email:password format).
        email_type: Email type.

    Docs: https://lzt-market.readme.io/reference/publishingcheck
    """

    __http_method__ = HttpMethod.POST
    __url__ = "/{item_id}/goods/check"
    __returning__ = MarketStatusItemResponse[PublishingCheckItem]

    item_id: int
    random_proxy: bool | None = None
    login: str | None = None
    password: str | None = None
    login_password: str | None = None
    has_email_login_data: bool | None = None
    email_login_data: str | None = None
    email_type: EmailType | None = None
    extra: dict[str, Any] | None = None


# Source: official OpenAPI spec, operationId "Publishing.External".
class PublishingExternal(BaseMethod[MarketStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Add an External Account.
    Sourced from the official OpenAPI spec (readme.io).
    Check and add an external account to your item.
    > ❗️ Please note that if you're linking a Social Club account to Steam, it will update the last activity on your account (This is a limitation of Steam). If Social Club Games does not have a linked account, do not enter any data.

    Args:
        item_id: Item id.
        type: External account type.
        login: Account login data (login:password format).
        email_login_data: Email login data (email:password format).
        cookies: Cookies.

    Docs: https://lzt-market.readme.io/reference/publishingexternal
    """

    __http_method__ = HttpMethod.POST
    __url__ = "/{item_id}/external-account"
    __returning__ = MarketStatusMessageResponse

    item_id: int
    type: Type
    login: str | None = None
    email_login_data: str | None = None
    cookies: str | None = None


# Source: official OpenAPI spec, operationId "Publishing.FastSell".
class PublishingFastSell(BaseMethod[PublishingFastSellResponse]):
    """Generated by forge — DO NOT EDIT. Fast Account Upload.
    Sourced from the official OpenAPI spec (readme.io).
    Adds and checks the account for validity.
    > ❗️ If you receive a "retry_request" error, you should repeat the same request (up to a maximum of 100 times).

    Args:
        price: Current price of account in your currency.
        title: Title of account. If **title** specified and **title_en** is empty, **title_en** will be automatically translated to English language.
        title_en: English title of account. If **title_en** specified and **title** is empty, **title** will be automatically translated to Russian language.
        auto_generate_title: Generate the title by using AI.
        guarantee_duration: Guarantee duration.
        allow_ask_discount: Allow users to ask discount for this account.
        proxy_id: Proxy id that will be used to check account.
        description: Account public description.
        information: Account private information (visible only for buyer).
        login: Account login (or email).
        password: Account password.
        login_password: Account login data (login:password format).
        resell_item_id: Put item id, if you are trying to resell item. This is useful to pass temporary email from reselling item to new item. You will get same temporary email from reselling account.
        has_email_login_data: Required if a **category** is one of list of Required email login data categories.
        email_login_data: Required if a **category** is one of list of Required email login data categories. Email login data (email:password format).
        email_type: Email type.
        tfa_secret: 2FA secret code. Available for `Instagram` and `Roblox` categories.

    Docs: https://lzt-market.readme.io/reference/publishingfastsell
    """

    __http_method__ = HttpMethod.POST
    __url__ = "/item/fast-sell"
    __returning__ = PublishingFastSellResponse

    price: float
    category_id: int
    currency: Currency
    item_origin: ItemOrigin
    title: str | None = None
    title_en: str | None = None
    auto_generate_title: bool | None = None
    guarantee_duration: int | None = None
    allow_ask_discount: bool | None = None
    proxy_id: int | None = None
    random_proxy: bool | None = None
    description: str | None = None
    information: str | None = None
    login: str | None = None
    password: str | None = None
    login_password: str | None = None
    resell_item_id: int | None = None
    has_email_login_data: bool | None = None
    email_login_data: str | None = None
    email_type: EmailType | None = None
    tfa_secret: str | None = None
    extra: dict[str, Any] | None = None
