"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.enums.market import FieldsInclude
from pylzt.methods.base import BaseMethod
from pylzt.models.market import ProfileGetUser
from pylzt.types import HttpMethod


# Source: official OpenAPI spec, operationId "Profile.Get".
class ProfileGet(BaseMethod[ProfileGetUser]):
    """Generated by forge — DO NOT EDIT. Get Profile.
    Sourced from the official OpenAPI spec (readme.io).
    Displays info about your profile.

    Args:
        fields_include: List of hidden fields to include.

    Docs: https://lzt-market.readme.io/reference/profileget
    """

    __http_method__ = HttpMethod.GET
    __url__ = "/me"
    __returning__ = ProfileGetUser
    __unwrap__ = "user"

    fields_include: tuple[FieldsInclude, ...] | None = None
