"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.methods.base import BaseMethod
from pylzt.models.market import (
    MarketStatusMessageResponse,
    MarketTagIdTitleIsDefaultForOwnedAccountsOnlyBcResponse,
)
from pylzt.types import HttpMethod


# Source: official OpenAPI spec, operationId "Managing.TagsCreate".
class ManagingTagsCreate(BaseMethod[MarketTagIdTitleIsDefaultForOwnedAccountsOnlyBcResponse]):
    """Generated by forge — DO NOT EDIT. Create Tag.
    Sourced from the official OpenAPI spec (readme.io).
    Creates Tag.

    Args:
        bc: Background Color

    Docs: https://lzt-market.readme.io/reference/managingtagscreate
    """

    __http_method__ = HttpMethod.POST
    __url__ = "/user/tags"
    __returning__ = MarketTagIdTitleIsDefaultForOwnedAccountsOnlyBcResponse
    __unwrap__ = "tag"

    title: str
    bc: str


# Source: official OpenAPI spec, operationId "Managing.TagsDelete".
class ManagingTagsDelete(BaseMethod[MarketStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Delete Tag.
    Sourced from the official OpenAPI spec (readme.io).
    Deletes a tag.

    Docs: https://lzt-market.readme.io/reference/managingtagsdelete
    """

    __http_method__ = HttpMethod.DELETE
    __url__ = "/user/tags"
    __returning__ = MarketStatusMessageResponse

    tag_id: int


# Source: official OpenAPI spec, operationId "Managing.TagsEdit".
class ManagingTagsEdit(BaseMethod[MarketTagIdTitleIsDefaultForOwnedAccountsOnlyBcResponse]):
    """Generated by forge — DO NOT EDIT. Update Tag.
    Sourced from the official OpenAPI spec (readme.io).
    Updates a specified tag.

    Args:
        bc: Background Color

    Docs: https://lzt-market.readme.io/reference/managingtagsedit
    """

    __http_method__ = HttpMethod.PUT
    __url__ = "/user/tags"
    __returning__ = MarketTagIdTitleIsDefaultForOwnedAccountsOnlyBcResponse
    __unwrap__ = "tag"

    tag_id: int
    title: str
    bc: str


# Source: official OpenAPI spec, operationId "Managing.TagsList".
class ManagingTagsList(BaseMethod[list[MarketTagIdTitleIsDefaultForOwnedAccountsOnlyBcResponse]]):
    """Generated by forge — DO NOT EDIT. Get All Tags.
    Sourced from the official OpenAPI spec (readme.io).
    Returns a list of your tags.

    Docs: https://lzt-market.readme.io/reference/managingtagslist
    """

    __http_method__ = HttpMethod.GET
    __url__ = "/user/tags"
    __returning__ = MarketTagIdTitleIsDefaultForOwnedAccountsOnlyBcResponse
    __unwrap__ = "tags"


# Source: official OpenAPI spec, operationId "Managing.TagsOrder".
class ManagingTagsOrder(BaseMethod[MarketStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Reorder Tags.
    Sourced from the official OpenAPI spec (readme.io).
    Reorder your tags.
    > ❗️ Tags missing from `tag_order` will be deleted (even from the items).

    Args:
        tag_order: Array of tag IDs in the desired order.

    Docs: https://lzt-market.readme.io/reference/managingtagsorder
    """

    __http_method__ = HttpMethod.POST
    __url__ = "/user/tags/order"
    __returning__ = MarketStatusMessageResponse

    tag_order: tuple[int, ...]
