"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.methods.base import BaseMethod
from pylzt.models.market import MarketStatusMessageResponse
from pylzt.types import HttpMethod


# Source: official OpenAPI spec, operationId "Imap.Create".
class ImapCreate(BaseMethod[MarketStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Create IMAP Configuration.
    Sourced from the official OpenAPI spec (readme.io).
    Create an IMAP configuration for a domain.

    Args:
        domain: Name (domain) of IMAP configuration, required for future IMAP config deletion.
        imap_server: IMAP server address.
        port: IMAP server port.
        secure: Whether to use a secure connection.

    Docs: https://lzt-market.readme.io/reference/imapcreate
    """

    __http_method__ = HttpMethod.POST
    __url__ = "/imap"
    __returning__ = MarketStatusMessageResponse

    domain: str
    imap_server: str
    port: int
    secure: bool


# Source: official OpenAPI spec, operationId "Imap.Delete".
class ImapDelete(BaseMethod[MarketStatusMessageResponse]):
    """Generated by forge — DO NOT EDIT. Delete IMAP Configuration.
    Sourced from the official OpenAPI spec (readme.io).
    Delete an IMAP configuration for a domain.

    Args:
        domain: Name (domain) of IMAP configuration.

    Docs: https://lzt-market.readme.io/reference/imapdelete
    """

    __http_method__ = HttpMethod.DELETE
    __url__ = "/imap"
    __returning__ = MarketStatusMessageResponse

    domain: str
