"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.enums.market import Status
from pylzt.methods.base import BaseMethod
from pylzt.models.market import Invoice, PaymentsInvoiceListResponse
from pylzt.types import Currency, HttpMethod


# Source: official OpenAPI spec, operationId "Payments.Invoice.Get".
class PaymentsInvoiceGet(BaseMethod[Invoice]):
    """Generated by forge — DO NOT EDIT. Get Invoice.
    Sourced from the official OpenAPI spec (readme.io).
    Get invoice.
    Required scopes:
    + **invoice**

    Args:
        invoice_id: Invoice ID.
        payment_id: Payment ID.

    Docs: https://lzt-market.readme.io/reference/paymentsinvoiceget
    """

    __http_method__ = HttpMethod.GET
    __url__ = "/invoice"
    __returning__ = Invoice
    __unwrap__ = "invoice"

    invoice_id: int | None = None
    payment_id: str | None = None


# Source: official OpenAPI spec, operationId "Payments.Invoice.List".
class PaymentsInvoiceList(BaseMethod[PaymentsInvoiceListResponse]):
    """Generated by forge — DO NOT EDIT. Get Invoice List.
    Sourced from the official OpenAPI spec (readme.io).
    Get invoice list.
    Required scopes:
    + **invoice**

    Args:
        page: The number of the page to display results from.
        currency: Currency of the created invoice.
        status: Status of the invoice.
        amount: Invoice amount.
        merchant_id: Merchant ID.

    Docs: https://lzt-market.readme.io/reference/paymentsinvoicelist
    """

    __http_method__ = HttpMethod.GET
    __url__ = "/invoice/list"
    __returning__ = PaymentsInvoiceListResponse

    page: int | None = None
    currency: Currency | None = None
    status: Status | None = None
    amount: float | None = None
    merchant_id: int | None = None
