"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pylzt.enums.antipublic import Format, GroupBy, Order, SearchBy
from pylzt.methods.antipublic_account import GetDebug, LicenseAvailableQueries, LicenseCheckLicense
from pylzt.methods.antipublic_check import LicenseCheckLines
from pylzt.methods.antipublic_info import PublicCountLines, PublicCountLinesPlain
from pylzt.methods.antipublic_search import LicensePlusEmailPasswords, LicenseSearch
from pylzt.models.antipublic import PublicCountLinesResponse, Threads
from pylzt.transport.base import RequestOptions

if TYPE_CHECKING:
    from pylzt.methods.base import BaseMethod


class GeneratedAntipublicFacade:
    """Generated by forge — DO NOT EDIT. Async facade for the antipublic API."""

    if TYPE_CHECKING:

        async def __call__[T](
            self, method: BaseMethod[T], *, request_options: RequestOptions | None = None
        ) -> T: ...

    async def license_available_queries(
        self, *, request_options: RequestOptions | None = None
    ) -> str:
        """Generated by forge — DO NOT EDIT. Available Queries.
        Sourced from the official OpenAPI spec (readme.io).
        Get your available queries.

        Docs: https://antipublic.readme.io/reference/licenseavailablequeries-1
        """
        return await self(LicenseAvailableQueries(), request_options=request_options)

    async def license_check_license(self, *, request_options: RequestOptions | None = None) -> str:
        """Generated by forge — DO NOT EDIT. Check Access.
        Sourced from the official OpenAPI spec (readme.io).
        Checks your license.

        Docs: https://antipublic.readme.io/reference/licensechecklicense-1
        """
        return await self(LicenseCheckLicense(), request_options=request_options)

    async def get_debug(self, *, request_options: RequestOptions | None = None) -> Threads:
        """Generated by forge — DO NOT EDIT. Threads usage debug.
        Sourced from the official OpenAPI spec (readme.io).

        Docs: https://antipublic.readme.io/reference/get_debug
        """
        return await self(GetDebug(), request_options=request_options)

    async def license_check_lines(
        self,
        lines: tuple[str, ...],
        insert: bool | None = None,
        *,
        request_options: RequestOptions | None = None,
    ) -> str:
        """Generated by forge — DO NOT EDIT. Check Lines.
        Sourced from the official OpenAPI spec (readme.io).
        Check your lines. Maximum 1000 lines per request.

        Args:
            lines: Lines for check, email:password.
            insert: Upload private rows to AntiPublic db.

        Docs: https://antipublic.readme.io/reference/licensechecklines-1
        """
        return await self(
            LicenseCheckLines(lines=lines, insert=insert), request_options=request_options
        )

    async def public_count_lines(
        self, *, request_options: RequestOptions | None = None
    ) -> PublicCountLinesResponse:
        """Generated by forge — DO NOT EDIT. Count Lines.
        Sourced from the official OpenAPI spec (readme.io).
        Get count of rows in the AntiPublic db.

        Docs: https://antipublic.readme.io/reference/publiccountlines-1
        """
        return await self(PublicCountLines(), request_options=request_options)

    async def public_count_lines_plain(
        self, *, request_options: RequestOptions | None = None
    ) -> str:
        """Generated by forge — DO NOT EDIT. Count Lines Plain.
        Sourced from the official OpenAPI spec (readme.io).
        Get count of rows in the AntiPublic db (raw format).

        Docs: https://antipublic.readme.io/reference/publiccountlinesplain-1
        """
        return await self(PublicCountLinesPlain(), request_options=request_options)

    async def license_search(
        self,
        searchBy: SearchBy,
        query: dict[str, Any],
        direction: dict[str, Any] | None = None,
        order: Order | None = None,
        fromLastValueOfKey: bool | None = None,
        groupBy: GroupBy | None = None,
        format: Format | None = None,
        pageToken: str | None = None,
        *,
        request_options: RequestOptions | None = None,
    ) -> str:
        """Generated by forge — DO NOT EDIT. Search.
        Sourced from the official OpenAPI spec (readme.io).
        Search lines by email/password/domain.

        Args:
            searchBy: Search type. Search Priority: - **searchBy: email** - `email`, then `password`. - **searchBy: password** - `password`, then `email`. - **searchBy: domain** - `domain`, then `email`, then `password`.
            query: Search query
            direction: Search direction To use `all` - Premium required
            order: [**Premium** subscription required] If you specify DESC order, then most likely you will have a couple of results. Everything is fine and it should be. To get more results - you need to disable fuses by specifying `all` in `direction` for your query field. Or if the request field is `strict`, then specify `fromLastValueOfKey` equal to true.
            fromLastValueOfKey: [**Premium** subscription required] When using this option and "strict direction" the starting position starts from the last value of the key. For example, we have *email:pass1*, *email:pass2*, *email:pass3*. Then when setting `query` = email, `direction` = strict, `fromLastValueOfKey` = true the first result obtained will be `email:pass3`.
            groupBy: [**Premium** subscription required] This option allows you to remove "duplicates". Only the first found line corresponding to the grouping will be returned and will move on to the next value. Can be used in the following cases: - **searchBy: email** - `login@domain`. - **searchBy: password** - `password`. - **searchBy: domain** - `domain`, `login@domain`.
            format: The format of the returned results. Allows you to quickly leave the most necessary without post-processing. When used correctly together with `groupBy`, the execution time of a database search query can be accelerated by eliminating JOIN operations on the server.
            pageToken: The page token that was returned in the previous request. The token will be considered invalid if any of the request parameters change.

        Docs: https://antipublic.readme.io/reference/licensesearch-1
        """
        return await self(
            LicenseSearch(
                searchBy=searchBy,
                query=query,
                direction=direction,
                order=order,
                fromLastValueOfKey=fromLastValueOfKey,
                groupBy=groupBy,
                format=format,
                pageToken=pageToken,
            ),
            request_options=request_options,
        )

    async def license_plus_email_passwords(
        self,
        emails: tuple[str, ...],
        onlyPassword: bool | None = None,
        limit: int | None = None,
        *,
        request_options: RequestOptions | None = None,
    ) -> str:
        """Generated by forge — DO NOT EDIT. Email Passwords.
        Sourced from the official OpenAPI spec (readme.io).
        Get passwords for emails. AntiPublic Plus subscription required.

        Args:
            emails: Emails for search.
            onlyPassword: Return only passwords, instead of lines with logins
            limit: Result limit (per email).

        Docs: https://antipublic.readme.io/reference/licenseplusemailpasswords-1
        """
        return await self(
            LicensePlusEmailPasswords(emails=emails, onlyPassword=onlyPassword, limit=limit),
            request_options=request_options,
        )
