"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pylzt.enums.forum import (
    ClaimState,
    ContentType,
    ContestType,
    Direction,
    Duration,
    FieldsInclude,
    LengthOption,
    LikeType,
    Order,
    PayClaim,
    Period,
    PrizeType,
    State,
    TransferType,
    Type,
)
from pylzt.media import Media
from pylzt.methods.forum_assets import AssetsCss
from pylzt.methods.forum_authentication import OAuthToken
from pylzt.methods.forum_categories import CategoriesGet, CategoriesList
from pylzt.methods.forum_chatbox import (
    ChatboxGetLeaderboard,
    ChatboxIndex,
    ChatboxOnline,
    ChatboxPostIgnore,
    ChatboxPostMessage,
    ChatboxReportReasons,
)
from pylzt.methods.forum_content_tagging import TagsFind, TagsGet, TagsList, TagsPopular
from pylzt.methods.forum_conversations import (
    ConversationsAlertsEnable,
    ConversationsGet,
    ConversationsInvite,
    ConversationsKick,
    ConversationsMessagesEdit,
    ConversationsMessagesGet,
    ConversationsMessagesList,
    ConversationsMessagesUnstick,
    ConversationsRead,
    ConversationsReadAll,
    ConversationsSave,
    ConversationsSearch,
    ConversationsShareContent,
    ConversationsStart,
    ConversationsUnstar,
    ConversationsUpdate,
)
from pylzt.methods.forum_forms import FormsCreate, FormsList
from pylzt.methods.forum_forums import (
    ForumsFollowed,
    ForumsGet,
    ForumsGetFeedOptions,
    ForumsGrouped,
    ForumsList,
    ForumsUnfollow,
)
from pylzt.methods.forum_link_forums import LinksGet, LinksList
from pylzt.methods.forum_notifications import NotificationsGet, NotificationsRead
from pylzt.methods.forum_pages import PagesGet, PagesList
from pylzt.methods.forum_post_comments import PostsCommentsGet
from pylzt.methods.forum_posts import (
    PostsCommentsReportReasons,
    PostsGet,
    PostsList,
    PostsReportReasons,
    PostsUnlike,
)
from pylzt.methods.forum_profile_post_comments import (
    ProfilePostsCommentsGet,
    ProfilePostsCommentsList,
    ProfilePostsCommentsReportReasons,
)
from pylzt.methods.forum_profile_posts import (
    ProfilePostsCreate,
    ProfilePostsGet,
    ProfilePostsList,
    ProfilePostsReportReasons,
    ProfilePostsUnlike,
    ProfilePostsUnstick,
)
from pylzt.methods.forum_searching import (
    SearchAll,
    SearchPosts,
    SearchProfilePosts,
    SearchResults,
    SearchTagged,
    SearchThreads,
    SearchUsers,
)
from pylzt.methods.forum_threads import (
    ThreadsBump,
    ThreadsClaim,
    ThreadsCreateContest,
    ThreadsFinish,
    ThreadsFollowed,
    ThreadsGet,
    ThreadsHide,
    ThreadsList,
    ThreadsMove,
    ThreadsNavigation,
    ThreadsPollGet,
    ThreadsPollVote,
    ThreadsRecent,
    ThreadsUnfollow,
    ThreadsUnread,
    ThreadsUnstar,
)
from pylzt.methods.forum_users import (
    UsersAvatarCrop,
    UsersAvatarUpload,
    UsersBackgroundCrop,
    UsersBackgroundUpload,
    UsersClaims,
    UsersContents,
    UsersFields,
    UsersFind,
    UsersFollowings,
    UsersGet,
    UsersIgnored,
    UsersLikes,
    UsersList,
    UsersSAReset,
    UsersSecretAnswerTypes,
    UsersTrophies,
    UsersUnfollow,
    UsersUnignore,
)
from pylzt.models.forum import (
    CategoriesListResponse,
    ChatboxIndexResponse,
    Content,
    ConversationsMessagesEditMessage,
    ConversationsMessagesListResponse,
    ConversationsSearchResponse,
    FormsCreateResponse,
    FormsListResponse,
    ForumDataDataTotalLinksResponse,
    ForumsGetFeedOptionsResponse,
    ForumsGroupedResponse,
    ForumsListResponse,
    ForumStatusMessageResponse,
    Leaderboard,
    LinkForum,
    LinksListResponse,
    Message,
    OAuthTokenResponse,
    PagesListResponse,
    Post,
    SearchAllResponse,
    SearchAllUser,
    User,
    UsersClaimsResponse,
    UsersIgnoredUser,
    UsersLikesResponse,
    UsersListResponse,
    UsersSAResetResponse,
    UsersSecretAnswerTypesData,
    UsersTrophiesResponse,
)
from pylzt.types import Currency

if TYPE_CHECKING:
    from pylzt.methods.base import BaseMethod


class GeneratedForumFacade:
    """Generated by forge — DO NOT EDIT. Async facade for the forum API."""

    if TYPE_CHECKING:

        async def __call__[T](self, method: BaseMethod[T]) -> T: ...

    async def assets_css(self, css: tuple[str, ...] | None = None) -> str:
        """Generated by forge — DO NOT EDIT. Get CSS.
        Sourced from the official OpenAPI spec (readme.io).
        Gets css rulesets for requested selectors.

        Args:
            css: The names or identifiers of the CSS selectors to retrieve.

        Docs: https://lolzteam.readme.io/reference/assetscss
        """
        return await self(AssetsCss(css=css))

    async def o_auth_token(self) -> OAuthTokenResponse:
        """Generated by forge — DO NOT EDIT. Get Access Token.
        Sourced from the official OpenAPI spec (readme.io).
        Obtain an access token using various grant types.
        Supports the following grant types:
        - Client Credentials
        - Authorization Code
        - Refresh Token
        - Password

        Docs: https://lolzteam.readme.io/reference/oauthtoken
        """
        return await self(OAuthToken())

    async def categories_get(self, category_id: int) -> str:
        """Generated by forge — DO NOT EDIT. Get Category.
        Sourced from the official OpenAPI spec (readme.io).
        Detail information of a category.
        Required scopes:
        + **read**

        Args:
            category_id: Id of category.

        Docs: https://lolzteam.readme.io/reference/categoriesget
        """
        return await self(CategoriesGet(category_id=category_id))

    async def categories_list(
        self,
        parent_category_id: int | None = None,
        parent_forum_id: int | None = None,
        order: Order | None = None,
    ) -> CategoriesListResponse:
        """Generated by forge — DO NOT EDIT. Get Categories.
        Sourced from the official OpenAPI spec (readme.io).
        List of all categories in the system.
        Required scopes:
        + **read**

        Args:
            parent_category_id: Id of parent category. If exists, filter categories that are direct children of that category.
            parent_forum_id: Id of parent forum. If exists, filter categories that are direct children of that forum.
            order: Ordering of categories.

        Docs: https://lolzteam.readme.io/reference/categorieslist
        """
        return await self(
            CategoriesList(
                parent_category_id=parent_category_id, parent_forum_id=parent_forum_id, order=order
            )
        )

    async def chatbox_get_leaderboard(self, duration: Duration | None = None) -> list[Leaderboard]:
        """Generated by forge — DO NOT EDIT. Get Chat Leaderboard.
        Sourced from the official OpenAPI spec (readme.io).
        Get chat leaderboard.
        Required scopes:
        + **chatbox**

        Args:
            duration: Duration.

        Docs: https://lolzteam.readme.io/reference/chatboxgetleaderboard
        """
        return await self(ChatboxGetLeaderboard(duration=duration))

    async def chatbox_index(self, room_id: int | None = None) -> ChatboxIndexResponse:
        """Generated by forge — DO NOT EDIT. Get Chats.
        Sourced from the official OpenAPI spec (readme.io).
        Get chat rooms.
        Required scopes:
        + **chatbox**

        Args:
            room_id: Room id.

        Docs: https://lolzteam.readme.io/reference/chatboxindex
        """
        return await self(ChatboxIndex(room_id=room_id))

    async def chatbox_online(self, room_id: int) -> list[User]:
        """Generated by forge — DO NOT EDIT. Get Chat Online.
        Sourced from the official OpenAPI spec (readme.io).
        Get chat Online Users.
        Required scopes:
        + **chatbox**

        Args:
            room_id: Room id.

        Docs: https://lolzteam.readme.io/reference/chatboxonline
        """
        return await self(ChatboxOnline(room_id=room_id))

    async def chatbox_post_ignore(self, user_id: str) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Ignore Chat User.
        Sourced from the official OpenAPI spec (readme.io).
        Ignore chat user.
        Required scopes:
        + **chatbox**

        Docs: https://lolzteam.readme.io/reference/chatboxpostignore
        """
        return await self(ChatboxPostIgnore(user_id=user_id))

    async def chatbox_post_message(
        self, room_id: int, message: str, reply_message_id: int | None = None
    ) -> Message:
        """Generated by forge — DO NOT EDIT. Create Chat Message.
        Sourced from the official OpenAPI spec (readme.io).
        Create chat message.
        Required scopes:
        + **chatbox**

        Args:
            message: Content of the chat message.
            reply_message_id: ID of the message being replied to.

        Docs: https://lolzteam.readme.io/reference/chatboxpostmessage
        """
        return await self(
            ChatboxPostMessage(room_id=room_id, message=message, reply_message_id=reply_message_id)
        )

    async def chatbox_report_reasons(self, message_id: int) -> list[str]:
        """Generated by forge — DO NOT EDIT. Get Chat Message Report Reasons.
        Sourced from the official OpenAPI spec (readme.io).
        Report chat message.
        Required scopes:
        + **chatbox**

        Args:
            message_id: Message id.

        Docs: https://lolzteam.readme.io/reference/chatboxreportreasons
        """
        return await self(ChatboxReportReasons(message_id=message_id))

    async def tags_find(self, tag: str) -> str:
        """Generated by forge — DO NOT EDIT. Get Filtered Content.
        Sourced from the official OpenAPI spec (readme.io).
        Filtered list of tags.
        Required scopes:
        + **read**

        Args:
            tag: tag to filter. Tags start with the query will be returned.

        Docs: https://lolzteam.readme.io/reference/tagsfind
        """
        return await self(TagsFind(tag=tag))

    async def tags_get(self, tag_id: int, page: int | None = None, limit: int | None = None) -> str:
        """Generated by forge — DO NOT EDIT. Get Tagged Content.
        Sourced from the official OpenAPI spec (readme.io).
        List of tagged contents.
        Required scopes:
        + **read**

        Args:
            tag_id: Id of tag.
            page: Page number of tagged contents.
            limit: Number of tagged contents in a page.

        Docs: https://lolzteam.readme.io/reference/tagsget
        """
        return await self(TagsGet(tag_id=tag_id, page=page, limit=limit))

    async def tags_list(self, page: int | None = None, limit: int | None = None) -> str:
        """Generated by forge — DO NOT EDIT. Get Tags.
        Sourced from the official OpenAPI spec (readme.io).
        List of tags.
        Required scopes:
        + **read**

        Args:
            page: Page number of tags list.
            limit: Number of results in a page.

        Docs: https://lolzteam.readme.io/reference/tagslist
        """
        return await self(TagsList(page=page, limit=limit))

    async def tags_popular(self) -> str:
        """Generated by forge — DO NOT EDIT. Get Popular Tags.
        Sourced from the official OpenAPI spec (readme.io).
        List of popular tags (no pagination).
        Required scopes:
        + **read**

        Docs: https://lolzteam.readme.io/reference/tagspopular
        """
        return await self(TagsPopular())

    async def conversations_alerts_enable(self, conversation_id: int) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Enable Conversation Alerts.
        Sourced from the official OpenAPI spec (readme.io).
        Enable alerts for conversation.
        Required scopes:
        + **post**
        + **conversate**

        Args:
            conversation_id: Id of conversation.

        Docs: https://lolzteam.readme.io/reference/conversationsalertsenable
        """
        return await self(ConversationsAlertsEnable(conversation_id=conversation_id))

    async def conversations_get(self, conversation_id: int) -> str:
        """Generated by forge — DO NOT EDIT. Get Conversation.
        Sourced from the official OpenAPI spec (readme.io).
        Detail information of a conversation.
        Required scopes:
        + **read**
        + **conversate**

        Args:
            conversation_id: Id of conversation.

        Docs: https://lolzteam.readme.io/reference/conversationsget
        """
        return await self(ConversationsGet(conversation_id=conversation_id))

    async def conversations_invite(
        self, conversation_id: int, recipients: tuple[str, ...]
    ) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Invite Users to Conversation.
        Sourced from the official OpenAPI spec (readme.io).
        Invite one or more users to an existing conversation.
        Required scopes:
        + **conversate**
        + **post**

        Args:
            conversation_id: Id of conversation.
            recipients: List of recipients username's.

        Docs: https://lolzteam.readme.io/reference/conversationsinvite
        """
        return await self(
            ConversationsInvite(conversation_id=conversation_id, recipients=recipients)
        )

    async def conversations_kick(
        self, conversation_id: int, user_id: int
    ) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Kick User from Conversation.
        Sourced from the official OpenAPI spec (readme.io).
        Kicks a user from a conversation.
        Required scopes:
        + **conversate**

        Args:
            conversation_id: Id of conversation.
            user_id: Id of user to kick from conversation.

        Docs: https://lolzteam.readme.io/reference/conversationskick
        """
        return await self(ConversationsKick(conversation_id=conversation_id, user_id=user_id))

    async def conversations_messages_edit(
        self, conversation_id: int, message_id: int, message_body: str
    ) -> ConversationsMessagesEditMessage:
        """Generated by forge — DO NOT EDIT. Edit Conversation Message.
        Sourced from the official OpenAPI spec (readme.io).
        Edit a message.
        Required scopes:
        + **post**
        + **conversate**

        Args:
            conversation_id: Id of conversation.
            message_id: Id of message.
            message_body: New content of the message.

        Docs: https://lolzteam.readme.io/reference/conversationsmessagesedit
        """
        return await self(
            ConversationsMessagesEdit(
                conversation_id=conversation_id, message_id=message_id, message_body=message_body
            )
        )

    async def conversations_messages_get(self, message_id: int) -> str:
        """Generated by forge — DO NOT EDIT. Get Conversation Message.
        Sourced from the official OpenAPI spec (readme.io).
        Detail information of a message.
        Required scopes:
        + **read**
        + **conversate**

        Args:
            message_id: Id of message.

        Docs: https://lolzteam.readme.io/reference/conversationsmessagesget
        """
        return await self(ConversationsMessagesGet(message_id=message_id))

    async def conversations_messages_list(
        self,
        conversation_id: int,
        page: int | None = None,
        limit: int | None = None,
        order: Order | None = None,
        before: int | None = None,
        after: int | None = None,
    ) -> ConversationsMessagesListResponse:
        """Generated by forge — DO NOT EDIT. Get Conversation Messages.
        Sourced from the official OpenAPI spec (readme.io).
        List of messages in a conversation (with pagination).
        Required scopes:
        + **read**
        + **conversate**

        Args:
            conversation_id: Id of conversation.
            page: Page number of messages.
            limit: Number of messages in a page.
            order: Ordering of messages.
            before: Date to get older messages.
            after: Date to get newer messages.

        Docs: https://lolzteam.readme.io/reference/conversationsmessageslist
        """
        return await self(
            ConversationsMessagesList(
                conversation_id=conversation_id,
                page=page,
                limit=limit,
                order=order,
                before=before,
                after=after,
            )
        )

    async def conversations_messages_unstick(
        self, conversation_id: int, message_id: int
    ) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Unstick Conversation Message.
        Sourced from the official OpenAPI spec (readme.io).
        Unstick a message in a conversation.
        Required scopes:
        + **post**
        + **conversate**

        Args:
            conversation_id: Id of conversation.
            message_id: Id of message.

        Docs: https://lolzteam.readme.io/reference/conversationsmessagesunstick
        """
        return await self(
            ConversationsMessagesUnstick(conversation_id=conversation_id, message_id=message_id)
        )

    async def conversations_read(self, conversation_id: int) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Read Conversation.
        Sourced from the official OpenAPI spec (readme.io).
        Read a specific conversation.
        Required scopes:
        + **conversate**

        Args:
            conversation_id: Id of conversation.

        Docs: https://lolzteam.readme.io/reference/conversationsread
        """
        return await self(ConversationsRead(conversation_id=conversation_id))

    async def conversations_read_all(self) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Read All Conversations.
        Sourced from the official OpenAPI spec (readme.io).
        Mark all conversations as read.
        Required scopes:
        + **read**
        + **conversate**

        Docs: https://lolzteam.readme.io/reference/conversationsreadall
        """
        return await self(ConversationsReadAll())

    async def conversations_save(self, link: str) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Send Content To Saved Messages.
        Sourced from the official OpenAPI spec (readme.io).
        Send content to Saved Messages.
        Required scopes:
        + **conversate**

        Args:
            link: Content url.

        Docs: https://lolzteam.readme.io/reference/conversationssave
        """
        return await self(ConversationsSave(link=link))

    async def conversations_search(
        self,
        q: str | None = None,
        conversation_id: int | None = None,
        search_recipients: bool | None = None,
    ) -> ConversationsSearchResponse:
        """Generated by forge — DO NOT EDIT. Search Conversations Messages.
        Sourced from the official OpenAPI spec (readme.io).
        Search for conversations messages or recipients.
        Required scopes:
        + **read**
        + **conversate**

        Args:
            q: Search query string.
            conversation_id: Id of conversation.
            search_recipients: Search for recipients.

        Docs: https://lolzteam.readme.io/reference/conversationssearch
        """
        return await self(
            ConversationsSearch(
                q=q, conversation_id=conversation_id, search_recipients=search_recipients
            )
        )

    async def conversations_share_content(self, thread_id: int) -> str:
        """Generated by forge — DO NOT EDIT. Get Shareable Thread Content.
        Sourced from the official OpenAPI spec (readme.io).
        Get a shareable thread content (hides).
        Required scopes:
        + **get**
        + **conversate**

        Args:
            thread_id: Id of thread.

        Docs: https://lolzteam.readme.io/reference/conversationssharecontent
        """
        return await self(ConversationsShareContent(thread_id=thread_id))

    async def conversations_start(self, user_id: str) -> ConversationsMessagesEditMessage:
        """Generated by forge — DO NOT EDIT. Start Conversation.
        Sourced from the official OpenAPI spec (readme.io).
        Start a new conversation with a user.
        Required scopes:
        + **conversate**

        Docs: https://lolzteam.readme.io/reference/conversationsstart
        """
        return await self(ConversationsStart(user_id=user_id))

    async def conversations_unstar(self, conversation_id: int) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Unstar Conversation.
        Sourced from the official OpenAPI spec (readme.io).
        Unstar conversation.
        Required scopes:
        + **post**
        + **conversate**

        Args:
            conversation_id: Id of conversation.

        Docs: https://lolzteam.readme.io/reference/conversationsunstar
        """
        return await self(ConversationsUnstar(conversation_id=conversation_id))

    async def conversations_update(
        self,
        conversation_id: int,
        title: str | None = None,
        open_invite: bool | None = None,
        history_open: bool | None = None,
        allow_edit_messages: bool | None = None,
        allow_sticky_messages: bool | None = None,
        allow_delete_own_messages: bool | None = None,
    ) -> str:
        """Generated by forge — DO NOT EDIT. Edit Conversation.
        Sourced from the official OpenAPI spec (readme.io).
        Edit conversation.
        Required scopes:
        + **conversate**

        Args:
            conversation_id: Id of conversation.
            title: New conversation title.
            open_invite: Allow members to invite others.
            history_open: Make conversation history visible to new members.
            allow_edit_messages: Allow members to edit their own messages.
            allow_sticky_messages: Allow members to stick messages.
            allow_delete_own_messages: Allow members to delete their own messages.

        Docs: https://lolzteam.readme.io/reference/conversationsupdate
        """
        return await self(
            ConversationsUpdate(
                conversation_id=conversation_id,
                title=title,
                open_invite=open_invite,
                history_open=history_open,
                allow_edit_messages=allow_edit_messages,
                allow_sticky_messages=allow_sticky_messages,
                allow_delete_own_messages=allow_delete_own_messages,
            )
        )

    async def forms_create(self) -> FormsCreateResponse:
        """Generated by forge — DO NOT EDIT. Create Form.
        Sourced from the official OpenAPI spec (readme.io).
        Create Form.

        Docs: https://lolzteam.readme.io/reference/formscreate
        """
        return await self(FormsCreate())

    async def forms_list(self, page: int | None = None) -> FormsListResponse:
        """Generated by forge — DO NOT EDIT. Get Forms List.
        Sourced from the official OpenAPI spec (readme.io).
        Get Forms List

        Args:
            page: Page number of forms.

        Docs: https://lolzteam.readme.io/reference/formslist
        """
        return await self(FormsList(page=page))

    async def forums_followed(self, total: bool | None = None) -> str:
        """Generated by forge — DO NOT EDIT. Get Followed Forums.
        Sourced from the official OpenAPI spec (readme.io).
        List of followed forums by current user.
        Required scopes:
        + **read**

        Args:
            total: If included in the request, only the forum count is returned as **forums_total**.

        Docs: https://lolzteam.readme.io/reference/forumsfollowed
        """
        return await self(ForumsFollowed(total=total))

    async def forums_get(self, forum_id: int) -> str:
        """Generated by forge — DO NOT EDIT. Get Forum.
        Sourced from the official OpenAPI spec (readme.io).
        Detail information of a forum.
        Required scopes:
        + **read**

        Args:
            forum_id: Id of forum.

        Docs: https://lolzteam.readme.io/reference/forumsget
        """
        return await self(ForumsGet(forum_id=forum_id))

    async def forums_get_feed_options(self) -> ForumsGetFeedOptionsResponse:
        """Generated by forge — DO NOT EDIT. Get Feed Options.
        Sourced from the official OpenAPI spec (readme.io).
        Returns available options for the forums feed.
        Required scopes:
        + **read**

        Docs: https://lolzteam.readme.io/reference/forumsgetfeedoptions
        """
        return await self(ForumsGetFeedOptions())

    async def forums_grouped(self) -> ForumsGroupedResponse:
        """Generated by forge — DO NOT EDIT. Get Forums Tree.
        Sourced from the official OpenAPI spec (readme.io).
        Returns grouped forums.
        Required scopes:
        + **read**

        Docs: https://lolzteam.readme.io/reference/forumsgrouped
        """
        return await self(ForumsGrouped())

    async def forums_list(
        self,
        parent_category_id: int | None = None,
        parent_forum_id: int | None = None,
        order: Order | None = None,
    ) -> ForumsListResponse:
        """Generated by forge — DO NOT EDIT. Get Forums.
        Sourced from the official OpenAPI spec (readme.io).
        List of all forums in the system.
        Required scopes:
        + **read**

        Args:
            parent_category_id: Id of parent category. If exists, filter forums that are direct children of that category.
            parent_forum_id: Id of parent forum. If exists, filter forums that are direct children of that forum.
            order: Ordering of forums.

        Docs: https://lolzteam.readme.io/reference/forumslist
        """
        return await self(
            ForumsList(
                parent_category_id=parent_category_id, parent_forum_id=parent_forum_id, order=order
            )
        )

    async def forums_unfollow(self, forum_id: int) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Unfollow Forum.
        Sourced from the official OpenAPI spec (readme.io).
        Unfollow a forum.
        Required scopes:
        + **post**

        Args:
            forum_id: Id of forum.

        Docs: https://lolzteam.readme.io/reference/forumsunfollow
        """
        return await self(ForumsUnfollow(forum_id=forum_id))

    async def links_get(self, link_id: int) -> LinkForum:
        """Generated by forge — DO NOT EDIT. Get Link Forum.
        Sourced from the official OpenAPI spec (readme.io).
        Detail information of a link forum.
        Required scopes:
        + **read**

        Args:
            link_id: Id of link forum.

        Docs: https://lolzteam.readme.io/reference/linksget
        """
        return await self(LinksGet(link_id=link_id))

    async def links_list(self) -> LinksListResponse:
        """Generated by forge — DO NOT EDIT. Get Links Forum.
        Sourced from the official OpenAPI spec (readme.io).
        List of all link forums.
        Required scopes:
        + **read**

        Docs: https://lolzteam.readme.io/reference/linkslist
        """
        return await self(LinksList())

    async def notifications_get(self, notification_id: int) -> str:
        """Generated by forge — DO NOT EDIT. Get Notification.
        Sourced from the official OpenAPI spec (readme.io).
        Get associated content of notification. The response depends on the content type.
        Required scopes:
        + **read**

        Args:
            notification_id: Id of notification.

        Docs: https://lolzteam.readme.io/reference/notificationsget
        """
        return await self(NotificationsGet(notification_id=notification_id))

    async def notifications_read(
        self, notification_id: int | None = None
    ) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Mark Notification Read.
        Sourced from the official OpenAPI spec (readme.io).
        Mark single notification or all existing notifications read.
        Required scopes:
        + **post**

        Args:
            notification_id: If notification_id is omitted, it's mark all existing notifications as read.

        Docs: https://lolzteam.readme.io/reference/notificationsread
        """
        return await self(NotificationsRead(notification_id=notification_id))

    async def pages_get(self, page_id: int) -> str:
        """Generated by forge — DO NOT EDIT. Get Page.
        Sourced from the official OpenAPI spec (readme.io).
        Detail information of a page.
        Required scopes:
        + **read**

        Args:
            page_id: Id of page.

        Docs: https://lolzteam.readme.io/reference/pagesget
        """
        return await self(PagesGet(page_id=page_id))

    async def pages_list(
        self, parent_page_id: int | None = None, order: Order | None = None
    ) -> PagesListResponse:
        """Generated by forge — DO NOT EDIT. Get Pages.
        Sourced from the official OpenAPI spec (readme.io).
        List of all pages in the system.
        Required scopes:
        + **read**

        Args:
            parent_page_id: Id of parent page. If exists, filter pages that are direct children of that page.
            order: Ordering of pages.

        Docs: https://lolzteam.readme.io/reference/pageslist
        """
        return await self(PagesList(parent_page_id=parent_page_id, order=order))

    async def posts_comments_get(
        self,
        post_id: int | None = None,
        post_comment_id: int | None = None,
        before: int | None = None,
        before_comment: int | None = None,
    ) -> str:
        """Generated by forge — DO NOT EDIT. Get Post Comments.
        Sourced from the official OpenAPI spec (readme.io).
        List of post comments in a thread.
        Required scopes:
        + **read**

        Args:
            post_id: Id of a post.
            post_comment_id: Id of a post comment.
            before: The time in milliseconds (e.g. 1652177794083) before last comment date.
            before_comment: Comment id to get older comments.

        Docs: https://lolzteam.readme.io/reference/postscommentsget
        """
        return await self(
            PostsCommentsGet(
                post_id=post_id,
                post_comment_id=post_comment_id,
                before=before,
                before_comment=before_comment,
            )
        )

    async def posts_comments_report_reasons(self, post_comment_id: int) -> list[str]:
        """Generated by forge — DO NOT EDIT. Get Post Comment Report Reasons.
        Sourced from the official OpenAPI spec (readme.io).
        Get a post comment report reasons.
        Required scopes:
        + **read**

        Args:
            post_comment_id: Id of post comment.

        Docs: https://lolzteam.readme.io/reference/postscommentsreportreasons
        """
        return await self(PostsCommentsReportReasons(post_comment_id=post_comment_id))

    async def posts_get(self, post_id: int) -> Post:
        """Generated by forge — DO NOT EDIT. Get Post.
        Sourced from the official OpenAPI spec (readme.io).
        Detail information of a post.
        Required scopes:
        + **read**

        Args:
            post_id: Id of post.

        Docs: https://lolzteam.readme.io/reference/postsget
        """
        return await self(PostsGet(post_id=post_id))

    async def posts_list(
        self,
        thread_id: int | None = None,
        page_of_post_id: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        order: Order | None = None,
    ) -> str:
        """Generated by forge — DO NOT EDIT. Get Posts.
        Sourced from the official OpenAPI spec (readme.io).
        List of posts in a thread (with pagination).
        Required scopes:
        + **read**

        Args:
            thread_id: Id of the containing thread.
            page_of_post_id: Id of a post, posts that are in the same page with the specified post will be returned. **thread_id** may be skipped.
            page: Page number of posts.
            limit: Number of posts in a page.
            order: Ordering of posts.

        Docs: https://lolzteam.readme.io/reference/postslist
        """
        return await self(
            PostsList(
                thread_id=thread_id,
                page_of_post_id=page_of_post_id,
                page=page,
                limit=limit,
                order=order,
            )
        )

    async def posts_report_reasons(self, post_id: int) -> list[str]:
        """Generated by forge — DO NOT EDIT. Get Post Report Reasons.
        Sourced from the official OpenAPI spec (readme.io).
        Get post report reasons.
        Required scopes:
        + **read**

        Args:
            post_id: Id of post.

        Docs: https://lolzteam.readme.io/reference/postsreportreasons
        """
        return await self(PostsReportReasons(post_id=post_id))

    async def posts_unlike(self, post_id: int) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Unlike Post.
        Sourced from the official OpenAPI spec (readme.io).
        Unlike a post.
        Required scopes:
        + **post**

        Args:
            post_id: Id of post.

        Docs: https://lolzteam.readme.io/reference/postsunlike
        """
        return await self(PostsUnlike(post_id=post_id))

    async def profile_posts_comments_get(self, profile_post_id: int, comment_id: int) -> str:
        """Generated by forge — DO NOT EDIT. Get Profile Post Comment.
        Sourced from the official OpenAPI spec (readme.io).
        Detail information of a profile post comment.
        Required scopes:
        + **read**

        Args:
            profile_post_id: Id of profile post.
            comment_id: Id of profile post comment.

        Docs: https://lolzteam.readme.io/reference/profilepostscommentsget
        """
        return await self(
            ProfilePostsCommentsGet(profile_post_id=profile_post_id, comment_id=comment_id)
        )

    async def profile_posts_comments_list(
        self,
        profile_post_id: int | None = None,
        comment_id: int | None = None,
        page_of_comment_id: int | None = None,
        before: int | None = None,
        limit: int | None = None,
    ) -> str:
        """Generated by forge — DO NOT EDIT. Get Profile Post Comments.
        Sourced from the official OpenAPI spec (readme.io).
        List of comments of a profile post.
        Required scopes:
        + **read**

        Args:
            profile_post_id: ID of profile post.
            comment_id: ID of a profile post comment.
            page_of_comment_id: ID of a profile post comment, comments that are in the same page with the specified comment will be returned.
            before: Date to get older comments. Please note that this entry point does not support the page parameter but it still does support **limit**.
            limit: Number of profile posts in a page.

        Docs: https://lolzteam.readme.io/reference/profilepostscommentslist
        """
        return await self(
            ProfilePostsCommentsList(
                profile_post_id=profile_post_id,
                comment_id=comment_id,
                page_of_comment_id=page_of_comment_id,
                before=before,
                limit=limit,
            )
        )

    async def profile_posts_comments_report_reasons(self, comment_id: int) -> list[str]:
        """Generated by forge — DO NOT EDIT. Get Profile Post Comment Report Reasons.
        Sourced from the official OpenAPI spec (readme.io).
        Get profile post comment report reasons.
        Required scopes:
        + **read**

        Args:
            comment_id: Id of profile post comment.

        Docs: https://lolzteam.readme.io/reference/profilepostscommentsreportreasons
        """
        return await self(ProfilePostsCommentsReportReasons(comment_id=comment_id))

    async def profile_posts_create(self, user_id: str, post_body: str) -> str:
        """Generated by forge — DO NOT EDIT. Create Profile Post.
        Sourced from the official OpenAPI spec (readme.io).
        Create a profile post on a user profile.
        Required scopes:
        + **post**

        Args:
            post_body: Content of a profile post.

        Docs: https://lolzteam.readme.io/reference/profilepostscreate
        """
        return await self(ProfilePostsCreate(user_id=user_id, post_body=post_body))

    async def profile_posts_get(self, profile_post_id: int) -> str:
        """Generated by forge — DO NOT EDIT. Get Profile Post.
        Sourced from the official OpenAPI spec (readme.io).
        Detail information of a profile post.
        Required scopes:
        + **read**

        Args:
            profile_post_id: Id of profile post.

        Docs: https://lolzteam.readme.io/reference/profilepostsget
        """
        return await self(ProfilePostsGet(profile_post_id=profile_post_id))

    async def profile_posts_list(
        self,
        user_id: str,
        posts_user_id: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        fields_include: tuple[FieldsInclude, ...] | None = None,
    ) -> str:
        """Generated by forge — DO NOT EDIT. Get Profile Posts.
        Sourced from the official OpenAPI spec (readme.io).
        List of profile posts (with pagination).
        Required scopes:
        + **read**

        Args:
            user_id: User ID. > You can use shortlink `me` to interact with your profile.
            posts_user_id: Filter to get only posts from the specified user.
            page: Page number of contents.
            limit: Number of contents in a page.
            fields_include: List of fields to include.

        Docs: https://lolzteam.readme.io/reference/profilepostslist
        """
        return await self(
            ProfilePostsList(
                user_id=user_id,
                posts_user_id=posts_user_id,
                page=page,
                limit=limit,
                fields_include=fields_include,
            )
        )

    async def profile_posts_report_reasons(self, profile_post_id: int) -> list[str]:
        """Generated by forge — DO NOT EDIT. Get Profile Post Report Reasons.
        Sourced from the official OpenAPI spec (readme.io).
        Get Profile Post Report Reasons.
        Required scopes:
        + **read**

        Args:
            profile_post_id: Id of profile post.

        Docs: https://lolzteam.readme.io/reference/profilepostsreportreasons
        """
        return await self(ProfilePostsReportReasons(profile_post_id=profile_post_id))

    async def profile_posts_unlike(self, profile_post_id: int) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Unlike Profile Post.
        Sourced from the official OpenAPI spec (readme.io).
        Unlike a profile post.
        Required scopes:
        + **post**

        Args:
            profile_post_id: Id of profile post.

        Docs: https://lolzteam.readme.io/reference/profilepostsunlike
        """
        return await self(ProfilePostsUnlike(profile_post_id=profile_post_id))

    async def profile_posts_unstick(self, profile_post_id: int) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Unstick Profile Post.
        Sourced from the official OpenAPI spec (readme.io).
        Unstick a profile post.
        Required scopes:
        + **post**

        Args:
            profile_post_id: Id of profile post.

        Docs: https://lolzteam.readme.io/reference/profilepostsunstick
        """
        return await self(ProfilePostsUnstick(profile_post_id=profile_post_id))

    async def search_all(
        self,
        q: str | None = None,
        tag: str | None = None,
        forum_id: int | None = None,
        user_id: str | None = None,
        page: int | None = None,
        limit: int | None = None,
        before: int | None = None,
    ) -> SearchAllResponse:
        """Generated by forge — DO NOT EDIT. Search.
        Sourced from the official OpenAPI spec (readme.io).
        Search for all supported contents.
        Required scopes:
        + **post**

        Args:
            q: Search query. Can be skipped if **user_id** is set.
            tag: Tag to search for tagged contents.
            forum_id: Id of the container forum to search for contents. Child forums of the specified forum will be included in the search.
            page: Page number of results.
            limit: Number of results in a page.
            before: The time in milliseconds (e.g. 1767214800) before last content date.

        Docs: https://lolzteam.readme.io/reference/searchall
        """
        return await self(
            SearchAll(
                q=q,
                tag=tag,
                forum_id=forum_id,
                user_id=user_id,
                page=page,
                limit=limit,
                before=before,
            )
        )

    async def search_posts(
        self,
        q: str | None = None,
        tag: str | None = None,
        forum_id: int | None = None,
        user_id: str | None = None,
        page: int | None = None,
        limit: int | None = None,
        data_limit: int | None = None,
        before: int | None = None,
    ) -> ForumDataDataTotalLinksResponse:
        """Generated by forge — DO NOT EDIT. Search Post.
        Sourced from the official OpenAPI spec (readme.io).
        Search for posts.
        Required scopes:
        + **post**

        Args:
            q: Search query. Can be skipped if **user_id** is set.
            tag: Tag to search for tagged contents.
            forum_id: Id of the container forum to search for contents. Child forums of the specified forum will be included in the search.
            page: Page number of results.
            limit: Number of results in a page.
            data_limit: Number of post data to be returned.
            before: The time in milliseconds (e.g. 1767214800) before last content date.

        Docs: https://lolzteam.readme.io/reference/searchposts
        """
        return await self(
            SearchPosts(
                q=q,
                tag=tag,
                forum_id=forum_id,
                user_id=user_id,
                page=page,
                limit=limit,
                data_limit=data_limit,
                before=before,
            )
        )

    async def search_profile_posts(
        self,
        q: str | None = None,
        user_id: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        before: int | None = None,
    ) -> ForumDataDataTotalLinksResponse:
        """Generated by forge — DO NOT EDIT. Search Profile Posts.
        Sourced from the official OpenAPI spec (readme.io).
        Search for profile posts.
        Required scopes:
        + **post**

        Args:
            q: Search query. Can be skipped if **user_id** is set.
            user_id: User ID to filter profile posts.
            page: Page number of results.
            limit: Number of results in a page.
            before: The time in milliseconds (e.g. 1767214800) before last content date.

        Docs: https://lolzteam.readme.io/reference/searchprofileposts
        """
        return await self(
            SearchProfilePosts(q=q, user_id=user_id, page=page, limit=limit, before=before)
        )

    async def search_results(
        self, search_id: str, page: int | None = None, limit: int | None = None
    ) -> str:
        """Generated by forge — DO NOT EDIT. Get Search Results.
        Sourced from the official OpenAPI spec (readme.io).
        List of search results (with pagination).
        Required scopes:
        + **get**

        Args:
            search_id: Search ID.
            page: Page number of results.
            limit: Number of results in a page.

        Docs: https://lolzteam.readme.io/reference/searchresults
        """
        return await self(SearchResults(search_id=search_id, page=page, limit=limit))

    async def search_tagged(
        self,
        tag: str | None = None,
        tags: tuple[str, ...] | None = None,
        page: int | None = None,
        limit: int | None = None,
    ) -> ForumDataDataTotalLinksResponse:
        """Generated by forge — DO NOT EDIT. Search Tagged.
        Sourced from the official OpenAPI spec (readme.io).
        Search for tagged contents.
        Required scopes:
        + **post**

        Args:
            tag: Tag to search for tagged contents.
            tags: Array of tags to search for tagged contents.
            page: Page number of results.
            limit: Number of results in a page.

        Docs: https://lolzteam.readme.io/reference/searchtagged
        """
        return await self(SearchTagged(tag=tag, tags=tags, page=page, limit=limit))

    async def search_threads(
        self,
        q: str | None = None,
        tag: str | None = None,
        forum_id: int | None = None,
        user_id: str | None = None,
        page: int | None = None,
        limit: int | None = None,
        data_limit: int | None = None,
        before: int | None = None,
    ) -> ForumDataDataTotalLinksResponse:
        """Generated by forge — DO NOT EDIT. Search Thread.
        Sourced from the official OpenAPI spec (readme.io).
        Search for threads.
        Required scopes:
        + **post**

        Args:
            q: Search query. Can be skipped if **user_id** is set.
            tag: Tag to search for tagged contents.
            forum_id: Id of the container forum to search for contents. Child forums of the specified forum will be included in the search.
            page: Page number of results.
            limit: Number of results in a page.
            data_limit: Number of thread data to be returned.
            before: The time in milliseconds (e.g. 1767214800) before last content date.

        Docs: https://lolzteam.readme.io/reference/searchthreads
        """
        return await self(
            SearchThreads(
                q=q,
                tag=tag,
                forum_id=forum_id,
                user_id=user_id,
                page=page,
                limit=limit,
                data_limit=data_limit,
                before=before,
            )
        )

    async def search_users(self, q: str | None = None) -> list[SearchAllUser]:
        """Generated by forge — DO NOT EDIT. Search Users.
        Sourced from the official OpenAPI spec (readme.io).
        Search for users.
        Required scopes:
        + **post**

        Args:
            q: Search query.

        Docs: https://lolzteam.readme.io/reference/searchusers
        """
        return await self(SearchUsers(q=q))

    async def threads_bump(self, thread_id: int) -> str:
        """Generated by forge — DO NOT EDIT. Bump Thread.
        Sourced from the official OpenAPI spec (readme.io).
        Bump a thread.
        Required scopes:
        + **post**

        Args:
            thread_id: Id of thread.

        Docs: https://lolzteam.readme.io/reference/threadsbump
        """
        return await self(ThreadsBump(thread_id=thread_id))

    async def threads_claim(
        self,
        as_responder: str,
        as_is_market_deal: bool,
        as_amount: float,
        transfer_type: TransferType,
        post_body: str,
        as_market_item_id: int | None = None,
        as_data: str | None = None,
        currency: Currency | None = None,
        pay_claim: PayClaim | None = None,
        as_funds_receipt: str | None = None,
        as_tg_login_screenshot: str | None = None,
        tags: tuple[str, ...] | None = None,
        hide_contacts: bool | None = None,
        allow_ask_hidden_content: bool | None = None,
        reply_group: int | None = None,
        comment_ignore_group: bool | None = None,
        dont_alert_followers: bool | None = None,
        schedule_date: str | None = None,
        schedule_time: str | None = None,
        watch_thread_state: bool | None = None,
        watch_thread: bool | None = None,
        watch_thread_email: bool | None = None,
    ) -> Content:
        """Generated by forge — DO NOT EDIT. Create Claim.
        Sourced from the official OpenAPI spec (readme.io).
        Create a Claim.
        Required scopes:
        + **post**

        Args:
            as_responder: To whom the complaint is filed. Specify a nickname or a link to the profile.
            as_is_market_deal: Did you buy account on the market?
            as_amount: Indicate the amount by which the responder deceived you.
            transfer_type: The transaction took place through a guarantor or there was a transfer to the market with a hold? Required if **as_is_market_deal** is 0.
            post_body: You should describe what's happened. - describe the situation in a nutshell. If you wish, you can describe the situation in more detail using the "Spoiler" function. - attach screenshots of correspondence. You may upload to the site [Imgur](https://imgur.com/upload) - for convenience, use Ctrl + V when uploading screenshots to the album. - other evidence; - notify the respondent about the complaint you created, familiarize him with hidden content Describe the situation in as much detail as possible.
            as_market_item_id: Market item id. Required if **as_is_market_deal** is 1.
            as_data: Contacts and wallets of the responder. Specify the known data about the responder, if any. Optional if **as_is_market_deal** is 0.
            currency: Currency of Claim.
            pay_claim: Pay claim fee now or later. (Only for **transfer_type** = **notsafe**)
            as_funds_receipt: Funds transfer receipt. Upload a receipt for the transfer of funds, use the "View receipt" button in your wallet. May be uploaded to [Imgur](https://imgur.com/upload). Write "no" if you have not paid. Required if **as_is_market_deal** is 0.
            as_tg_login_screenshot: Screenshot showing the respondent's Telegram login. If the correspondence was conducted in Telegram, upload a screenshot that will display the respondent's Telegram login against the background of your dialogue. The screenshot may be uploaded to [Imgur](https://imgur.com/upload). If the correspondence was conducted elsewhere, write "no".
            tags: Thread tags.
            hide_contacts: Hide contacts.
            allow_ask_hidden_content: Allow ask hidden content.
            reply_group: Allow to reply only users with chosen or higher group.
            comment_ignore_group: Allow commenting if user can't post in thread.
            dont_alert_followers: Don't alert followers about thread creation.
            schedule_date: Date to schedule thread creation (format: `DD-MM-YYYY`).
            schedule_time: Time to schedule thread creation (format: `HH:MM`).
            watch_thread_state: Watch thread state.
            watch_thread: Receive forum notifications of new posts in this thread.
            watch_thread_email: Receive email notifications of new posts in this thread.

        Docs: https://lolzteam.readme.io/reference/threadsclaim
        """
        return await self(
            ThreadsClaim(
                as_responder=as_responder,
                as_is_market_deal=as_is_market_deal,
                as_amount=as_amount,
                transfer_type=transfer_type,
                post_body=post_body,
                as_market_item_id=as_market_item_id,
                as_data=as_data,
                currency=currency,
                pay_claim=pay_claim,
                as_funds_receipt=as_funds_receipt,
                as_tg_login_screenshot=as_tg_login_screenshot,
                tags=tags,
                hide_contacts=hide_contacts,
                allow_ask_hidden_content=allow_ask_hidden_content,
                reply_group=reply_group,
                comment_ignore_group=comment_ignore_group,
                dont_alert_followers=dont_alert_followers,
                schedule_date=schedule_date,
                schedule_time=schedule_time,
                watch_thread_state=watch_thread_state,
                watch_thread=watch_thread,
                watch_thread_email=watch_thread_email,
            )
        )

    async def threads_create_contest(
        self,
        post_body: str,
        contest_type: ContestType,
        prize_type: PrizeType,
        require_like_count: int,
        require_total_like_count: int,
        title: str | None = None,
        title_en: str | None = None,
        length_value: int | None = None,
        length_option: LengthOption | None = None,
        count_winners: int | None = None,
        prize_data_money: float | None = None,
        is_money_places: bool | None = None,
        prize_data_places: tuple[float, ...] | None = None,
        prize_data_upgrade: int | None = None,
        secret_answer: str | None = None,
        tags: tuple[str, ...] | None = None,
        reply_group: int | None = None,
        comment_ignore_group: bool | None = None,
        dont_alert_followers: bool | None = None,
        hide_contacts: bool | None = None,
        allow_ask_hidden_content: bool | None = None,
        schedule_date: str | None = None,
        schedule_time: str | None = None,
        watch_thread_state: bool | None = None,
        watch_thread: bool | None = None,
        watch_thread_email: bool | None = None,
    ) -> Content:
        """Generated by forge — DO NOT EDIT. Create Contest.
        Sourced from the official OpenAPI spec (readme.io).
        Create a new contest.
        Required scopes:
        + **post**

        Args:
            post_body: Content of the new contest.
            contest_type: Contest type.
            prize_type: Prize type.
            require_like_count: Sympathies for this week.
            require_total_like_count: Sympathies for all time.
            title: Thread title. Can be skipped if **title_en** set.
            title_en: Thread english title. Can be skipped if **title** set.
            length_value: Giveaway duration value. The maximum duration is 3 days. Required if **contest_type** is **by_finish_date**.
            length_option: Giveaway duration type. The maximum duration is 3 days. Required if **contest_type** is **by_finish_date**.
            count_winners: Winner count (prize count). Optional if **prize_type** is **money**.
            prize_data_money: How much money will each winner receive. Optional if **prize_type** is **money**.
            is_money_places: Enable the distribution of money prizes by places. Optional if **prize_type** is **money**.
            prize_data_places: How much money will receive each place. Required if **is_money_places** is **1**.
            prize_data_upgrade: Which upgrade will each winner receive. Required if **prize_type** is **upgrades**.
            secret_answer: Secret answer of your account.
            tags: Thread tags.
            reply_group: Allow to reply only users with chosen or higher group.
            comment_ignore_group: Allow commenting if user can't post in thread.
            dont_alert_followers: Don't alert followers about thread creation.
            hide_contacts: Hide contacts.
            allow_ask_hidden_content: Allow ask hidden content.
            schedule_date: Date to schedule thread creation (format: `DD-MM-YYYY`).
            schedule_time: Time to schedule thread creation (format: `HH:MM`).
            watch_thread_state: Watch thread state.
            watch_thread: Receive forum notifications of new posts in this thread.
            watch_thread_email: Receive email notifications of new posts in this thread.

        Docs: https://lolzteam.readme.io/reference/threadscreatecontest
        """
        return await self(
            ThreadsCreateContest(
                post_body=post_body,
                contest_type=contest_type,
                prize_type=prize_type,
                require_like_count=require_like_count,
                require_total_like_count=require_total_like_count,
                title=title,
                title_en=title_en,
                length_value=length_value,
                length_option=length_option,
                count_winners=count_winners,
                prize_data_money=prize_data_money,
                is_money_places=is_money_places,
                prize_data_places=prize_data_places,
                prize_data_upgrade=prize_data_upgrade,
                secret_answer=secret_answer,
                tags=tags,
                reply_group=reply_group,
                comment_ignore_group=comment_ignore_group,
                dont_alert_followers=dont_alert_followers,
                hide_contacts=hide_contacts,
                allow_ask_hidden_content=allow_ask_hidden_content,
                schedule_date=schedule_date,
                schedule_time=schedule_time,
                watch_thread_state=watch_thread_state,
                watch_thread=watch_thread,
                watch_thread_email=watch_thread_email,
            )
        )

    async def threads_finish(self, thread_id: int) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Finish Contest.
        Sourced from the official OpenAPI spec (readme.io).
        Finishes a contest.
        Required scopes:
        + **post**

        Args:
            thread_id: Id of thread.

        Docs: https://lolzteam.readme.io/reference/threadsfinish
        """
        return await self(ThreadsFinish(thread_id=thread_id))

    async def threads_followed(
        self, total: bool | None = None, fields_include: tuple[FieldsInclude, ...] | None = None
    ) -> str:
        """Generated by forge — DO NOT EDIT. Get Followed Threads.
        Sourced from the official OpenAPI spec (readme.io).
        List of followed threads by current user.
        Required scopes:
        + **read**

        Args:
            total: If included in the request, only the thread count is returned as **threads_total**.
            fields_include: List of fields to include.

        Docs: https://lolzteam.readme.io/reference/threadsfollowed
        """
        return await self(ThreadsFollowed(total=total, fields_include=fields_include))

    async def threads_get(
        self, thread_id: int, fields_include: tuple[FieldsInclude, ...] | None = None
    ) -> Content:
        """Generated by forge — DO NOT EDIT. Get Thread.
        Sourced from the official OpenAPI spec (readme.io).
        Detail information of a thread.
        Required scopes:
        + **read**

        Args:
            thread_id: Id of thread.
            fields_include: List of fields to include.

        Docs: https://lolzteam.readme.io/reference/threadsget
        """
        return await self(ThreadsGet(thread_id=thread_id, fields_include=fields_include))

    async def threads_hide(self, thread_id: int) -> str:
        """Generated by forge — DO NOT EDIT. Hide Thread.
        Sourced from the official OpenAPI spec (readme.io).
        Hide a thread from your feed.
        Required scopes:
        + **post**

        Args:
            thread_id: Id of thread.

        Docs: https://lolzteam.readme.io/reference/threadshide
        """
        return await self(ThreadsHide(thread_id=thread_id))

    async def threads_list(
        self,
        forum_id: int | None = None,
        tab: str | None = None,
        state: State | None = None,
        period: Period | None = None,
        title: str | None = None,
        title_only: bool | None = None,
        creator_user_id: int | None = None,
        sticky: bool | None = None,
        prefix_ids: tuple[int, ...] | None = None,
        prefix_ids_not: tuple[int, ...] | None = None,
        thread_tag_id: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        order: Order | None = None,
        direction: Direction | None = None,
        thread_create_date: int | None = None,
        thread_update_date: int | None = None,
        fields_include: tuple[FieldsInclude, ...] | None = None,
    ) -> str:
        """Generated by forge — DO NOT EDIT. Get Threads.
        Sourced from the official OpenAPI spec (readme.io).
        List of threads in a forum (with pagination).
        Required scopes:
        + **read**

        Args:
            forum_id: Id of the containing forum.
            tab: Tab to get threads from.
            state: Thread state. Works only if **forum_id** is set.
            period: Filter to get only threads created within the selected period. Works only if **forum_id** is set.
            title: Thread title.
            title_only: Search only in titles.
            creator_user_id: Filter to get only threads created by the specified user.
            sticky: Filter to get only sticky or non-sticky threads. By default, all threads will be included and sticky ones will be at the top of the result on the first page. In mixed mode, sticky threads are not counted towards **threads_total** and does not affect pagination.
            prefix_ids: Filter to get only threads with the specified prefix.
            prefix_ids_not: Filter to get only threads without the specified prefix.
            thread_tag_id: Filter to get only threads with the specified tag.
            page: Page number of threads.
            limit: Number of threads in a page.
            order: Ordering of threads.
            direction: Direction of threads ordering.
            thread_create_date: Filter threads by creation date. Only works with 'thread_create_date' and 'thread_create_date_reverse' ordering.
            thread_update_date: Filter threads by update date. Only works with 'thread_update_date' and 'thread_update_date_reverse' ordering.
            fields_include: List of fields to include.

        Docs: https://lolzteam.readme.io/reference/threadslist
        """
        return await self(
            ThreadsList(
                forum_id=forum_id,
                tab=tab,
                state=state,
                period=period,
                title=title,
                title_only=title_only,
                creator_user_id=creator_user_id,
                sticky=sticky,
                prefix_ids=prefix_ids,
                prefix_ids_not=prefix_ids_not,
                thread_tag_id=thread_tag_id,
                page=page,
                limit=limit,
                order=order,
                direction=direction,
                thread_create_date=thread_create_date,
                thread_update_date=thread_update_date,
                fields_include=fields_include,
            )
        )

    async def threads_move(
        self,
        thread_id: int,
        node_id: str,
        title: str | None = None,
        title_en: str | None = None,
        prefix_id: tuple[int, ...] | None = None,
        apply_thread_prefix: bool | None = None,
        send_alert: bool | None = None,
    ) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Move Thread.
        Sourced from the official OpenAPI spec (readme.io).
        Move a thread to another forum.
        Required scopes:
        + **post**

        Args:
            thread_id: Id of thread.
            node_id: Forum id.
            title: Thread title.
            title_en: Thread title english.
            prefix_id: Prefix ids. Set "0" to remove all thread prefixes.
            apply_thread_prefix: Apply thread prefix.
            send_alert: Send a notification to users who are followed to target node.

        Docs: https://lolzteam.readme.io/reference/threadsmove
        """
        return await self(
            ThreadsMove(
                thread_id=thread_id,
                node_id=node_id,
                title=title,
                title_en=title_en,
                prefix_id=prefix_id,
                apply_thread_prefix=apply_thread_prefix,
                send_alert=send_alert,
            )
        )

    async def threads_navigation(self, thread_id: int) -> str:
        """Generated by forge — DO NOT EDIT. Get Navigation Elements.
        Sourced from the official OpenAPI spec (readme.io).
        List of navigation elements to reach the specified thread.
        Required scopes:
        + **read**

        Args:
            thread_id: Id of thread.

        Docs: https://lolzteam.readme.io/reference/threadsnavigation
        """
        return await self(ThreadsNavigation(thread_id=thread_id))

    async def threads_poll_get(self, thread_id: int) -> str:
        """Generated by forge — DO NOT EDIT. Get Poll.
        Sourced from the official OpenAPI spec (readme.io).
        Detail information of a poll.
        Required scopes:
        + **read**

        Args:
            thread_id: Id of thread.

        Docs: https://lolzteam.readme.io/reference/threadspollget
        """
        return await self(ThreadsPollGet(thread_id=thread_id))

    async def threads_poll_vote(
        self,
        thread_id: int,
        response_id: int | None = None,
        response_ids: tuple[int, ...] | None = None,
    ) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Vote Poll.
        Sourced from the official OpenAPI spec (readme.io).
        Vote on a thread poll.
        Required scopes:
        + **post**

        Args:
            thread_id: Id of thread.
            response_id: The id of the response to vote for. Can be skipped if **response_ids** set.
            response_ids: An array of ids of responses (if the poll allows multiple choices).

        Docs: https://lolzteam.readme.io/reference/threadspollvote
        """
        return await self(
            ThreadsPollVote(thread_id=thread_id, response_id=response_id, response_ids=response_ids)
        )

    async def threads_recent(
        self,
        days: int | None = None,
        limit: int | None = None,
        forum_id: int | None = None,
        data_limit: int | None = None,
    ) -> str:
        """Generated by forge — DO NOT EDIT. Get Recent Threads.
        Sourced from the official OpenAPI spec (readme.io).
        List of recent threads.
        Required scopes:
        + **read**

        Args:
            days: Maximum number of days to search for threads.
            limit: Maximum number of result threads. The limit may get decreased if the value is too large.
            forum_id: Id of the container forum to search for threads. Child forums of the specified forum will be included in the search.
            data_limit: Number of thread data to be returned. Default value is 20.

        Docs: https://lolzteam.readme.io/reference/threadsrecent
        """
        return await self(
            ThreadsRecent(days=days, limit=limit, forum_id=forum_id, data_limit=data_limit)
        )

    async def threads_unfollow(self, thread_id: int) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Unfollow Thread.
        Sourced from the official OpenAPI spec (readme.io).
        Unfollow a thread.
        Required scopes:
        + **post**

        Args:
            thread_id: Id of thread.

        Docs: https://lolzteam.readme.io/reference/threadsunfollow
        """
        return await self(ThreadsUnfollow(thread_id=thread_id))

    async def threads_unread(
        self, limit: int | None = None, forum_id: int | None = None, data_limit: int | None = None
    ) -> str:
        """Generated by forge — DO NOT EDIT. Get Unread Threads.
        Sourced from the official OpenAPI spec (readme.io).
        List of unread threads (must be logged in).
        Required scopes:
        + **read**

        Args:
            limit: Maximum number of result threads. The limit may get decreased if the value is too large (depending on the system configuration).
            forum_id: Id of the container forum to search for threads. Child forums of the specified forum will be included in the search.
            data_limit: Number of thread data to be returned. Default value is 20.

        Docs: https://lolzteam.readme.io/reference/threadsunread
        """
        return await self(ThreadsUnread(limit=limit, forum_id=forum_id, data_limit=data_limit))

    async def threads_unstar(self, thread_id: int) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Unbookmark Thread.
        Sourced from the official OpenAPI spec (readme.io).
        Unbookmark a thread.
        Required scopes:
        + **post**

        Args:
            thread_id: Id of thread.

        Docs: https://lolzteam.readme.io/reference/threadsunstar
        """
        return await self(ThreadsUnstar(thread_id=thread_id))

    async def users_avatar_crop(
        self, user_id: str, x: int | None = None, y: int | None = None, crop: int | None = None
    ) -> str:
        """Generated by forge — DO NOT EDIT. Crop Avatar.
        Sourced from the official OpenAPI spec (readme.io).
        Crop avatar for a user.
        Required scopes:
        + **post**

        Args:
            user_id: User ID. > You can use shortlink `me` to interact with your profile.
            x: The starting point of the selection by width. Default value - 0
            y: The starting point of the selection by height. Default value - 0
            crop: Selection size.

        Docs: https://lolzteam.readme.io/reference/usersavatarcrop
        """
        return await self(UsersAvatarCrop(user_id=user_id, x=x, y=y, crop=crop))

    async def users_avatar_upload(
        self,
        user_id: str,
        avatar: Media,
        x: int | None = None,
        y: int | None = None,
        crop: int | None = None,
    ) -> str:
        """Generated by forge — DO NOT EDIT. Upload Avatar.
        Sourced from the official OpenAPI spec (readme.io).
        Upload avatar for a user.
        Required scopes:
        + **post**

        Args:
            user_id: User ID. > You can use shortlink `me` to interact with your profile.
            avatar: Binary data of the avatar.
            x: The starting point of the selection by width. Default value - 0
            y: The starting point of the selection by height. Default value - 0
            crop: Selection size.

        Docs: https://lolzteam.readme.io/reference/usersavatarupload
        """
        return await self(UsersAvatarUpload(user_id=user_id, avatar=avatar, x=x, y=y, crop=crop))

    async def users_background_crop(
        self, user_id: str, x: int | None = None, y: int | None = None, crop: int | None = None
    ) -> str:
        """Generated by forge — DO NOT EDIT. Crop Background.
        Sourced from the official OpenAPI spec (readme.io).
        Crop background for a user.
        Required scopes:
        + **post**

        Args:
            user_id: User ID. > You can use shortlink `me` to interact with your profile.
            x: The starting point of the selection by width. Default value - 0
            y: The starting point of the selection by height. Default value - 0
            crop: Selection size.

        Docs: https://lolzteam.readme.io/reference/usersbackgroundcrop
        """
        return await self(UsersBackgroundCrop(user_id=user_id, x=x, y=y, crop=crop))

    async def users_background_upload(
        self,
        user_id: str,
        background: Media,
        x: int | None = None,
        y: int | None = None,
        crop: int | None = None,
    ) -> str:
        """Generated by forge — DO NOT EDIT. Upload Background.
        Sourced from the official OpenAPI spec (readme.io).
        Upload background for a user.
        Required scopes:
        + **post**

        Args:
            user_id: User ID. > You can use shortlink `me` to interact with your profile.
            background: Binary data of the background. Background image must be 1920x1080 pixels
            x: The starting point of the selection by width. Default value - 0
            y: The starting point of the selection by height. Default value - 0
            crop: Selection size.

        Docs: https://lolzteam.readme.io/reference/usersbackgroundupload
        """
        return await self(
            UsersBackgroundUpload(user_id=user_id, background=background, x=x, y=y, crop=crop)
        )

    async def users_claims(
        self, user_id: str, type: Type | None = None, claim_state: ClaimState | None = None
    ) -> UsersClaimsResponse:
        """Generated by forge — DO NOT EDIT. Get User Claims.
        Sourced from the official OpenAPI spec (readme.io).
        Get user claims.
        Required scopes:
        + **read**

        Args:
            user_id: User ID. > You can use shortlink `me` to interact with your profile.
            type: Filter claims by their type.
            claim_state: Filter claims by their state.

        Docs: https://lolzteam.readme.io/reference/usersclaims
        """
        return await self(UsersClaims(user_id=user_id, type=type, claim_state=claim_state))

    async def users_contents(
        self, user_id: str, page: int | None = None, limit: int | None = None
    ) -> str:
        """Generated by forge — DO NOT EDIT. Get Contents.
        Sourced from the official OpenAPI spec (readme.io).
        List of contents created by user (with pagination).
        Required scopes:
        + **read**

        Args:
            user_id: User ID. > You can use shortlink `me` to interact with your profile.
            page: Page number of contents.
            limit: Number of contents in a page.

        Docs: https://lolzteam.readme.io/reference/userscontents
        """
        return await self(UsersContents(user_id=user_id, page=page, limit=limit))

    async def users_fields(self) -> str:
        """Generated by forge — DO NOT EDIT. Get User Fields.
        Sourced from the official OpenAPI spec (readme.io).
        List of user fields.
        Required scopes:
        + **read**

        Docs: https://lolzteam.readme.io/reference/usersfields
        """
        return await self(UsersFields())

    async def users_find(
        self,
        username: str | None = None,
        custom_fields: dict[str, Any] | None = None,
        fields_include: tuple[FieldsInclude, ...] | None = None,
    ) -> str:
        """Generated by forge — DO NOT EDIT. Find Users.
        Sourced from the official OpenAPI spec (readme.io).
        List of users filtered by username, email or custom fields.
        Required scopes:
        + **read**

        Args:
            username: Username to filter. Usernames start with the query will be returned.
            custom_fields: Custom fields to filter. Example: **custom_fields[telegram]=telegramLogin**.
            fields_include: List of fields to include.

        Docs: https://lolzteam.readme.io/reference/usersfind
        """
        return await self(
            UsersFind(username=username, custom_fields=custom_fields, fields_include=fields_include)
        )

    async def users_followings(
        self,
        user_id: str,
        order: Order | None = None,
        page: int | None = None,
        limit: int | None = None,
    ) -> str:
        """Generated by forge — DO NOT EDIT. Get Followed Users By User.
        Sourced from the official OpenAPI spec (readme.io).
        List of users whom are followed by a user.
        Required scopes:
        + **read**

        Args:
            user_id: User ID. > You can use shortlink `me` to interact with your profile.
            order: Ordering of users.
            page: Page number of users.
            limit: Number of users in a page.

        Docs: https://lolzteam.readme.io/reference/usersfollowings
        """
        return await self(UsersFollowings(user_id=user_id, order=order, page=page, limit=limit))

    async def users_get(
        self, user_id: str, fields_include: tuple[FieldsInclude, ...] | None = None
    ) -> SearchAllUser:
        """Generated by forge — DO NOT EDIT. Get User.
        Sourced from the official OpenAPI spec (readme.io).
        Detail information of a user.
        Required scopes:
        + **read**
        + **basic**

        Args:
            user_id: User ID. > You can use shortlink `me` to interact with your profile.
            fields_include: List of fields to include.

        Docs: https://lolzteam.readme.io/reference/usersget
        """
        return await self(UsersGet(user_id=user_id, fields_include=fields_include))

    async def users_ignored(self, total: bool | None = None) -> list[UsersIgnoredUser]:
        """Generated by forge — DO NOT EDIT. Get Ignored Users.
        Sourced from the official OpenAPI spec (readme.io).
        List of ignored users of current user.
        Required scopes:
        + **read**

        Args:
            total: If included in the request, only the user count is returned as **users_total**.

        Docs: https://lolzteam.readme.io/reference/usersignored
        """
        return await self(UsersIgnored(total=total))

    async def users_likes(
        self,
        user_id: str,
        node_id: int | None = None,
        like_type: LikeType | None = None,
        type: Type | None = None,
        page: int | None = None,
        content_type: ContentType | None = None,
        search_user_id: int | None = None,
        stats: bool | None = None,
    ) -> UsersLikesResponse:
        """Generated by forge — DO NOT EDIT. Get User Likes.
        Sourced from the official OpenAPI spec (readme.io).
        Get information about user likes.
        Required scopes:
        + **read**

        Args:
            user_id: User ID. > You can use shortlink `me` to interact with your profile.
            node_id: Filter by forum section.
            like_type: Like type.
            type: Likes type.
            page: Page number.
            content_type: Content type.
            search_user_id: Get only likes from specified user.
            stats: Show weekly statistics.

        Docs: https://lolzteam.readme.io/reference/userslikes
        """
        return await self(
            UsersLikes(
                user_id=user_id,
                node_id=node_id,
                like_type=like_type,
                type=type,
                page=page,
                content_type=content_type,
                search_user_id=search_user_id,
                stats=stats,
            )
        )

    async def users_list(
        self,
        page: int | None = None,
        limit: int | None = None,
        fields_include: tuple[FieldsInclude, ...] | None = None,
    ) -> UsersListResponse:
        """Generated by forge — DO NOT EDIT. Get Users.
        Sourced from the official OpenAPI spec (readme.io).
        List of users (with pagination).
        Required scopes:
        + **read**

        Args:
            page: Page number of users.
            limit: Number of users in a page.
            fields_include: List of fields to include.

        Docs: https://lolzteam.readme.io/reference/userslist
        """
        return await self(UsersList(page=page, limit=limit, fields_include=fields_include))

    async def users_sa_reset(self) -> UsersSAResetResponse:
        """Generated by forge — DO NOT EDIT. Reset Secret Answer.
        Sourced from the official OpenAPI spec (readme.io).
        Request a reset of the secret answer for the account.
        Required scopes:
        + **post**

        Docs: https://lolzteam.readme.io/reference/userssareset
        """
        return await self(UsersSAReset())

    async def users_secret_answer_types(self) -> list[UsersSecretAnswerTypesData]:
        """Generated by forge — DO NOT EDIT. Get Secret Answer Types.
        Sourced from the official OpenAPI spec (readme.io).
        Get available secret answer types for user account security.
        Required scopes:
        + **read**

        Docs: https://lolzteam.readme.io/reference/userssecretanswertypes
        """
        return await self(UsersSecretAnswerTypes())

    async def users_trophies(self, user_id: str) -> UsersTrophiesResponse:
        """Generated by forge — DO NOT EDIT. Get Trophies.
        Sourced from the official OpenAPI spec (readme.io).
        List of user trophies.
        Required scopes:
        + **read**

        Args:
            user_id: User ID. > You can use shortlink `me` to interact with your profile.

        Docs: https://lolzteam.readme.io/reference/userstrophies
        """
        return await self(UsersTrophies(user_id=user_id))

    async def users_unfollow(self, user_id: str) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Unfollow User.
        Sourced from the official OpenAPI spec (readme.io).
        Unfollow a user.
        Required scopes:
        + **post**

        Args:
            user_id: User ID. > You can use shortlink `me` to interact with your profile.

        Docs: https://lolzteam.readme.io/reference/usersunfollow
        """
        return await self(UsersUnfollow(user_id=user_id))

    async def users_unignore(self, user_id: str) -> ForumStatusMessageResponse:
        """Generated by forge — DO NOT EDIT. Unignore User.
        Sourced from the official OpenAPI spec (readme.io).
        Stop ignoring a user.
        Required scopes:
        + **post**

        Args:
            user_id: User ID. > You can use shortlink `me` to interact with your profile.

        Docs: https://lolzteam.readme.io/reference/usersunignore
        """
        return await self(UsersUnignore(user_id=user_id))
