"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from enum import StrEnum


class Origin(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    BRUTE = "brute"
    PHISHING = "phishing"
    STEALER = "stealer"
    AUTOREG = "autoreg"
    PERSONAL = "personal"
    RESALE = "resale"
    DUMMY = "dummy"
    SELF_REGISTRATION = "self_registration"
    RETRIEVE_VIA_SUPPORT = "retrieve_via_support"


class NotOrigin(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    BRUTE = "brute"
    PHISHING = "phishing"
    STEALER = "stealer"
    AUTOREG = "autoreg"
    PERSONAL = "personal"
    RESALE = "resale"
    DUMMY = "dummy"
    SELF_REGISTRATION = "self_registration"
    RETRIEVE_VIA_SUPPORT = "retrieve_via_support"


class EmailProvider(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    OTHER = "other"
    RAMBLER = "rambler"
    OUTLOOK = "outlook"
    FIRSTMAIL = "firstmail"
    NOTLETTERS = "notletters"
    MAIL_RU = "mail_ru"


class NotEmailProvider(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    OTHER = "other"
    RAMBLER = "rambler"
    OUTLOOK = "outlook"
    FIRSTMAIL = "firstmail"
    NOTLETTERS = "notletters"
    MAIL_RU = "mail_ru"


class EmailType(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    NATIVE = "native"
    NO = "no"
    AUTOREG = "autoreg"
    MARKET = "market"
    NO_MARKET = "no_market"


class NitroType(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    BASIC = "basic"
    CLASSIC = "classic"
    FULL = "full"
    NONE = "none"
    TRIAL = "trial"


class NitroPeriod(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DAY = "day"
    MONTH = "month"
    YEAR = "year"


class Badge(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    BUG_HUNTER = "bug_hunter"
    BUG_HUNTER_LEVEL_2 = "bug_hunter_level_2"
    CERTIFICATED_MODERATOR = "certificated_moderator"
    EARLY_SUPPORTER = "early_supporter"
    HYPESQUAD = "hypesquad"
    PARTNER = "partner"
    STAFF = "staff"
    VERIFIED_DEVELOPER = "verified_developer"


class Condition(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    CLEANED = "cleaned"
    EMPTY = "empty"
    NOSPAM = "nospam"
    SPAM = "spam"


class RegPeriod(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DAY = "day"
    MONTH = "month"
    YEAR = "year"


class AlRankMin(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_0 = "0"
    V_1000 = "1000"
    V_10600 = "10600"
    V_11400 = "11400"
    V_12300 = "12300"
    V_13200 = "13200"
    V_14100 = "14100"
    V_1500 = "1500"
    V_15000 = "15000"
    V_2000 = "2000"
    V_250 = "250"
    V_2500 = "2500"
    V_3000 = "3000"
    V_3600 = "3600"
    V_4200 = "4200"
    V_4800 = "4800"
    V_500 = "500"
    V_5400 = "5400"
    V_6100 = "6100"
    V_6800 = "6800"
    V_750 = "750"
    V_7500 = "7500"
    V_8200 = "8200"
    V_9000 = "9000"
    V_9800 = "9800"


class AlRankMax(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_10599 = "10599"
    V_11399 = "11399"
    V_12299 = "12299"
    V_13199 = "13199"
    V_14099 = "14099"
    V_1499 = "1499"
    V_14999 = "14999"
    V_1999 = "1999"
    V_249 = "249"
    V_2499 = "2499"
    V_2999 = "2999"
    V_3599 = "3599"
    V_4199 = "4199"
    V_4799 = "4799"
    V_499 = "499"
    V_500000 = "500000"
    V_5399 = "5399"
    V_6099 = "6099"
    V_6799 = "6799"
    V_749 = "749"
    V_7499 = "7499"
    V_8199 = "8199"
    V_8999 = "8999"
    V_9799 = "9799"
    V_999 = "999"


class Subscription(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    EA_PLAY = "EA Play"
    EA_PLAY_PRO = "EA Play Pro"
    CLAUDE_MAX_20X = "claude_max_20x"
    CLAUDE_MAX_5X = "claude_max_5x"
    CLAUDE_PRO = "claude_pro"
    DISCORD_NITRO = "discord_nitro"
    DISCORD_NITRO_BASIC = "discord_nitro_basic"
    DISCORD_NITRO_TRIAL = "discord_nitro_trial"
    TELEGRAM_PREMIUM = "telegram_premium"
    CHATGPTEDUPLAN = "chatgpteduplan"
    CHATGPTENTERPRISEPLAN = "chatgptenterpriseplan"
    CHATGPTGOPLAN = "chatgptgoplan"
    CHATGPTPLUSPLAN = "chatgptplusplan"
    CHATGPTPRO = "chatgptpro"
    CHATGPTPROLITE = "chatgptprolite"
    CHATGPTQUORUMPLAN = "chatgptquorumplan"
    CLAUDE_RAVEN = "claude_raven"
    CURSOR_ENTERPRISE = "cursor_enterprise"
    CURSOR_PRO = "cursor_pro"
    CURSOR_PRO_PLUS = "cursor_pro_plus"
    CURSOR_ULTRA = "cursor_ultra"
    GROK_ENTERPRISE = "grok_enterprise"
    GROK_PRO = "grok_pro"
    GROK_SUPER_LITE = "grok_super_lite"
    GROK_SUPER_PRO = "grok_super_pro"
    PC_GAME_PASS = "PC Game Pass"
    XBOX_GAME_PASS_ULTIMATE = "Xbox Game Pass Ultimate"
    BLACKBIRD = "Blackbird"
    ROBLOX_PLUS1000 = "RobloxPlus1000"
    ROBLOX_PLUS2000 = "RobloxPlus2000"
    ROBLOX_PLUS500 = "RobloxPlus500"
    ROBLOX_PREMIUM1000 = "RobloxPremium1000"
    ROBLOX_PREMIUM100012_MONTHS = "RobloxPremium100012Months"
    ROBLOX_PREMIUM1000_ONE_MONTH = "RobloxPremium1000OneMonth"
    ROBLOX_PREMIUM2200 = "RobloxPremium2200"
    ROBLOX_PREMIUM2200_ONE_MONTH = "RobloxPremium2200OneMonth"
    ROBLOX_PREMIUM450 = "RobloxPremium450"
    ROBLOX_PREMIUM450_ONE_MONTH = "RobloxPremium450OneMonth"
    BASIC = "basic"
    PREMIUM = "premium"
    PREMIUM_ANYWHERE = "premiumAnywhere"


class SubscriptionPeriod(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DAY = "day"
    MONTH = "month"
    YEAR = "year"


class Region(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    AF = "af"
    AS = "as"
    CIS = "cis"
    EU = "eu"
    ME = "me"
    OC = "oc"
    US = "us"
    ASIA = "asia"
    CHT = "cht"
    USA = "usa"
    NA = "na"
    RU = "ru"


class Version(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    EDGE_OF_DARKNESS = "edge_of_darkness"
    LEFT_BEHIND = "left_behind"
    PREPARE_FOR_ESCAPE = "prepare_for_escape"
    STANDARD = "standard"
    UNHEARD_EDITION = "unheard_edition"


class Side(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    BEAR = "Bear"
    SAVAGE = "Savage"


class Sc(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_544A11AC4BDC2D470E8B456A = "544a11ac4bdc2d470e8b456a"
    V_5857A8B324597729AB0A0E7D = "5857a8b324597729ab0a0e7d"
    V_5857A8BC2459772BAD15DB29 = "5857a8bc2459772bad15db29"
    V_59DB794186F77448BC595262 = "59db794186f77448bc595262"
    V_5C093CA986F7740A1867AB12 = "5c093ca986f7740a1867ab12"
    V_665EE77CCF2D642E98220BCA = "665ee77ccf2d642e98220bca"
    V_676008DB84E242067D0DC4C9 = "676008db84e242067d0dc4c9"


class LastRaidPeriod(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DAY = "day"
    MONTH = "month"
    YEAR = "year"


class Platform(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    EPIC = "Epic"
    EPIC_ANDROID = "EpicAndroid"
    EPIC_IOS = "EpicIOS"
    EPIC_PC = "EpicPC"
    EPIC_PC_KOREA = "EpicPCKorea"
    GOOGLE_PLAY = "GooglePlay"
    IOS_APP_STORE = "IOSAppStore"
    LIVE = "Live"
    NINTENDO = "Nintendo"
    ONE_STORE_KOREA = "OneStoreKorea"
    PSN = "PSN"
    SAMSUNG = "Samsung"


class LastTransDatePeriod(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DAY = "day"
    MONTH = "month"
    YEAR = "year"


class Stw(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DELUXE = "Deluxe"
    LIMITED = "Limited"
    PRE_ORDER = "Pre-Order"
    STANDARD = "Standard"
    SUPER_DELUXE = "Super Deluxe"
    ULTIMATE = "Ultimate"


class NotStw(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DELUXE = "Deluxe"
    LIMITED = "Limited"
    PRE_ORDER = "Pre-Order"
    STANDARD = "Standard"
    SUPER_DELUXE = "Super Deluxe"
    ULTIMATE = "Ultimate"


class Edition(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    BASE = "base"
    DELUXE = "deluxe"
    FOUNDER = "founder"


class Service(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    CHATGPT = "chatgpt"
    CLAUDE = "claude"
    CURSOR = "cursor"
    GROK = "grok"
    KIMI = "kimi"
    ADGUARD_VPN = "AdguardVPN"
    PIAVPN = "PIAVPN"
    CYBERGHOST_VPN = "cyberghostVPN"
    HOTSPOT_SHIELD_VPN = "hotspotShieldVPN"
    MULLVAD_VPN = "mullvadVPN"
    PLANET_VPN = "planetVPN"
    PURE_VPN = "pureVPN"
    TUNNELBEAR_VPN = "tunnelbearVPN"
    ULTRA_VPN = "ultraVPN"
    VANISH_VPN = "vanishVPN"
    VYPR_VPN = "vyprVPN"
    WINDSCRIBE_VPN = "windscribeVPN"


class NotService(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    CHATGPT = "chatgpt"
    CLAUDE = "claude"
    CURSOR = "cursor"
    GROK = "grok"
    KIMI = "kimi"


class NotRegion(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    ASIA = "asia"
    CHT = "cht"
    EU = "eu"
    USA = "usa"
    NA = "na"
    RU = "ru"


class MihoyoGame(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    GENSHIN_IMPACT = "genshin-impact"
    HONKAI_STAR_RAIL = "honkai-star-rail"
    ZENLESS_ZONE_ZERO = "zenless-zone-zero"


class RankHypixel(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    MVP = "MVP"
    VIP = "VIP"
    YOUTUBE = "YOUTUBE"


class LastLoginHypixelPeriod(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DAY = "day"
    MONTH = "month"
    YEAR = "year"


class Rmin(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_10 = "10"
    V_11 = "11"
    V_12 = "12"
    V_13 = "13"
    V_14 = "14"
    V_15 = "15"
    V_16 = "16"
    V_17 = "17"
    V_18 = "18"
    V_19 = "19"
    V_20 = "20"
    V_21 = "21"
    V_22 = "22"
    V_23 = "23"
    V_24 = "24"
    V_25 = "25"
    V_26 = "26"
    V_27 = "27"
    V_3 = "3"
    V_4 = "4"
    V_5 = "5"
    V_6 = "6"
    V_7 = "7"
    V_8 = "8"
    V_9 = "9"


class Rmax(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_10 = "10"
    V_11 = "11"
    V_12 = "12"
    V_13 = "13"
    V_14 = "14"
    V_15 = "15"
    V_16 = "16"
    V_17 = "17"
    V_18 = "18"
    V_19 = "19"
    V_20 = "20"
    V_21 = "21"
    V_22 = "22"
    V_23 = "23"
    V_24 = "24"
    V_25 = "25"
    V_26 = "26"
    V_27 = "27"
    V_3 = "3"
    V_4 = "4"
    V_5 = "5"
    V_6 = "6"
    V_7 = "7"
    V_8 = "8"
    V_9 = "9"


class LastRmin(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_10 = "10"
    V_11 = "11"
    V_12 = "12"
    V_13 = "13"
    V_14 = "14"
    V_15 = "15"
    V_16 = "16"
    V_17 = "17"
    V_18 = "18"
    V_19 = "19"
    V_20 = "20"
    V_21 = "21"
    V_22 = "22"
    V_23 = "23"
    V_24 = "24"
    V_25 = "25"
    V_26 = "26"
    V_27 = "27"
    V_3 = "3"
    V_4 = "4"
    V_5 = "5"
    V_6 = "6"
    V_7 = "7"
    V_8 = "8"
    V_9 = "9"


class LastRmax(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_10 = "10"
    V_11 = "11"
    V_12 = "12"
    V_13 = "13"
    V_14 = "14"
    V_15 = "15"
    V_16 = "16"
    V_17 = "17"
    V_18 = "18"
    V_19 = "19"
    V_20 = "20"
    V_21 = "21"
    V_22 = "22"
    V_23 = "23"
    V_24 = "24"
    V_25 = "25"
    V_26 = "26"
    V_27 = "27"
    V_3 = "3"
    V_4 = "4"
    V_5 = "5"
    V_6 = "6"
    V_7 = "7"
    V_8 = "8"
    V_9 = "9"


class PreviousRmin(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_10 = "10"
    V_11 = "11"
    V_12 = "12"
    V_13 = "13"
    V_14 = "14"
    V_15 = "15"
    V_16 = "16"
    V_17 = "17"
    V_18 = "18"
    V_19 = "19"
    V_20 = "20"
    V_21 = "21"
    V_22 = "22"
    V_23 = "23"
    V_24 = "24"
    V_25 = "25"
    V_26 = "26"
    V_27 = "27"
    V_3 = "3"
    V_4 = "4"
    V_5 = "5"
    V_6 = "6"
    V_7 = "7"
    V_8 = "8"
    V_9 = "9"


class PreviousRmax(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_10 = "10"
    V_11 = "11"
    V_12 = "12"
    V_13 = "13"
    V_14 = "14"
    V_15 = "15"
    V_16 = "16"
    V_17 = "17"
    V_18 = "18"
    V_19 = "19"
    V_20 = "20"
    V_21 = "21"
    V_22 = "22"
    V_23 = "23"
    V_24 = "24"
    V_25 = "25"
    V_26 = "26"
    V_27 = "27"
    V_3 = "3"
    V_4 = "4"
    V_5 = "5"
    V_6 = "6"
    V_7 = "7"
    V_8 = "8"
    V_9 = "9"


class ValorantRankType(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    RANKED = "ranked"
    RANKED_READY = "ranked_ready"
    UNRATED = "unrated"


class LolRank(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    UNRANKED = "Unranked"
    IRON_IV = "IRON IV"
    IRON_III = "IRON III"
    IRON_II = "IRON II"
    IRON_I = "IRON I"
    BRONZE_IV = "BRONZE IV"
    BRONZE_III = "BRONZE III"
    BRONZE_II = "BRONZE II"
    BRONZE_I = "BRONZE I"
    SILVER_IV = "SILVER IV"
    SILVER_III = "SILVER III"
    SILVER_II = "SILVER II"
    SILVER_I = "SILVER I"
    GOLD_IV = "GOLD IV"
    GOLD_III = "GOLD III"
    GOLD_II = "GOLD II"
    GOLD_I = "GOLD I"
    PLATINUM_IV = "PLATINUM IV"
    PLATINUM_III = "PLATINUM III"
    PLATINUM_II = "PLATINUM II"
    PLATINUM_I = "PLATINUM I"
    EMERALD_IV = "EMERALD IV"
    EMERALD_III = "EMERALD III"
    EMERALD_II = "EMERALD II"
    EMERALD_I = "EMERALD I"
    DIAMOND_IV = "DIAMOND IV"
    DIAMOND_III = "DIAMOND III"
    DIAMOND_II = "DIAMOND II"
    DIAMOND_I = "DIAMOND I"
    MASTER_I = "MASTER I"
    GRANDMASTER_I = "GRANDMASTER I"
    CHALLENGER_I = "CHALLENGER I"


class RiotGame(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    LEAGUE_OF_LEGENDS = "league-of-legends"
    VALORANT = "valorant"


class WingmanRmin(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_1 = "1"
    V_10 = "10"
    V_11 = "11"
    V_12 = "12"
    V_13 = "13"
    V_14 = "14"
    V_15 = "15"
    V_16 = "16"
    V_17 = "17"
    V_18 = "18"
    V_2 = "2"
    V_3 = "3"
    V_4 = "4"
    V_5 = "5"
    V_6 = "6"
    V_7 = "7"
    V_8 = "8"
    V_9 = "9"


class WingmanRmax(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_1 = "1"
    V_10 = "10"
    V_11 = "11"
    V_12 = "12"
    V_13 = "13"
    V_14 = "14"
    V_15 = "15"
    V_16 = "16"
    V_17 = "17"
    V_18 = "18"
    V_2 = "2"
    V_3 = "3"
    V_4 = "4"
    V_5 = "5"
    V_6 = "6"
    V_7 = "7"
    V_8 = "8"
    V_9 = "9"


class InvGame(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_232090 = "232090"
    V_252490 = "252490"
    V_304930 = "304930"
    V_322330 = "322330"
    V_440 = "440"
    V_570 = "570"
    V_578080 = "578080"
    V_730 = "730"
    V_753 = "753"


class LastTransDatePeriodLater(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DAY = "day"
    MONTH = "month"
    YEAR = "year"


class Cs2MapRank(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_1 = "1"
    V_10 = "10"
    V_11 = "11"
    V_12 = "12"
    V_13 = "13"
    V_14 = "14"
    V_15 = "15"
    V_16 = "16"
    V_17 = "17"
    V_18 = "18"
    V_19 = "19"
    V_2 = "2"
    V_20 = "20"
    V_21 = "21"
    V_22 = "22"
    V_23 = "23"
    V_24 = "24"
    V_25 = "25"
    V_26 = "26"
    V_27 = "27"
    V_3 = "3"
    V_4 = "4"
    V_5 = "5"
    V_6 = "6"
    V_7 = "7"
    V_8 = "8"
    V_9 = "9"


class Cs2MapRmin(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_1 = "1"
    V_10 = "10"
    V_11 = "11"
    V_12 = "12"
    V_13 = "13"
    V_14 = "14"
    V_15 = "15"
    V_16 = "16"
    V_17 = "17"
    V_18 = "18"
    V_2 = "2"
    V_3 = "3"
    V_4 = "4"
    V_5 = "5"
    V_6 = "6"
    V_7 = "7"
    V_8 = "8"
    V_9 = "9"


class Cs2MapRmax(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_1 = "1"
    V_10 = "10"
    V_11 = "11"
    V_12 = "12"
    V_13 = "13"
    V_14 = "14"
    V_15 = "15"
    V_16 = "16"
    V_17 = "17"
    V_18 = "18"
    V_2 = "2"
    V_3 = "3"
    V_4 = "4"
    V_5 = "5"
    V_6 = "6"
    V_7 = "7"
    V_8 = "8"
    V_9 = "9"


class D2LastMatchDatePeriod(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DAY = "day"
    MONTH = "month"
    YEAR = "year"


class RegAfterPeriod(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DAY = "day"
    MONTH = "month"
    YEAR = "year"


class D2LastMatchDateLaterPeriod(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DAY = "day"
    MONTH = "month"
    YEAR = "year"


class SupercellGame(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    BRAWL_STARS = "brawl-stars"
    CLASH_OF_CLANS = "clash-of-clans"
    CLASH_ROYALE = "clash-royale"


class PremiumExpirationPeriod(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DAY = "day"
    MONTH = "month"
    YEAR = "year"


class BirthdayPeriod(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DAY = "day"
    MONTH = "month"
    YEAR = "year"


class BirthdayAfterPeriod(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    DAY = "day"
    MONTH = "month"
    YEAR = "year"


class R6RankMin(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_1 = "1"
    V_1001 = "1001"
    V_1100 = "1100"
    V_1200 = "1200"
    V_1300 = "1300"
    V_1400 = "1400"
    V_1500 = "1500"
    V_1600 = "1600"
    V_1700 = "1700"
    V_1800 = "1800"
    V_1900 = "1900"
    V_2000 = "2000"
    V_2100 = "2100"
    V_2200 = "2200"
    V_2300 = "2300"
    V_2400 = "2400"
    V_2500 = "2500"
    V_2600 = "2600"
    V_2700 = "2700"
    V_2800 = "2800"
    V_2900 = "2900"
    V_3000 = "3000"
    V_3100 = "3100"
    V_3200 = "3200"
    V_3300 = "3300"
    V_3400 = "3400"
    V_3500 = "3500"
    V_3600 = "3600"
    V_3700 = "3700"
    V_3800 = "3800"
    V_3900 = "3900"
    V_4000 = "4000"
    V_4100 = "4100"
    V_4200 = "4200"
    V_4300 = "4300"
    V_4400 = "4400"
    V_4500 = "4500"


class R6RankMax(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_1000 = "1000"
    V_1099 = "1099"
    V_1199 = "1199"
    V_1299 = "1299"
    V_1399 = "1399"
    V_1499 = "1499"
    V_1599 = "1599"
    V_1699 = "1699"
    V_1799 = "1799"
    V_1899 = "1899"
    V_1999 = "1999"
    V_2099 = "2099"
    V_2199 = "2199"
    V_2299 = "2299"
    V_2399 = "2399"
    V_2499 = "2499"
    V_2599 = "2599"
    V_2699 = "2699"
    V_2799 = "2799"
    V_2899 = "2899"
    V_2999 = "2999"
    V_3099 = "3099"
    V_3199 = "3199"
    V_3299 = "3299"
    V_3399 = "3399"
    V_3499 = "3499"
    V_3599 = "3599"
    V_3699 = "3699"
    V_3799 = "3799"
    V_3899 = "3899"
    V_3999 = "3999"
    V_4099 = "4099"
    V_4199 = "4199"
    V_4299 = "4299"
    V_4399 = "4399"
    V_4499 = "4499"
    V_999999 = "999999"


class ClanRole(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    COMMANDER = "commander"
    EXECUTIVE_OFFICER = "executive_officer"
    PERSONNEL_OFFICER = "personnel_officer"
    COMBAT_OFFICER = "combat_officer"
    INTELLIGENCE_OFFICER = "intelligence_officer"
    QUARTERMASTER = "quartermaster"
    RECRUITMENT_OFFICER = "recruitment_officer"
    JUNIOR_OFFICER = "junior_officer"
    PRIVATE = "private"
    RECRUIT = "recruit"
    RESERVIST = "reservist"


class NotClanRole(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    COMMANDER = "commander"
    EXECUTIVE_OFFICER = "executive_officer"
    PERSONNEL_OFFICER = "personnel_officer"
    COMBAT_OFFICER = "combat_officer"
    INTELLIGENCE_OFFICER = "intelligence_officer"
    QUARTERMASTER = "quartermaster"
    RECRUITMENT_OFFICER = "recruitment_officer"
    JUNIOR_OFFICER = "junior_officer"
    PRIVATE = "private"
    RECRUIT = "recruit"
    RESERVIST = "reservist"


class Type(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    ITEMS = "items"
    ORDERS = "orders"
    MARKET = "market"
    NOMARKET = "nomarket"
    SKINS = "skins"
    PICKAXES = "pickaxes"
    DANCES = "dances"
    GLIDERS = "gliders"
    WEAPONS = "weapons"
    AGENTS = "agents"
    BUDDIES = "buddies"
    PROFILES = "profiles"
    GAMES = "games"
    SOCIALCLUB = "socialclub"


class Format(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    SHORT = "short"
    CUSTOM = "custom"
    MFA_FILE_STEAM_ID = "mfa_file_steam_id"
    MFA_FILE_LOGIN = "mfa_file_login"


class Show(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    STICKIED = "stickied"
    DISCOUNT_REQUEST = "discount_request"
    IN_BUYERS_FAVORITES = "in_buyers_favorites"
    ACTIVE = "active"
    PAID = "paid"
    CLOSED = "closed"
    DELETED = "deleted"
    AWAITING = "awaiting"
    PRE_ACTIVE = "pre_active"
    PRE_UPLOAD = "pre_upload"
    PENDING_DELETION = "pending_deletion"
    CLOSED_INACTIVE = "closed_inactive"
    AUTO_BUMP = "auto_bump"


class ClaimState(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    ACTIVE = "active"
    SOLVED = "solved"
    REJECTED = "rejected"
    SETTLED = "settled"


class Status(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    PAID = "paid"
    NOT_PAID = "not_paid"


class HoldLengthOption(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    HOUR = "hour"
    DAY = "day"
    WEEK = "week"
    MONTH = "month"
    YEAR = "year"


class FieldsInclude(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    V_ = "*"
    SEARCH_HISTORY = "searchHistory"
    SAVED_SEARCH = "savedSearch"


class Action(StrEnum):
    """Generated by forge — DO NOT EDIT. From the official OpenAPI spec."""

    APPROVE = "approve"
    REJECT = "reject"
