"""Generated by forge — DO NOT EDIT.
Sourced from the official readme.io OpenAPI spec; re-run `python -m dev.codegen build`
to update.
"""

from __future__ import annotations

from pylzt.models.antipublic.extended_stats import ExtendedStats
from pylzt.models.base import LolzObject


class PublicCountLinesResponse(LolzObject):
    """Generated by forge — DO NOT EDIT. Sourced from the official OpenAPI spec.

    Docs: https://antipublic.readme.io/reference/publiccountlines-1
    """

    count: int | None = None
    extendedStats: ExtendedStats | None = None
